### PR TITLE
Change: Cycle through visible signals by default

### LINKED ISSUE #10118: [Bug]: «Сycle trough signal types» set to «Path signals only» by default
### Version of OpenTTD

OpenTTD 12.2 and newer

### Expected result

By default, ctrl+click scrolling through _«all visible signals»_ is set, so that players can fully use block signals at the touch of a single button, without having to look for anything in the settings. And since the signals menu is closed by default, new players will not get cycled through all 6 signals.

### Actual result

The default is cycle trough signals _«path signals only»_.
Even if the player has expanded the signal menu, he still has to select the desired block signal with the mouse.

But given that players mainly play either with PBS-only or with the entire range of signals, the default “cycle trough all visible signals” setting will be quite logical.

Also in settings there is also no option "loop through block signals only" clause. I definitely remember that it existed and it was more convenient to use signals via ctrl+click. The parameter is not so critical, but if it was already hidden in Advanced, why not give more choices?

### Steps to reproduce

1. Reset all settings in… settings (don't forget to backup your current openttd.cfg)
2. Open Railway signals menu
3. Press «Toggle showing advanced signals»
4. Try to build some old-scool station with large amount of different block-signals.

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

#10118 

The signal GUI by default shows only path signals. There's a separate setting to choose whether Ctrl-click cycles through path signals or all visible signals. When we only see path signals, this second setting does nothing. However, if a player expands the signal GUI to use more signals, they likely want to cycle through all visible signals (as was the default before #8688). Right now the default is path signals only, so they'd need to go into Settings and change that.

## Description

Changing the default only affects people who use block/presignals and don't already have an OpenTTD config file, and we can close #10118. 🙂 

## Limitations

The issue also requests an option to cycle through block signals only. That isn't covered in this PR.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by frosch123** [comment]
I don't understand the purpose of this setting. Is there some history with it?

I would understand a setting with values:
* one cycle through all (visible) signals
* two cycles: (oneway-pbs, twoway-pbs) and (normal block, pre, exit, combo)

But a setting that converts a non-path signal into a path signal and not back?
I think we should rather remove this setting :)

**Comment by 2TallTyler** [comment]
I agree. The function of this setting should be changed to two options:
1. Cycle through all visible signals
2. Cycle through this type of signal (block/pre or path)

**Comment by frosch123** [comment]
I wondered how often you actually use this:
* You only cycle signals when building them. One click for a block signal, 2 for a presignal, 3 for exit, ...
* The wrap-around is only relevant if you misclick and click too often.

I think a setting for this rare "misclick" thingie is a bit too much. So I think just removing this setting is quite valid.

**Comment by 2TallTyler** [comment]
I don't disagree for how I play the game, but I've learned not to assume that my way is best.

**Pull request closed without merging**
