### PR TITLE
Codechange: Simplify IsCompanyBuildableVehicleType.

### PR DESCRIPTION
**Pull request by J0anJosep**
## Motivation / Problem

None really.

## Description

IsCompanyBuildableVehicleType used a switch that can be replaced by a single comparison.

## Limitations

None

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
While it might be less code (so simpler), it isn't clearer in my opinion.

**Comment by J0anJosep** [comment]
> While it might be less code (so simpler), it isn't clearer in my opinion.

Just looking into the VehicleType enum makes it clear enough.

Maybe what is not clear is the name of the function. It is equivalent to `IsValidCompanyVehicleType`, which would fit better, as there are a lot of IsValid* functions, which usually use a simple comparison like this and not switches.

There are also some uses of `type < VEH_COMPANY_END` or something similar in several loops, which are way clearer than using `IsCompanyBuildableVehicleType(type)`.

**Comment by 2TallTyler** [comment]
`IsValidCompanyVehicleType()` does make more sense for how this is used.

I suppose my question here is: Is this a change for change's sake or is this refactoring ahead of a future PR?

**Comment by J0anJosep** [comment]
> `IsValidCompanyVehicleType()` does make more sense for how this is used.
> 
> I suppose my question here is: Is this a change for change's sake or is this refactoring ahead of a future PR?

Neither of the two. It is mostly to keep code consistent, as many other functions use this approach, and simple.

The `IsPlayerBuildableVehicleType` function was introduced in 2007 and the `VEH_COMPANY_END` constant was added in 2011. When `IsPlayerBuildableVehicleType` was introduced the constant didn't exist, so it was written with a switch. But had `VEH_COMPANY_END` been there, it would have used the constant, which is the natural way to do this.

**Review by 2TallTyler — APPROVED** [review]
Fine by me, I like consistency. 🤷

**Pull request merged**
