### PR TITLE
Change: Remove some tiny/colour strings

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

There are a few little strings with colour/size which are only used rarely.

## Description

Replace usage with the basic STR_JUST_XXX version, specifying colour and size as function parameters instead.

## Limitations

Incomplete...

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Had to force-push to fix the commit title typo.

**Review by LordAro — DISMISSED** [review]
:+1:

**Comment by PeterN** [comment]
Updated for change from `SetTextColour` to `SetTextStyle`.

**Comment by glx22** [comment]
59f6decd0c19b3ca495df782597a56250638e2d6 can be improved now

**Review by rubidium42 — DISMISSED** [review]

**Review by rubidium42 — APPROVED** [review]

**Pull request merged**
