### PR TITLE
Fix #8155: Roadtype speed limit in toolbar dropdown in scenario editor was doubled.

### LINKED ISSUE #8155: Roadtype speed limit values are doubled in scenario editor drop-down menu
## Version of OpenTTD
master-20200517
## Expected result
Speed limits are displayed correctly
## Actual result
Speed limits are not displayed correctly
## Steps to reproduce
 - Load any roadtype NewGRF with speed limits (RattRoads is shown below)
 - Observe speeds shown in the scenario editor menu vs everything else

screenshot#1

The doubling effect only appears on this drop-down menu and does not appear to affect anything functionally; it is merely cosmetic and limited to the scenario editor.

### PR DESCRIPTION
**Pull request by Yexo**

### CODE REVIEW

**Review by nielsmh — APPROVED** [review]

**Comment by LordAro** [comment]
At the risk of sounding silly, why is `/ 2` necessary at all? Why is `max_speed` double the actual value? Perhaps there should be a helper function to get it for you, so it doesn't get forgotten elsewhere?

**Comment by Yexo** [comment]
> At the risk of sounding silly, why is / 2 necessary at all? Why is max_speed double the actual value? Perhaps there should be a helper function to get it for you, so it doesn't get forgotten elsewhere?

This is absolutely a good point. For now I'm going to merge this first, since it is a trivial fix for an existing bug. I'll try to document and/or refactor the code in a separate PR to handle the unclarity of the code (I spend 10 minutes so far, and the reason isn't obvious to me yet).

**Comment by frosch123** [comment]
It's NewGRF speed units. They different for all vehicle types.
```
src/aircraft.h: int GetDisplaySpeed() const    { return this->cur_speed; }
src/roadveh.h:  int GetDisplaySpeed() const { return this->gcache.last_speed / 2; }
src/ship.h:     int GetDisplaySpeed() const { return this->cur_speed / 2; }
src/train.h:    int GetDisplaySpeed() const { return this->gcache.last_speed; }
```

**Comment by James103** [comment]
Quoting from https://wiki.openttd.org/?title=Game_mechanics#Vehicle_speeds:
> For trains and aircraft the raw speed is in km-ish/h, for road vehicles/ships in **0.5** km-ish/h. For trains and aircraft this step is done twice a tick, whereas ships and road vehicles do it once a tick.

In other words, the raw speed (the value stored in code) is doubled in code for road vehicles and ships because the physics calculations are only done once per tick on them compared to twice per tick for aircraft and trains. This is why `GetDisplaySpeed()` divides the speed by 2 before displaying them.

**Pull request merged**
