### PR TITLE
Feature: When filtering purchase list by cargo type, make buy button perform a refit if required.

### PR DESCRIPTION
**Pull request by PeterN**
This solves a user-experience issue where purchasing a vehicle ends up with the 'wrong' cargo type.

This turned out to be quite nasty to implement as testing a refit cost requires a vehicle to be present. This is achieved similarly to how autoreplace works, by buying the vehicle and then selling it again, if in test mode.

### CODE REVIEW

**Comment by PeterN** [comment]
Well played, "works" with clang, but nothing else. Oops!

**Comment by frosch123** [comment]
Is it possible to run a test-execute when selecting a vehicle, so stuff like _returned_refit_capacity can be shown?

**Comment by PeterN** [comment]
Good idea, that should allow the true cost to be shown as well.

**Comment by nielsmh** [comment]
This might also fix one of the things Samu has been complaining about repeatedly, that NoAI can't query the cost or capacity of a refit without purchasing? Although that would require a new API to purchase a vehicle already refitted too.

**Comment by PeterN** [comment]
Hmm, one issue is that the query requires a depot to operate from, so will only work on a purchase list window from a depot.

**Comment by glx22** [comment]
Using AITestMode() it's possible to query the cost I think, so it should be possible to add a new parameter to ScriptVehicle::BuildVehicle(). But for the capacity a new function similar to ScriptVehicle::GetRefitCapacity() will be needed.

**Review by michicc — COMMENTED** [review]
Did you check if autoreplace and clone work? `BuildReplacementVehicle` and `CmdCloneVehicle` both call `CmdBuildVehicle` and make separate refits later. As they pass 0 for the cargo type, the vehicles would be refitted to passengers first unless I misread the code somewhere.

**Comment by glx22** [comment]
AIs should be able to use this feature with https://github.com/PeterN/OpenTTD/pull/1

**Comment by PeterN** [comment]
@michicc Good catch. I've looked to see whether we can just use the buy & refit functionality for these but they try to preserve cargo subtype, so it's not really feasible. I have updated the calls so they don't do a refit.

**Comment by PeterN** [comment]
New functionality, when filtering from a depot view, the extra cost and the refitted cargo capacity are now shown.

**Review by michicc — DISMISSED** [review]

**Comment by PeterN** [comment]
Rebased due to conflict.

**Review by michicc — APPROVED** [review]

**Pull request merged**
