### PR TITLE
Change: Decrease the min #opcodes

### PR DESCRIPTION
**Pull request by SamuXarick**

### CODE REVIEW

**Comment by LordAro** [comment]
Please explain the reasoning behind this PR. Why is it necessary?

**Comment by SamuXarick** [comment]
It was an idea to help maintaining 33 fps with 15 AIs on 4096x4096 maps. Less max opcodes would help, but it would also make the AIs look rather innactive most of the time. I guess I just wanted to be able to insert a lower value than 5000 to see what it would look like.

**Comment by Moth-Tolias** [comment]
perhaps making this a configurable option would be possible?

**Comment by PeterN** [comment]
That's rather meta. A config option to set the minimum value of a config option...

**Comment by Moth-Tolias** [comment]
oh, gosh. I really should have focused a little more carefully while reading - sorry about that!

**Review by LordAro — APPROVED** [review]
Don't see why not, it's not changing default after all.
Perhaps the helptext could be updated to more clearly indicate that a lower number would slow AIs down ?

**Pull request merged**
