### PR TITLE
Codechange: Implement a constructor for CurrencySpec (fixes VS2017 compile failure)

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem
VS2017 [fails to compile](https://github.com/glx22/OpenTTD/actions/runs/507639860) our current code with 
```
  Error: ..\src\currency.cpp(69): error C2440: 'initializing': cannot convert from 'const char [3]' to 'char'
  ..\src\currency.cpp(69): note: There is no context in which this conversion is possible
```
While the error is weird (and probably incorrect as VS2019 has no issue with our code), I think implicit copy from `const char[]` (string literal) to `char[]` is not fully legit.

## Description
I added a constructor to do the copy without implicit casting.
Of course that removed the default constructor, so I re-added it.
And with that VS2017 [succeeds to build](https://github.com/glx22/OpenTTD/runs/1762162432)

## Limitations
None I can think of.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by LordAro — DISMISSED** [review]
LGTM

**Comment by LordAro** [comment]
Should we add windows-2016 to the CI, perhaps?

**Comment by glx22** [comment]
It's easy to enable both, test running on https://github.com/glx22/OpenTTD/actions/runs/510045181

**Comment by LordAro** [comment]
Might as well, I'd say. Not like there's extra expense or anything :)

**Review by LordAro — APPROVED** [review]

**Pull request merged**
