### PR TITLE
Change: Disallow taking over AI companies in multiplayer

### PR DESCRIPTION
**Pull request by SamuXarick**
https://www.tt-forums.net/viewtopic.php?p=1184335#p1184335

### CODE REVIEW

**Comment by PeterN** [comment]
Can you explain why it should be disallowed?

**Comment by SamuXarick** [comment]
> Can you explain why it should be disallowed?

Because they're legitimate competitors. I've tried AIs in multiplayer and it's unfair that HU players can buy 100% AI shares and only 75% HU shares. I'd like to have AI servers with shares, but not to the point that they're 100% buyable.

**Comment by SamuXarick** [comment]
Looks like this deserves a better explanation.

I like to be able to set up servers with AIs, where human companies can buy shares in AI companies as a strategy for making money. Players could invest part of their money on a rising AI company and them sell it at a later time to get a good sum in return.

 When I first set up a server like this, I didn't expect AIs to be totally buyable, it caught me by surprise when I saw people buying them out. I also think it's unfair for the reason that AIs are supposed to play with equal rules as HU companies. And there's another problem I forgot to mention, which is, it can mess up with the AI configuration slots. If I setup 2 AIs in the proper slots, then 1 is bought out, the next AI replacement could take a year before it starts, which may be enough time for a HU company to take over the slot that had the proper configuration.

**Comment by TrueBrain** [comment]
Currently I see no reason to accept this Pull Request. Thank you for your contribution though!

**Pull request closed without merging**
