### PR TITLE
Codechange: use C++ idioms to manage (network) packets

### PR DESCRIPTION
**Pull request by rubidium42**
## Motivation / Problem

There is a custom linked list, with custom methods to clear the memory.
Manual memory management.

Based on the function's signature it is not clear whether you are handing over ownership of the `Packet`, or not.

## Description

Use a `std::deque` instead of the custom linked list.
Use `std::unique_ptr<Packet>` for all functions/locations where ownership of the `Packet` is transferred.
Use `Packet &` anywhere where the ownership of the `Packet` is not transferred.

In the server code there are a few functions that check whether to ask for the game/company password. Instead of duplicating the code, I changed the respective functions to call the new `SendXXX` in the chain when they do not need to ask for the password. So now practically the send XXX and receive XXX functions need to know about the next step in the process, instead of multiple receive XXX functions having to know the next step in the process (`SendWelcome` was known by three receive XXX functions).

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by michicc** [comment]
Bikeshedding here: To be really explicit, one could use the `std::queue` container adapter here.

**Comment by rubidium42** [comment]
> Bikeshedding here: To be really explicit, one could use the `std::queue` container adapter here. It's even defaulting to `dequeue` for storage.

I could do that for half of the cases. The one in the save game writing is pushing the final size of the compressed save game in front of all the still to be sent data chunks.
For the actual queue in the socket handler there's no such requirement yet, so I could change it there.

**Comment by LordAro** [comment]
Perhaps a comment with the declaration explaining why std::queue can't be used?

**Review by LordAro — APPROVED** [review]
Seems like the sort of change where the compiler would flag up any issues

**Pull request merged**
