### PR TITLE
Change: When creating an industry move the origin tile to the center.

### PR DESCRIPTION
**Pull request by PeterN**
This does not affect anything about the industry itself, merely the initial tile is shifted before construction.

### CODE REVIEW

**Comment by Eddi-z** [comment]
Seems like a rather arbitrary and unfocused change to me. Does it actually solve any problems?

**Comment by PeterN** [comment]
Oops, was meant to be a draft for @andythenorth to test. But yes, I'm not sure what it solves.

**Comment by nielsmh** [comment]
I think this will break oil rig stations as they are currently implemented, perhaps specifically removal of them when the industry closes down.

**Comment by PeterN** [comment]
It won't, it just moves the build tile slightly, from then on everything is exactly the same.
However, closing now...
> 16:00 < andythenorth> peter1138: so 7258, doesn't really solve anything no :)

**Pull request closed without merging**
