### PR TITLE
Fix: [Script] Ensure building/removing rail lines can't be backwards and allow building/removing rail lines coming from or heading to the void

### PR DESCRIPTION
**Pull request by SamuXarick**
## Motivation / Problem
It is possible to build and remove a rail line backwards, using `ScriptRail.BuildRail` and `ScriptRail.RemoveRail`.
It is not possible to build or remove a rail line that is facing the void.

## Description
- Add the missing precondition that forbids `from` tile to be the same as `to` tile.
- For lines longer than 1 piece which makes the value of `diag_offset` to be 2 or more, the test was incomplete. It was not checking the direction going from a tile to another. The code below would solve it, but it would be difficult to describe in the documentation, so I opted for `DiagdirBetweenTiles`.
```
EnforcePrecondition(false, diag_offset <= 1 ||
			(::TileX(from) == ::TileX(tile) && ::TileX(tile) == ::TileX(to) && (int)::TileY(from) - (int)::TileY(tile) == ((int)::TileY(tile) - (int)::TileY(to)) / abs((int)::TileY(tile) - (int)::TileY(to))) ||
			(::TileY(from) == ::TileY(tile) && ::TileY(tile) == ::TileY(to) && (int)::TileX(from) - (int)::TileX(tile) == ((int)::TileX(tile) - (int)::TileX(to)) / abs((int)::TileX(tile) - (int)::TileX(to))));
```
- Replace the checks that test `IsValidTile` for `from` and `to` with a `MapSize` check. This allows building or removing rail facing the void.

## Limitations
If the void tiles on top left and top right are disabled, then the edge tiles are always ocean that can't be cleared. So there should be no worries about placing rail tiles there.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
Missing justification: What happens currently if from == to ?

**Comment by glx22** [comment]
I think it's to match the documentation stating `@pre from != to.`, but maybe the documentation is wrong (didn't check anything).

**Comment by SamuXarick** [comment]
> Missing justification: What happens currently if from == to ?

building rail

**Comment by glx22** [comment]
So if `from == to` it somehow looks like `BuildRailTrack`

**Comment by glx22** [comment]
> building rail
> 
Documentation says
```
Parameters
    from	The tile just before the tile to build on.
    tile	The first tile to build on.
    to	The tile just after the last tile to build on. 
```
I agree not everything is enforced, but it seems to build what it's supposed to build in the screenshot.

I'm not sure all the compat stuff is needed, as the function signature didn't change.

**Comment by SamuXarick** [comment]
Here's some examples what's happening right now with BuildRail. Running the same script...
image
Top right: this PR, AI API version requirements set to 14 - fails building backwards, and can build facing the void
Bottom left: 13.0-RC1, AI API version requirements set to 13 - builds backwards, can't build facing the void
Bottom right: this PR, AI API version requirements set to 13 - mimics 13.0-RC1

**Comment by 2TallTyler** [comment]
This PR is trying to solve two issues. 
- The missing precondition should be a separate PR. One thing per PR.
- Building to/from the void is a solution in search of a problem. And the function in the compat files is overly complex and impossible to review. 

I'm closing this PR, but feel free to open a new one to add the missing precondition.

**Pull request closed without merging**
