### PR TITLE
Add: k-d tree element checker function

### PR DESCRIPTION
**Pull request by GabdaZM**
Checks whether an element is in the k-d tree.

Is it intended to make it possible to add two different elements with the same coordinates? If so, this approach is not viable.

### CODE REVIEW

**Comment by nielsmh** [comment]
Multiple elements with same coordinates can exist, yes. It's possible to have two station signs on the same tile, if one of them is a "ghost" station, and the second non-ghost is built holding Ctrl.

**Comment by GabdaZM** [comment]
I've managed to try it out, and it seems like it works. Now it should handle multiple items with the same coordinates. This version is based on the `RemoveRecursive` function.

In the meantime I've realized that I don't need this function where I wanted to use it, but I think it good to have an element checker none the less.

**Comment by LordAro** [comment]
Not sure I like PRs that add code but don't use it. What's the usecase for this?

**Comment by GabdaZM** [comment]
Well, after realizing that I don't need this modification for my other PR (local town authority displaying), I cannot think of another useful usecase. That being said, I am not against closing this PR.

**Pull request closed without merging**
