### PR TITLE
Codechange: Shuffle members to reduce vehicle size.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Vehicle (and things inheriting from it) has lots of members, some of which are grouped by logical feature. This can result in unused gaps due to variable alignment.

## Description

Shuffle members around to reduce the size of these gaps.

| Object | Bytes in master | Bytes with PR |
| ------ | --------------- | ------------- |
| Vehicle | 576 | 552 |
| Train | 664 | 632 |
| RoadVehicle | 800 | 776 |
| Ship | 664 | 640 |
| Aircraft | 592 | 576 |
| EffectVehicle | 576 | 560 |

These are minor changes, but do add up with a moderately large game.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by 2TallTyler — COMMENTED** [review]
A question, because I don't know how this works: Why is no savegame conversion needed to tell saveload that the information has moved?

**Comment by glx22** [comment]
> A question, because I don't know how this works: Why is no savegame conversion needed to tell saveload that the information has moved?

Savegame code uses pointers to variable, so it's still fine.

**Comment by PeterN** [comment]
It's not being moved in the save game, only in memory

**Review by 2TallTyler — DISMISSED** [review]
Ah, I get it now. 😄

**Comment by PeterN** [comment]
Updated only for the `byte` to `uint8_t` change.

**Review by glx22 — APPROVED** [review]

**Pull request merged**
