### PR TITLE
Change: Don't apply forbid 90 deg turn settings to ships.

### PR DESCRIPTION
**Pull request by PeterN**
Is forbidding 90 degree turns for ships useful? Especially now that ships have extra handling for rotating on the spot.

### CODE REVIEW

**Comment by J0anJosep** [comment]
If it is not useful, it may be disabled by users.

It works as expected right now. I see no problem with it. I see more problems with OPF.

I use this feature and I like to use it with other patches I created. Can we keep this one? I see no problem in keeping it. Probably, the setting should be converted into two different settings (trains and ships), but that is another different thing that shouldn't be discussed on this PR.

**Comment by PeterN** [comment]
I've been working on adding a penalty for 90 degree turns instead, so that ships prefer not to, but still can.

**Comment by glx22** [comment]
Forbid 90° was a train thing anyway. It's the only transport type where it makes sense.

**Comment by PeterN** [comment]
Ok, so adding a penaltly for 90° turns only works when TrackDir is used as NodeKey instead of ExitDir, which is apparently a performance option. I think it'll mean it will search more tile combinations, which is not ideal. Might not be particularly problematic with the ship path cache now, though.

**Comment by PeterN** [comment]
This latest change only works properly with `pf.yapf.disable_node_optimization` on

**Comment by J0anJosep** [comment]
Isn't it better to address path penalties in a separate branch? One thing is removing 90 deg setting for ships and another is add path penalties.

**Comment by PeterN** [comment]
Yes, you are right, I got carried away. I will split that off.

**Comment by TrueBrain** [comment]
Make this a non-draft and lets merge it! (or possibly for 1.10?)

Side question: possibly we can also rename the variable to indicate it is trains only? Not worth it if it is a lot of effort, but it might avoid this conversation in the future :)

**Review by TrueBrain — APPROVED** [review]

**Pull request merged**
