### PR TITLE
Fix #7089: close NewGRF textfile windows when their data are invalid

### LINKED ISSUE #7089: Crash when Removing NewGRF from Active list
Steps
- launch OpenTTD
- click NewGRF Settings
- add a NewGRF to the top list
- select it at the top list
- click License
- without closing the License window
- remove the selected NewGRF

Crash!

### PR DESCRIPTION
**Pull request by glx22**
I think I handled all cases.

### CODE REVIEW

**Comment by glx22** [comment]
I'm thinking about another solution with less closing.

**Comment by glx22** [comment]
The other possible solution is c9bbbd202f4713a95821ab38051e59539d6dc29d

**Comment by LordAro** [comment]
Regardless of solution, it should be extended to ScriptTextfileWindow, which uses similar behaviour (See #7088)

**Comment by LordAro** [comment]
Both GRF & Script textfile windows get given pointers that have their data change underneath them, and I suspect that changing it so that the windows maintain their own state a bit more is going to be a fair bit more work

Personally, I'd like it so that the Window properly refers to a particular AI/GRF/GS, and doesn't change/care when the underlying slot is updated. As such I'd definitely prefer option 1 over option 2 as currently presented, anyway :)

**Comment by glx22** [comment]
Hmm maybe this window_number change should be on an higher level in the TextfileWindow hierarchy

**Review by LordAro — APPROVED** [review]

**Pull request merged**
