### PR TITLE
Codechange: rename .hpp to .h

### PR DESCRIPTION
**Pull request by rubidium42**
## Motivation / Problem

Someone was wondering why there are .hpp and .h files.

## Description

The .h files seem to be in the majority, so I renamed .hpp to .h.

I excluded the 3rdparty files (json.hpp and catch.hpp). I we were going with .hpp instead, then the other 3rdparty files should be excluded (format, monocypher, etc).

## Limitations

This is might be breaking a lot of patches. The third commit is completely scripted and can therefore easily be executed when you'd run into conflicts.
We might want to wait with merging this until just before branching for release 14.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
-1. Change for change's sake

**Comment by TrueBrain** [comment]
> -1. Change for change's sake

Given we had so many patch-breakers in 14.0, I would argue there isn't a better time. C-char -> std::string, formatting, uint8 -> uint8_t, etc etc. We dumped a lot in 14.0. So if we want to make extensions make sense, this is the moment, I would argue.

**Comment by LordAro** [comment]
I'm not concerned about patch breakers. I fail to see the justification for making this change. A mild bit of consistency isn't enough, personally

**Comment by glx22** [comment]
Wasn't it .hpp for headers with templates and .h for normal headers ?

**Comment by TrueBrain** [comment]
> Wasn't it .hpp for headers with templates and .h for normal headers ?

`If you are writing one or more template class in the dedicated header file, use file.hpp for its name instead of file.h. This will let others know that it is template library (includes also implementation), not just header with declarations.`

**Comment by PeterN** [comment]
I think we should 'fix' that rule, because it's pretty impossible to follow now.

**Pull request closed without merging**
