### PR TITLE
Fix: Moving cargo definition slots prevents normal town/industry behaviour.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

<s>NewGRFs can define additional passenger or mail type cargoes (with TE_PASSENGERS/TE_MAIL or CC_PASSENGERS/CC_MAIL) but they don't do a lot.</s>

NewGRFs can move passengers from CT_PASSENGERS or mail from CT_MAIL and everything looks fine in the UI but it isn't produced by towns, and aircraft cannot carry mail (if there was any to move...)

Subsidies...

## Description

<s>This changeset creates a list of passenger and mail type cargoes, and allows towns to produce the first available type.

Aircraft with mail use the first available mail type.</s>

This changeset creates a cargo translation map between base climate cargo types and the active cargo types, and uses the translation map when determining what cargo to accept/produce for towns/default houses/default industries.

Vehicles already used a cargo translation lookup, which is now switched to use the map, and the hardcoded CT_MAIL for aircraft is now mapped as well.

This change no longer changes the game's behaviour when multiple cargoes providing town effect or cargo classes are installed.

## Limitations

WIP!

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Possibly cargo classes / town effect should have more impact on what happens with cargo produced by towns. While individual houses have acceptance, they don't have production settings.

**Comment by andythenorth** [comment]
Does this cover the case where grfs defining cargo have to place them in specific slots (IDs), otherwise house acceptance will be 'strange'?

https://github.com/andythenorth/firs/blob/main/src/economies/basic_arctic.py#L6

**Comment by PeterN** [comment]
Yes, this is pretty much all it does right now.

**Comment by PeterN** [comment]
This would 'break' cargo NewGRFs that rely on the current behaviour (Improved Town Industries is one I've been told about) but actually their behaviour is already broken for aircraft -- and it's possible to be fixed by the NewGRF implementing the town production callback.

**Comment by PeterN** [comment]
Superseded by #11719

**Pull request closed without merging**
