### PR TITLE
Change: Adjust spacing and layout of Company windows.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Company details, face and finance windows use lots of spacers and padding to produce their layout. This makes them complex to deal with.

image
image
image

## Description

Adjust layouts to use `WidgetDimension` spacing where possible and make use of PIP/PIPRatio to complete the layout.

This also puts the multiplayer buttons of the company window back where they belong (being broken when company shares was removed.)

image
image
image

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by 2TallTyler — COMMENTED** [review]
Is there a constant that could be used for the line instead of `top - 1`?

**Comment by PeterN** [comment]
> Is there a constant that could be used for the line instead of `top - 1`?

It's basically "bottom = top + height -1", so not really magic, imho.

**Comment by 2TallTyler** [comment]
But what's the -1? Why isn't it `bottom = height + top`?

**Comment by PeterN** [comment]
> But what's the -1? Why isn't it `bottom = height + top`?

Because GfxFillRect's parameters are inclusive. If bottom is top + 2 then it will draw at top, top + 1 and top + 2.

**Review by 2TallTyler — APPROVED** [review]
I don't love the potential for off-by-one errors, but that's not the fault of this PR, I guess.

**Pull request merged**
