### PR TITLE
Change: Increase cargo type limit to 64 (bitset variant)

### PR DESCRIPTION
**Pull request by PeterN**
This variant adds helper functions to work with std::bitset, and uses a bitset in graph_gui.cpp.

CargoTypes is not a bitset because saveload does not support it.

### CODE REVIEW

**Comment by nielsmh** [comment]
How many bitset-like types are stored in a savegame? Could it perhaps make sense to extend the save-load framework to straight-up support std::bitset types directly?

**Comment by PeterN** [comment]
@nielsmh Not a lot, they tend to be stuff that's calculated on load.

**Comment by PeterN** [comment]
Not sure what's up with the OSX build?

**Comment by michicc** [comment]
`bitset` on OSX seems to have a member/method/something called `type`, and `sqobject.h` has a `#define type` in it. The classic defines are evil stuff.

**Comment by andythenorth** [comment]
Builds for me on macOS 10.12.6  / Apple LLVM version 9.0.0 (clang-900.0.39.2)

Unless I'm doing it wrong :P

**Comment by PeterN** [comment]
Obsoleted by #6802

**Pull request closed without merging**
