### PR TITLE
Refactor GUI rendering: Add documentation and name `Viewport` consistently

### PR DESCRIPTION
**Pull request by techgeeknz**
This is split off from #8217; part 3 of 3.
This should use https://github.com/OpenTTD/OpenTTD/pull/8256 as a base.

### CODE REVIEW

**Comment by LordAro** [comment]
When I said split the viewport rename out into a separate PR, I meant that it should precede it and have nothing to do with the GUI rendering PR. Currently this just serves to bloat the size of the whole PR, making changes to code you've just added. *And* make it more difficult to review, since you've basically just duplicated the PR 3 times over.

**Comment by techgeeknz** [comment]
> When I said split the viewport rename out into a separate PR, I meant that it should precede it and have nothing to do with the GUI rendering PR.

So the renaming of `ViewPort` is definitely something that you want; and you want it done first? Okay, I can do that.
I'd had it set up so that would happen last, making it easier to skip if it turned out to be an undesirable change.

**Comment by techgeeknz** [comment]
> Currently this just serves to bloat the size of the whole PR, making changes to code you've just added. _And_ make it more difficult to review, since you've basically just duplicated the PR 3 times over.

I'm not really sure what you want me to do. I've split the PR into three separate branches so they can be reviewed separately. Clearly, they can't all be based on the same version of `master`; because they build upon each other. How else would you go about setting up large changes like this?

**Comment by LordAro** [comment]
I want this PR to deal with renaming ViewPort and *only* renaming ViewPort. None of the other changes.

**Comment by techgeeknz** [comment]
> I want this PR to deal with renaming ViewPort and _only_ renaming ViewPort. None of the other changes.

That is more-or-less exactly what it does. Try differencing it to the final commit of the previous PR.

**Pull request closed without merging**
