### PR TITLE
Change: store crash logs in JSON format

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

A few things are coming together:

- I want to transmit crashes to us automatically (opt-in, ofc) when they happen. This to better react to bugs in our software. By the looks, there are very few crashes going on, but often we depend on users reporting them, and it can be a bit of a struggle to get the right files delivered to us. By automating this, I hope to make us a bit more responsive to fuck-ups, especially just after a release.
- Survey code looks up various of system-information, and the crashlog does too. But in the way the crashlog was written, it was nearly impossible to reuse that code. High on my wish-list was still a way to fix that, and deduplicate this information.
- Crash logs were wildly different between OSes, mostly for no real reason.

In an attempt to prepare for the first and address the other two, I created this PR.

## Description

The first commit contains moving of some code around, to make the next commit easier. GitHub doesn't show this well, but if you use `git diff HEAD^^..HEAD^ --color-moved` on this PR, you see with colour that it is moved code.

Instead of generating a `crash.log`, a crash now generates a `crash.json.log` (the extra `.log` is needed, as you are not allowed to upload a `.json` to GitHub .. so to make it easier for manual uploads, add another `.log`). Initially I wanted to convert the JSON back to a log-like file, but I realised that wouldn't actually add value. A human can read the JSON just as well as a flat file, and skipping another conversion sounds like a win.

During a crash, a short summary is printed to the console, as especially on Linux we are kinda used to seeing the stacktrace there.

The Crashlog contains slightly more information than the Survey. Most noticeable, the stacktrace (duh), the gamelog and recent news. None of them are needed for the Survey.

Tested on the following platforms:
- x64-linux
- x64-windows
- x64-macos

Example JSON file:
[crash20230827121137.json.txt](https://github.com/OpenTTD/OpenTTD/files/12447937/crash20230827121137.json.txt)

<details><summary>In-line example</summary>

```
{
    "crash": {
        "id": 11,
        "reason": "Segmentation fault"
    },
    "date": "2023-08-27 12:11:37 (UTC)",
    "game": {
        "companies": {
            "0": {
                "infrastructure": {
                    "airport": 0,
                    "rail": 0,
                    "road": 0,
                    "signal": 0,
                    "station": 0,
                    "tram": 0,
                    "water": 0
                },
                "type": "human",
                "vehicles": {
                    "aircraft": 0,
                    "roadveh": 0,
                    "ship": 0,
                    "train": 0
                }
            }
        },
        "current_company": 0,
        "game_script": null,
        "gamelog": [
            "---- gamelog start ----",
            "Tick 0: new game started",
            "Revision text changed to gab3efac73bbab8c3201b28747b6632490ac8b6f6, savegame version 317, not modified, _openttd_newgrf_version = 0x1e006d64",
            "New game mode: 1 landscape: 0",
            "Added NewGRF: GRF ID 54525531, checksum 3E7CE8D4C9D315257EB9CBE6D347AC9F, filename: test.grf (md5sum matches)",
            "Added NewGRF: GRF ID F1250007, checksum E3933F6F3FF709CA300D41308B0BE8BD, filename: firs_industry_replacement_set_3-3.0.10/firs.grf (md5sum matches)",
            "---- gamelog end ----"
        ],
        "grfs": {
            "54525531": {
                "blitter": "unset",
                "is_static": false,
                "md5sum": "3E7CE8D4C9D315257EB9CBE6D347AC9F",
                "palette": "dos",
                "parameters": [],
                "status": "disabled"
            },
            "f1250007": {
                "blitter": "unset",
                "is_static": false,
                "md5sum": "E3933F6F3FF709CA300D41308B0BE8BD",
                "palette": "dos",
                "parameters": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    16,
                    150,
                    80,
                    300
                ],
                "status": "activated"
            }
        },
        "local_company": 0,
        "news": [],
        "settings": {
            "ai.ai_disable_veh_aircraft": "false",
            "ai.ai_disable_veh_roadveh": "false",
            "ai.ai_disable_veh_ship": "false",
            "ai.ai_disable_veh_train": "false",
            "ai.ai_in_multiplayer": "true",
            "blitter": "",
            "construction.autoslope": "true",
            "construction.build_object_frame_burst": "2048",
            "construction.build_object_per_64k_frames": "2097152",
            "construction.build_on_slopes": "true",
            "construction.clear_frame_burst": "4096",
            "construction.clear_per_64k_frames": "4194304",
            "construction.command_pause_level": "1",
            "construction.extra_dynamite": "true",
            "construction.extra_tree_placement": "2",
            "construction.freeform_edges": "true",
            "construction.industry_platform": "1",
            "construction.map_height_limit": "30",
            "construction.max_bridge_height": "12",
            "construction.max_bridge_length": "64",
            "construction.max_tunnel_length": "64",
            "construction.raw_industry_construction": "0",
            "construction.road_stop_on_competitor_road": "true",
            "construction.road_stop_on_town_road": "true",
            "construction.terraform_frame_burst": "4096",
            "construction.terraform_per_64k_frames": "4194304",
            "construction.train_signal_side": "1",
            "construction.tree_frame_burst": "4096",
            "construction.tree_per_64k_frames": "4194304",
            "difficulty.competitor_speed": "2",
            "difficulty.competitors_interval": "1",
            "difficulty.construction_cost": "0",
            "difficulty.disasters": "false",
            "difficulty.economy": "false",
            "difficulty.industry_density": "1",
            "difficulty.initial_interest": "2",
            "difficulty.line_reverse_mode": "false",
            "difficulty.max_loan": "300000",
            "difficulty.max_no_competitors": "1",
            "difficulty.number_towns": "0",
            "difficulty.quantity_sea_lakes": "0",
            "difficulty.subsidy_duration": "1",
            "difficulty.subsidy_multiplier": "2",
            "difficulty.terrain_type": "1",
            "difficulty.town_council_tolerance": "0",
            "difficulty.vehicle_breakdowns": "1",
            "difficulty.vehicle_costs": "0",
            "display_opt": "SHOW_TOWN_NAMES|SHOW_STATION_NAMES|SHOW_SIGNS|WAYPOINTS|SHOW_COMPETITOR_SIGNS",
            "economy.allow_town_level_crossings": "true",
            "economy.allow_town_roads": "true",
            "economy.bribe": "true",
            "economy.dist_local_authority": "20",
            "economy.exclusive_rights": "true",
            "economy.feeder_payment_share": "75",
            "economy.found_town": "0",
            "economy.fund_buildings": "true",
            "economy.fund_roads": "true",
            "economy.give_money": "true",
            "economy.inflation": "false",
            "economy.infrastructure_maintenance": "false",
            "economy.initial_city_size": "2",
            "economy.larger_towns": "4",
            "economy.mod_road_rebuild": "true",
            "economy.multiple_industry_per_town": "false",
            "economy.station_noise_level": "false",
            "economy.town_cargogen_mode": "1",
            "economy.town_growth_rate": "2",
            "economy.town_layout": "0",
            "economy.town_noise_population[0]": "800",
            "economy.town_noise_population[1]": "2000",
            "economy.town_noise_population[2]": "4000",
            "economy.town_noise_population[3]": "400",
            "economy.type": "1",
            "engine_renew": "true",
            "engine_renew_money": "100000",
            "engine_renew_months": "6",
            "fullscreen": "false",
            "game_creation.amount_of_rivers": "0",
            "game_creation.custom_industry_number": "1",
            "game_creation.custom_sea_level": "1",
            "game_creation.custom_terrain_type": "30",
            "game_creation.custom_town_number": "1",
            "game_creation.desert_coverage": "50",
            "game_creation.ending_year": "2050",
            "game_creation.generation_seed": "2865075882",
            "game_creation.heightmap_height": "30",
            "game_creation.heightmap_rotation": "0",
            "game_creation.land_generator": "1",
            "game_creation.landscape": "temperate",
            "game_creation.map_x": "8",
            "game_creation.map_y": "8",
            "game_creation.min_river_length": "16",
            "game_creation.oil_refinery_limit": "32",
            "game_creation.river_route_random": "5",
            "game_creation.se_flat_world_height": "1",
            "game_creation.snow_coverage": "40",
            "game_creation.snow_line_height": "10",
            "game_creation.starting_year": "1950",
            "game_creation.tgen_smoothness": "1",
            "game_creation.town_name": "english",
            "game_creation.tree_placer": "2",
            "game_creation.variety": "0",
            "game_creation.water_borders": "15",
            "graphicsset": "\"OpenGFX\"",
            "gui.advanced_vehicle_list": "1",
            "gui.ai_developer_tools": "false",
            "gui.auto_euro": "true",
            "gui.auto_remove_signals": "false",
            "gui.auto_scrolling": "0",
            "gui.autosave_interval": "120",
            "gui.autosave_on_exit": "false",
            "gui.autosave_on_network_disconnect": "true",
            "gui.coloured_news_year": "2000",
            "gui.console_backlog_length": "100",
            "gui.console_backlog_timeout": "100",
            "gui.cycle_signal_types": "0",
            "gui.date_format_in_default_names": "iso",
            "gui.default_rail_type": "0",
            "gui.default_signal_type": "5",
            "gui.developer": "1",
            "gui.drag_signals_density": "4",
            "gui.drag_signals_fixed_distance": "false",
            "gui.errmsg_duration": "5",
            "gui.fast_forward_speed_limit": "2500",
            "gui.graph_line_thickness": "3",
            "gui.hover_delay_ms": "250",
            "gui.keep_all_autosave": "false",
            "gui.link_terraform_toolbar": "false",
            "gui.linkgraph_colours": "0",
            "gui.liveries": "2",
            "gui.loading_indicators": "1",
            "gui.lost_vehicle_warn": "true",
            "gui.max_num_autosaves": "16",
            "gui.measure_tooltip": "true",
            "gui.missing_strings_threshold": "25",
            "gui.network_chat_box_height": "25",
            "gui.network_chat_box_width_pct": "40",
            "gui.network_chat_timeout": "20",
            "gui.new_nonstop": "true",
            "gui.newgrf_default_palette": "1",
            "gui.newgrf_developer_tools": "true",
            "gui.newgrf_show_old_versions": "false",
            "gui.news_message_timeout": "2",
            "gui.order_review_system": "2",
            "gui.osk_activation": "double",
            "gui.pause_on_newgame": "false",
            "gui.persistent_buildingtools": "true",
            "gui.population_in_label": "true",
            "gui.prefer_teamchat": "false",
            "gui.quick_goto": "true",
            "gui.refresh_rate": "60",
            "gui.right_click_wnd_close": "yes",
            "gui.scale_bevels": "true",
            "gui.scenario_developer": "false",
            "gui.scroll_mode": "2",
            "gui.scrollwheel_multiplier": "5",
            "gui.scrollwheel_scrolling": "0",
            "gui.semaphore_build_before": "1950",
            "gui.settings_restriction_mode": "2",
            "gui.show_cargo_in_vehicle_lists": "false",
            "gui.show_date_in_logs": "false",
            "gui.show_finances": "true",
            "gui.show_newgrf_name": "false",
            "gui.show_track_reservation": "true",
            "gui.signal_gui_mode": "0",
            "gui.smallmap_land_colour": "0",
            "gui.smooth_scroll": "false",
            "gui.sprite_zoom_min": "0",
            "gui.starting_colour": "16",
            "gui.starting_colour_secondary": "16",
            "gui.station_dragdrop": "true",
            "gui.station_gui_group_order": "4",
            "gui.station_gui_sort_by": "0",
            "gui.station_gui_sort_order": "0",
            "gui.station_numtracks": "1",
            "gui.station_platlength": "5",
            "gui.station_show_coverage": "false",
            "gui.statusbar_pos": "1",
            "gui.stop_location": "2",
            "gui.threaded_saves": "true",
            "gui.timetable_arrival_departure": "true",
            "gui.timetable_in_ticks": "false",
            "gui.toolbar_pos": "1",
            "gui.vehicle_income_warn": "true",
            "gui.window_snap_radius": "10",
            "gui.window_soft_limit": "20",
            "gui.zoom_max": "5",
            "gui.zoom_min": "0",
            "gui_scale": "200",
            "invisibility_options": "0",
            "keyboard": "",
            "keyboard_caps": "",
            "language": "english.lng",
            "large_aa": "false",
            "large_font": "DejaVu Sans",
            "large_size": "0",
            "last_newgrf_count": "74",
            "linkgraph.accuracy": "16",
            "linkgraph.demand_distance": "100",
            "linkgraph.demand_size": "100",
            "linkgraph.distribution_armoured": "1",
            "linkgraph.distribution_default": "1",
            "linkgraph.distribution_mail": "1",
            "linkgraph.distribution_pax": "1",
            "linkgraph.recalc_interval": "90",
            "linkgraph.recalc_time": "512",
            "linkgraph.short_path_saturation": "80",
            "locale.currency": "GBP",
            "locale.digit_decimal_separator": "",
            "locale.digit_group_separator": "",
            "locale.digit_group_separator_currency": "",
            "locale.units_force": "si",
            "locale.units_height": "metric",
            "locale.units_power": "metric",
            "locale.units_velocity": "gameunits",
            "locale.units_velocity_nautical": "metric",
            "locale.units_volume": "metric",
            "locale.units_weight": "metric",
            "medium_aa": "false",
            "medium_font": "DejaVu Sans",
            "medium_size": "0",
            "mono_aa": "false",
            "mono_font": "",
            "mono_size": "0",
            "music.custom_1": "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
            "music.custom_2": "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
            "music.effect_vol": "100",
            "music.music_vol": "50",
            "music.playing": "true",
            "music.playlist": "0",
            "music.shuffle": "false",
            "musicdriver": "",
            "musicset": "",
            "network.autoclean_companies": "false",
            "network.autoclean_novehicles": "0",
            "network.autoclean_protected": "36",
            "network.autoclean_unprotected": "12",
            "network.bytes_per_frame": "8",
            "network.bytes_per_frame_burst": "256",
            "network.commands_per_frame": "2",
            "network.commands_per_frame_server": "16",
            "network.frame_freq": "0",
            "network.max_clients": "25",
            "network.max_commands_in_queue": "16",
            "network.max_companies": "15",
            "network.max_download_time": "1000",
            "network.max_init_time": "100",
            "network.max_join_time": "500",
            "network.max_lag_time": "500",
            "network.max_password_time": "2000",
            "network.min_active_clients": "0",
            "network.pause_on_join": "true",
            "network.reload_cfg": "false",
            "network.restart_game_year": "0",
            "network.server_admin_chat": "true",
            "network.server_admin_port": "3977",
            "network.server_game_type": "local",
            "network.server_port": "12346",
            "network.sync_freq": "100",
            "news_display.acceptance": "full",
            "news_display.accident": "full",
            "news_display.accident_other": "full",
            "news_display.advice": "full",
            "news_display.arrival_other": "summarized",
            "news_display.arrival_player": "full",
            "news_display.close": "summarized",
            "news_display.company_info": "full",
            "news_display.economy": "full",
            "news_display.general": "full",
            "news_display.new_vehicles": "full",
            "news_display.open": "summarized",
            "news_display.production_nobody": "off",
            "news_display.production_other": "off",
            "news_display.production_player": "summarized",
            "news_display.subsidies": "off",
            "order.gradual_loading": "true",
            "order.improved_load": "true",
            "order.no_servicing_if_no_breakdowns": "true",
            "order.selectgoods": "true",
            "order.serviceathelipad": "true",
            "pf.forbid_90_deg": "false",
            "pf.npf.maximum_go_to_depot_penalty": "2000",
            "pf.npf.npf_buoy_penalty": "200",
            "pf.npf.npf_crossing_penalty": "300",
            "pf.npf.npf_max_search_nodes": "10000",
            "pf.npf.npf_rail_curve_penalty": "100",
            "pf.npf.npf_rail_depot_reverse_penalty": "5000",
            "pf.npf.npf_rail_firstred_exit_penalty": "10000",
            "pf.npf.npf_rail_firstred_penalty": "1000",
            "pf.npf.npf_rail_lastred_penalty": "1000",
            "pf.npf.npf_rail_pbs_cross_penalty": "300",
            "pf.npf.npf_rail_pbs_signal_back_penalty": "1500",
            "pf.npf.npf_rail_slope_penalty": "100",
            "pf.npf.npf_rail_station_penalty": "100",
            "pf.npf.npf_road_bay_occupied_penalty": "1500",
            "pf.npf.npf_road_curve_penalty": "100",
            "pf.npf.npf_road_drive_through_penalty": "800",
            "pf.npf.npf_road_dt_occupied_penalty": "800",
            "pf.npf.npf_water_curve_penalty": "100",
            "pf.path_backoff_interval": "20",
            "pf.pathfinder_for_roadvehs": "2",
            "pf.pathfinder_for_ships": "2",
            "pf.pathfinder_for_trains": "2",
            "pf.reserve_paths": "false",
            "pf.reverse_at_signals": "false",
            "pf.roadveh_queue": "true",
            "pf.wait_for_pbs_path": "30",
            "pf.wait_oneway_signal": "15",
            "pf.wait_twoway_signal": "41",
            "pf.yapf.disable_node_optimization": "false",
            "pf.yapf.max_search_nodes": "10000",
            "pf.yapf.maximum_go_to_depot_penalty": "2000",
            "pf.yapf.rail_crossing_penalty": "300",
            "pf.yapf.rail_curve45_penalty": "100",
            "pf.yapf.rail_curve90_penalty": "600",
            "pf.yapf.rail_depot_reverse_penalty": "5000",
            "pf.yapf.rail_doubleslip_penalty": "100",
            "pf.yapf.rail_firstred_exit_penalty": "10000",
            "pf.yapf.rail_firstred_penalty": "1000",
            "pf.yapf.rail_firstred_twoway_eol": "true",
            "pf.yapf.rail_lastred_exit_penalty": "10000",
            "pf.yapf.rail_lastred_penalty": "1000",
            "pf.yapf.rail_longer_platform_penalty": "800",
            "pf.yapf.rail_longer_platform_per_tile_penalty": "0",
            "pf.yapf.rail_look_ahead_max_signals": "10",
            "pf.yapf.rail_look_ahead_signal_p0": "500",
            "pf.yapf.rail_look_ahead_signal_p1": "-100",
            "pf.yapf.rail_look_ahead_signal_p2": "5",
            "pf.yapf.rail_pbs_cross_penalty": "300",
            "pf.yapf.rail_pbs_signal_back_penalty": "1500",
            "pf.yapf.rail_pbs_station_penalty": "800",
            "pf.yapf.rail_shorter_platform_penalty": "4000",
            "pf.yapf.rail_shorter_platform_per_tile_penalty": "0",
            "pf.yapf.rail_slope_penalty": "200",
            "pf.yapf.rail_station_penalty": "1000",
            "pf.yapf.road_crossing_penalty": "300",
            "pf.yapf.road_curve_penalty": "100",
            "pf.yapf.road_slope_penalty": "200",
            "pf.yapf.road_stop_bay_occupied_penalty": "1500",
            "pf.yapf.road_stop_occupied_penalty": "800",
            "pf.yapf.road_stop_penalty": "800",
            "pf.yapf.ship_curve45_penalty": "100",
            "pf.yapf.ship_curve90_penalty": "600",
            "player_face": "0",
            "prefix": "",
            "rate": "1",
            "renew_keep_length": "false",
            "resolution": "1188,979",
            "rightclick_emulate": "false",
            "savegame_format": "",
            "screenshot_format": "",
            "script.script_max_memory_megabytes": "1024",
            "script.script_max_opcode_till_suspend": "10000",
            "script.settings_profile": "easy",
            "separator": "\".\"",
            "small_aa": "false",
            "small_font": "DejaVu Sans",
            "small_size": "0",
            "sound.ambient": "true",
            "sound.click_beep": "true",
            "sound.confirm": "true",
            "sound.disaster": "true",
            "sound.new_year": "true",
            "sound.news_full": "true",
            "sound.news_ticker": "true",
            "sound.vehicle": "true",
            "sounddriver": "",
            "soundsset": "\"NoSound\"",
            "sprite_cache_size_px": "128",
            "station.adjacent_stations": "true",
            "station.distant_join_stations": "true",
            "station.modified_catchment": "true",
            "station.never_expire_airports": "false",
            "station.serve_neutral_industries": "true",
            "station.station_spread": "12",
            "suffix": "\" credits\"",
            "support8bpp": "no",
            "to_euro": "0",
            "transparency_locks": "0",
            "transparency_options": "511",
            "vehicle.disable_elrails": "false",
            "vehicle.dynamic_engines": "true",
            "vehicle.extend_vehicle_life": "0",
            "vehicle.freight_trains": "1",
            "vehicle.max_aircraft": "200",
            "vehicle.max_roadveh": "500",
            "vehicle.max_ships": "300",
            "vehicle.max_train_length": "7",
            "vehicle.max_trains": "500",
            "vehicle.never_expire_vehicles": "false",
            "vehicle.plane_crashes": "2",
            "vehicle.plane_speed": "4",
            "vehicle.road_side": "right",
            "vehicle.roadveh_acceleration_model": "1",
            "vehicle.roadveh_slope_steepness": "7",
            "vehicle.servint_aircraft": "100",
            "vehicle.servint_ispercent": "false",
            "vehicle.servint_roadveh": "150",
            "vehicle.servint_ships": "360",
            "vehicle.servint_trains": "150",
            "vehicle.smoke_amount": "1",
            "vehicle.train_acceleration_model": "1",
            "vehicle.train_slope_steepness": "3",
            "vehicle.wagon_speed_limits": "true",
            "video_hw_accel": "false",
            "video_vsync": "false",
            "videodriver": ""
        },
        "timers": {
            "calendar": "1950-01-01 (36)",
            "seconds": 1,
            "ticks": 1316
        }
    },
    "info": {
        "compiler": {
            "extra": "Ubuntu Clang 14.0.0",
            "name": "GCC",
            "version": "4.2.1"
        },
        "configuration": {
            "blitter": "32bpp-optimized",
            "graphics_set": "OpenGFX.7938",
            "language": {
                "filename": "english.lng",
                "isocode": "en_GB",
                "name": "English (UK)"
            },
            "music_driver": "extmidi",
            "music_set": "Radio Monochrome Volume 1..0",
            "network": "no",
            "sound_driver": "sdl",
            "sound_set": "NoSound.2",
            "video_driver": "sdl",
            "video_info": "sdl (x11)"
        },
        "font": {
            "large": "DejaVu Sans, Book",
            "medium": "DejaVu Sans, Book",
            "mono": "sprite",
            "small": "DejaVu Sans, Book"
        },
        "libraries": {
            "curl": "8.1.2-DEV",
            "curl_ssl": "OpenSSL/3.1.1",
            "fontconfig": "2.13.1",
            "freetype": "2.11.1",
            "harfbuzz": "2.7.4",
            "icu_i18n": "70.1",
            "lzma": "5.4.1",
            "lzo": "2.10",
            "png": "1.6.39",
            "sdl2": "2.26.5",
            "zlib": "1.2.13"
        },
        "openttd": {
            "bits": 64,
            "build_date": "Aug 27 2023 14:10:32",
            "dedicated_build": "no",
            "endian": "little",
            "newgrf_version": 503344484,
            "version": "20230827-crashlog-json-gab3efac73b",
            "version_modified": 0
        },
        "os": {
            "hardware_concurrency": 12,
            "machine": "x86_64",
            "memory": "16 GiB",
            "os": "Linux",
            "release": "5.15.90.4-microsoft-standard-WSL2",
            "version": "#1 SMP Tue Jul 18 21:28:32 UTC 2023"
        }
    },
    "schema": 1,
    "stacktrace": [
        "./openttd(_ZNK12CrashLogUnix16SurveyStacktraceERN8nlohmann16json_abi_v3_11_210basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS1_14adl_serializerES4_IhSaIhEEEE+0x24) [0x559789eae984]",
        "./openttd(_ZN8CrashLog12FillCrashLogEv+0x3d1) [0x55978a0d9501]",
        "./openttd(_ZN8CrashLog12MakeCrashLogEv+0x1d1) [0x55978a0db331]",
        "./openttd(+0x10e074f) [0x559789eae74f]",
        "/lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f1010b31520]",
        "./openttd(_ZN10MainWindow8OnHotkeyEi+0x1f5) [0x55978a226a35]",
        "./openttd(_Z14HandleKeypressjDi+0x1d4) [0x55978a64fbf4]",
        "./openttd(_ZN20VideoDriver_SDL_Base9PollEventEv+0x423) [0x55978a028303]",
        "./openttd(_ZN11VideoDriver4TickEv+0x1b4) [0x55978a030d44]",
        "./openttd(_ZN20VideoDriver_SDL_Base8LoopOnceEv+0x3b) [0x55978a0293cb]",
        "./openttd(_ZN20VideoDriver_SDL_Base8MainLoopEv+0x3d) [0x55978a02941d]",
        "./openttd(_Z12openttd_mainiPPc+0x2930) [0x55978a362e60]",
        "./openttd(main+0x7d) [0x559789a1022d]",
        "/lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f1010b18d90]",
        "/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f1010b18e40]",
        "./openttd(_start+0x25) [0x559789a100e5]"
    ]
}
```
</details>

## Limitations

- I am not 100% sure that adding settings in the `crash.json.log` is all that useful. I welcome opinions on the matter. Update: see below, it changed into settings_changed, only showing settings that are not the default.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by glx22** [comment]
With settings we can see if info/configuration is auto-detected or forced.

**Comment by LordAro** [comment]
With that in mind, would it be worth *only* including non-default settings? Would shorten the output a fair bit

**Comment by TrueBrain** [comment]
> With that in mind, would it be worth _only_ including non-default settings? Would shorten the output a fair bit

Less trivial than I would have liked, but doable. You get something like this:

```
"settings_changed": {
            "construction.map_height_limit": "30",
            "difficulty.competitors_interval": "1",
            "difficulty.industry_density": "1",
            "difficulty.max_no_competitors": "1",
            "difficulty.number_towns": "0",
            "display_opt": "SHOW_TOWN_NAMES|SHOW_STATION_NAMES|SHOW_SIGNS|WAYPOINTS|SHOW_COMPETITOR_SIGNS",
            "game_creation.amount_of_rivers": "0",
            "game_creation.generation_seed": "1231893898",
            "graphicsset": "\"OpenGFX\"",
            "gui.autosave_interval": "120",
            "gui.newgrf_developer_tools": "true",
            "gui.right_click_wnd_close": "yes",
            "gui.settings_restriction_mode": "2",
            "gui.station_gui_group_order": "4",
            "gui_scale": "200",
            "language": "english.lng",
            "large_font": "DejaVu Sans",
            "last_newgrf_count": "74",
            "linkgraph.distribution_armoured": "1",
            "linkgraph.distribution_default": "1",
            "linkgraph.distribution_mail": "1",
            "linkgraph.distribution_pax": "1",
            "linkgraph.recalc_interval": "90",
            "linkgraph.recalc_time": "512",
            "locale.units_velocity": "gameunits",
            "medium_font": "DejaVu Sans",
            "music.custom_1": "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
            "music.custom_2": "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0",
            "network.server_port": "12346",
            "news_display.subsidies": "off",
            "pf.forbid_90_deg": "false",
            "resolution": "1188,979",
            "small_font": "DejaVu Sans",
            "soundsset": "\"NoSound\"",
            "transparency_options": "511",
            "video_hw_accel": "false"
        },
```

**Review by glx22 — APPROVED** [review]
Using JSON doesn't remove anything from the old format (we even gain some more data).
And reducing code duplication is always good.

**Pull request merged**
