### PR TITLE
Fix: marked text was not updated during text deletion

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem
* open the console
* switch keyboard to japanese IME
* enter non latin text
* trigger https://github.com/OpenTTD/OpenTTD/blob/master/src/gfx.cpp#L883

It crashes because `markend` can be outside of the string after text deletion.

## Description
Properly update marked text start and end during text deletion, like it was already done for caret.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by TrueBrain — DISMISSED** [review]
That is most likely one of the more complex ways I have seen a function do stuff, but given it is a copy/paste of an earlier if, let's go with it :)

**Comment by glx22** [comment]
Now I think I should write a function as the "same" thing is done at least 3 times :)

**Comment by michicc** [comment]
Specifically for #11291, https://gist.github.com/michicc/59a204d99d0321ae4592b4b9d32ad93a would do it, too.

**Comment by michicc** [comment]
Thinking more, I think both is needed, as `Textbuf::InsertString` also has a code path that does not call `DeleteText` but only `DiscardMarkedText`.

**Comment by glx22** [comment]
Reduced copy/paste.

> Thinking more, I think both is needed, as `Textbuf::InsertString` also has a code path that does not call `DeleteText` but only `DiscardMarkedText`.

`DiscardMarkedText` calls `DeleteText`, so I don't think it's needed to touch `Textbuf::DiscardMarkedText`.

**Comment by michicc** [comment]
Eh, yes, temporary brain fart.

**Review by michicc — APPROVED** [review]

**Pull request merged**
