### PR TITLE
Fix #6631: In singleplayer, you cannot buyout one human-player company as another

### LINKED ISSUE #6631: In singleplayer, you cannot buyout one human-player company as another.
**_james1101_ opened the ticket and wrote:**

> To Reproduce:
> 1. Launch OpenTTD. Start multiplayer game.
> 2. Create 2 companies of the 'Human Player' type.
> 3. Save the game in multiplayer.
> 4. Load the game in singleplayer.
> 5. Make sure...
>   \- that Company # 1 has enough money to buyout Company # 2 (use money cheat if needed),
>   \- both companies are at least 6 years old (use date cheat if needed), and
>   \- the setting "Allow buying shares" under "Competitors" is set to true.
> 6. BUG: In singleplayer, Attempt to buyout Company # 2 as Company # 1. This will fail at 75% progress, with no error message and a greyed out "Buy Share" button. (see attached image)
> Suggested Fix: When loading a multiplayer save in singleplayer (defined as a save with multiple human-player companies), convert all of the human player companies (except Company # 1) to dummy AI companies. AI companies can be completely bought, while human-player companies cannot be completely bought.
> 

**Attachments**
- [ottd_can't_buyout_company.png](https://bugs.openttd.org/task/6631/getfile/10866/ottd_can%27t_buyout_company.png) (48.46 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

### PR DESCRIPTION
**Pull request by alex6m59**
When a multiplayer saved game is loaded (in single player mode), you cannot buy other human companies. As a result, these companies are "ghosts" in the game.
This patch converts human players to AIs, except the current company.
The company name is automatically changed but all equipments are same.

### CODE REVIEW

**Comment by andythenorth** [comment]
Fix is for #6631 (in title, but easier to click the link now)

**Comment by glx22** [comment]
I don't really like merges in PR.

**Comment by TrueBrain** [comment]
@glx22 : this is no problem, as during merging we can squash commits into a single commit, removing all the merge commits.
And @glx22 , please keep your responses actionable and constructive. Stating a random opinion is both confusing to the author and not contributing to the PR. If you want the author to remove the merge requests, explain that you like him to do it, and how to do so (don't assume everyone knows how to do this). Be verbose :) Tnx!

**Comment by alex6m59** [comment]
I admit that i'm newbie in the use of Git. I'm used to svn.
Thanks for your advices.
Do you mean that i could have done something like this ?
`git rebase -i HEAD~~`
And specify the squash command ?

**Comment by TrueBrain** [comment]
Squashing can be done when we merge your PR. This requires no action from your part (just the OpenTTD developer merging your PR will have to take that into account).

In Git-world, you have two main ways of updating your PR to the latest upstream. This can be done via merges (like you seem to have done, and is the most common way to do so), or via rebasing. The downside of merging is that you get all those merge commits, which doesn't really add value to a PR. With rebasing on the other hand, you would break anyone working based on your work. With PRs this is unlikely, and so often people suggest to rebase instead of merge for PRs.

Rebasing is as easy as: `git rebase upstream/master`, assuming https://github.com/OpenTTD/OpenTTD is your upstream remote. You do have to force push your branch afterwards.

A very well written document (with pretty images) on the subject can be found here: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

If you like, you can experiment a bit with it. If done correctly, `git rebase -i upstream/master` should show only a single commit, which contains your changes.

**Comment by James103** [comment]
How about you make a new setting for which AIs should take over existing human player companies, whatever it be 'None' (companies remain human player companies), 'Random AI' (loads a random AI), or any of the AIs that the player has installed?

**Comment by TrueBrain** [comment]
Sorry for the lack of response; I would like to blame summertime, but I am not sure that is to blame :)

We talked this solution over a bit, and we see a few issues. Mostly, an AI is unlikely to use the human-build infrastructure. So we thought up a fix that might be better for #6631: add two comments `attachai` and `detachai` to the console, so people can opt-in for this behaviour when they like.

So I want to thank you for your Pull Request; code-wise it looks spot-on. But the solution most likely isn't what you would hope it is :D

If you feel up for the task, we would love to have a PR to add the two above mentioned commands. That would be perfect!

Thank you!

**Pull request closed without merging**
