### PR TITLE
Fix #7043, Fix #7274: Delete town owned bridge based on adjacent tile ownership, not nearest town.

### LINKED ISSUE #7043: Disconnected towns during world generation
[14:59] Samu> bt, I found a bug regarding town bridges, during world generation the code deletes towns that are generated with 0 population, but by doing so, nearby bridges are also removed
[14:59] Samu> btw*
[14:59] Eddi|zuHause> then maybe the code that assigns bridge ownership is wrong?
[15:00] Samu> those bridges didn't belong to the town being deleted
[15:00] Gabda> it is a world generated bridge
[15:00] Samu> it results in disconnected towns

https://imgur.com/a/hqCAgsO

dbbzcfq
i7epssm

### LINKED ISSUE #7274: Very long stalls during town generation
## Version of OpenTTD
1.9.0-beta2
## Expected result
Don't take/stall too long
## Actual result
Very long stalls during town generation
## Steps to reproduce
Launch OpenTTD
Click Settings, set these settings:
- Landscape: Temperate landscape
- Land generator: Original
- Proportion of towns that will become cities: 1 in 1
- Initial city size multiplier: 10
Close window
Click New Game, set these values:
- Map size: 4096 * 4096
- No. of towns: High
- Sea level: Medium
Click Generate

Notice the number of stalls occuring during Town generation, usually past 3500. The frequency keeps increasing and increasing...

### PR DESCRIPTION
**Pull request by PeterN**
The existing test performed badly with a large number of towns due to having to calculate the
nearest town, and also by its nature assumed a bridge was built by the nearest town, leading
to bridges of nearby large towns be removed incorrectly.

Two birds with one stone...

This is an alternative solution to #7282.

### CODE REVIEW

**Comment by PeterN** [comment]
Due to no longer using CalcClosestTownFromTile(), worldgen performance on large maps is increased substantially. A quick worldgen test with `time bin/openttd -v null g -G 1138` came back with:

* master:  `5m9.612s`
* this pr: `1m23.780s`

Worldgen settings: 4096x4096, TGP, High, Mountainous, None, High, Improved, Manual, 31, Jan 1950, Funding only, Very Rough, Many, Freeform.

**Comment by nielsmh** [comment]
I think I would still prefer a solution that stores the owning town in the map array, also to avoid the double map array traversal.

**Comment by PeterN** [comment]
PR #7282 now does exactly that. I was going for the agreed semi-KISS approach, however.

The ultimate KISS approach is of course to not build bridges with zero-pop, which is what #7282 originally did. That method avoids the double map scan too.

**Comment by TrueBrain** [comment]
I think this is a very nice stepping stone towards an even better solution (like #7282). For now I suggest we reschedule this to 1.10, as that allows us to accept this PR as first step to improve performance, and work on another before 1.10 is released.

**Comment by PeterN** [comment]
Note that town bridges are only deleted by a town on map generation when a town fails to build. This is normally quite rare but some settings can cause it to happen enough that it's noticeably slow. During the game, towns will never delete their own bridges, and even if they did it would not be an intensive loop, just a one-off.

**Review by nielsmh — APPROVED** [review]

**Pull request merged**
