### PR TITLE
Fix: Display tooltips on industry chains window even when "Show toolt…

### PR DESCRIPTION
**Pull request by stormcone**
…ips" is set to right click.

The changes are based on how the "Cargo Flow Legend" window (linkgraph_gui.cpp) works.

### CODE REVIEW

**Comment by michicc** [comment]
That's surely a `Fix:`, isn't it?

Please update the commit message (amend/rebase) and force-push to update the PR.

**Comment by PeterN** [comment]
This does not look like the right fix for the problem, which affects multiple instances.

**Comment by stormcone** [comment]
@michicc: It's maybe a matter of perspective. From the users' point of view it is. From the code's point of view actually there is no bug, because this functionality is just not there, so it's an "add. :) Anyway I modified it, however @PeterN's PR looks more suitable.

**Comment by michicc** [comment]
Indeed, the other PR is the better way.

Still, just for completeness: The commit message is for example the basis for the user-visible changelog. As such, especially the prefix should be from the user POV and not the implementation POV.

**Pull request closed without merging**
