### PR TITLE
Backport master into release/13

### PR DESCRIPTION
**Pull request by glx22**
## Description
Backport of all closed Pull Requests labeled as 'backport requested' into `release/13`.
- https://github.com/OpenTTD/OpenTTD/pull/10622
- https://github.com/OpenTTD/OpenTTD/pull/10639
- https://github.com/OpenTTD/OpenTTD/pull/10643
- https://github.com/OpenTTD/OpenTTD/pull/10640
- https://github.com/OpenTTD/OpenTTD/pull/10657
- https://github.com/OpenTTD/OpenTTD/pull/10673
- https://github.com/OpenTTD/OpenTTD/pull/10686
- https://github.com/OpenTTD/OpenTTD/pull/10690
- https://github.com/OpenTTD/OpenTTD/pull/10736
- https://github.com/OpenTTD/OpenTTD/pull/10695
- https://github.com/OpenTTD/OpenTTD/pull/10730
- https://github.com/OpenTTD/OpenTTD/pull/10752
- https://github.com/OpenTTD/OpenTTD/pull/10758
- https://github.com/OpenTTD/OpenTTD/pull/10751
- https://github.com/OpenTTD/OpenTTD/pull/10775
- https://github.com/OpenTTD/OpenTTD/pull/10803
- https://github.com/OpenTTD/OpenTTD/pull/10848
- https://github.com/OpenTTD/OpenTTD/pull/10873
- https://github.com/OpenTTD/OpenTTD/pull/10878
- https://github.com/OpenTTD/OpenTTD/pull/10883
- https://github.com/OpenTTD/OpenTTD/pull/10894
- https://github.com/OpenTTD/OpenTTD/pull/10912
- https://github.com/OpenTTD/OpenTTD/pull/10916
- All language changes

### CODE REVIEW

**Comment by LordAro** [comment]
I'd imagine we've been fairly lax in applying the label, did you review other merged MRs?

**Comment by glx22** [comment]
I didn't check other PRs. And it mostly was for me to test the scripts (and I found an issue).

**Comment by glx22** [comment]
Hmm I failed to merge #10766.

**Comment by TrueBrain** [comment]
There are two more PRs incoming to fix up some more Wayland issues; we could either add them to this set, of make a new one after merging this. I am fine with both :)

**Review by TrueBrain — APPROVED** [review]

**Comment by glx22** [comment]
Probably also needs #10879 since #10878 is included.
Oh #10747 (and follow-ups) would be nice too I guess.
But this batch of backports is already big enough, with some manual fixing required during cherry-picking and adding stuff now would mean redo all the manual fixing.

So I'd prefer merging this one, then we can do another batch.

**Pull request merged**
