### PR TITLE
Fix: Total reset of DMusic driver once every hour

### PR DESCRIPTION
**Pull request by nielsmh**
Supposedly there are issues with the MS softsynth if it plays continuously for a long time, attempt to work around this by resetting it.

See [this comment by @James103](https://github.com/OpenTTD/OpenTTD/issues/7438#issuecomment-508498478) describing the problem.

### CODE REVIEW

**Comment by James103** [comment]
Are you gonna provide a way to manually reset the DMusic driver if, for example, the automatic reset didn't work or for debugging?

**Comment by nielsmh** [comment]
I can make the reset interval configurable, and make a console command to force a reset on next song change.

**Comment by LordAro** [comment]
I don't like this solution, it's far too much of a hack to fix something that isn't properly understood. It could even be a dmusic bug, rather than anything in OTTD

Giving the ability to manually reset it might be an option, or perhaps just reset it in the general case when switching music sets?

**Comment by Eddi-z** [comment]
if we're seriously discussing hacks to work around problems elsewhere, maybe we could even send a reset after every song, which could work around #7637?

maybe guard that with an advanced/hidden setting?

**Comment by nielsmh** [comment]
@LordAro I agree this is hacky, but based on the problem description I can't think of a better fix. The only things that stay around between songs in the DMusic driver in OTTD are the DirectMusic objects and some integer timekeeping. The song data itself is re-read into a fresh structure every time a song is started, there isn't any way for them to suddenly partially lose data that couldn't just as well occur from the beginning.

Resetting after N song changes, or after a music set change, likely do not make sense. As far as the DirectMusic library is concerned there isn't any distinction between songs, it's just a stream of note data. The music driver also doesn't care about switching music sets, it just gets instructed to play a file with no knowledge of how that file was chosen. And if the user switches songs multiple times quickly it doesn't seem to cause the issue, so it has to be based on time.
Providing a manual reset command might be enough, but it'd still require keeping most of these changes :)

@Eddi-z The problem discussed in #7637 is specific to the extmidi driver on Linux, when used with `aplaymidi` (rather than the default of `timidity`) to send the MIDI to a hardware synth, it doesn't relate to the DMusic driver at all.

@James103 Have you been able to test whether my previous music fixes (proper GM reset before each song) have improved the situation?

**Comment by James103** [comment]
@nielsmh
Due to OpenTTD/website#91 and since I don't have a compiler, I can't test any of your midi fixes nor can I test the multi-tile dock feature merged in #7380.

**Comment by TrueBrain** [comment]
@James103 that sounds really odd, given https://github.com/OpenTTD/website/issues/91 is a closed ticket. Are you sure this is blocking you?

**Comment by James103** [comment]
@nielsmh Fixed! First time I loaded website, cache gave me "20190606" (6th June 2019) for the nightly. Reloading the website (clear cache) reset the latest nightly version to "20190704" (4th July 2019).

**Comment by nielsmh** [comment]
@James103 You mean #7620 does fix the "broken notes" issue after a long time of music, without needing the total teardown in this PR?

**Comment by James103** [comment]
No, I meant that the OpenTTD website now gives the correct nightly version. The fix still needs testing.

**Comment by nielsmh** [comment]
I'm attempting to test whether this is still required now by leaving 1.9.3 playing music through the DMusic driver overnight, if it's still working fine in the morning I'll close this as not needed.

**Comment by nielsmh** [comment]
After having 1.9.3 play through the DMusic driver with MS softsynth for 10 hours, there are no problems with music rendition. This patch is not necessary.

**Pull request closed without merging**
