### PR TITLE
Codechange: [C++11] Use override specifer for overriding member declarations

### PR DESCRIPTION
**Pull request by M3Henry**
This is a C++11 feature that allows the compiler to check that a virtual
member declaration overrides a base-class member with the same signature.

Also src/blitter/32bpp_anim_sse4.hpp +38 is no longer erroneously marked
as virtual despite being a template.

### CODE REVIEW

**Comment by PeterN** [comment]
Well done. I had started to do this myself but didn't get any near completing it.

I am not sure if the remaining `/* virtual */` comments should stay or go.

The only issue I see is the Mac OS build warns on compiling objc files which include other headers:
`warning: 'override' keyword is a C++11 extension [-Wc++11-extensions]`

**Comment by PeterN** [comment]
Many Window-derived classes incorrectly use `virtual` instead of `/* virtual */`. We should fix these up in separate commit(s). I believe this can be scripted easily, so I am working on this now.

I've pushed to my repo with a PR here: https://github.com/M3Henry/openttd/pull/1

**Comment by M3Henry** [comment]
I'd say they should go.

I do remember GCC sometimes backports features and then warns that the feature is not compiler agnostic. Perhaps something similar?

**Comment by michicc** [comment]
There's a bunch of new useless warnings in the CI output for OSX. You could try adding the following to config.lib around line 1324:
`		# warning: <something> is a C++11 extension`
`		flags="$flags -Wno-c++11-extensions"`

We do want to use C++11, after all.

**Comment by michicc** [comment]
Sorry @M3Henry, I should have said line 1323, i.e. just before the `if` block. Right now it's skipped for all CI clang versions.

**Review by michicc — APPROVED** [review]
Works for me. And if there's missing `override` somewhere, well, no harm in adding it later.

**Pull request merged**
