### PR TITLE
Fix 23960d0f2c: Company livery window shows incorrect groups when opened from group window in multiplayer.

### PR DESCRIPTION
**Pull request by PeterN**

### CODE REVIEW

**Comment by nielsmh** [comment]
I'm not sure I understand how to reproduce this bug.

**Comment by PeterN** [comment]
As a client on a server, and not company 0, create a vehicle group and click on the group livery button within that window. The licery window will open with the wrong groups.

**Comment by nielsmh** [comment]
Here's what I do:
1) Start a multiplayer game, join with an extra client.
2) As company 1, build a road vehicle and put it in a named group.
3) As company 2, build a road vehicle and put it in a differently named group.
4) As company 2, open own road vehicles list, select the group, click the Group Livery button below groups list.

What happens: Company 2 livery window opens showing company 2 group names.

What I understand you describing happens: Company 1 group names are shown in company 2 livery window.

**Comment by PeterN** [comment]
Might not always occur then. I think andy reported it and i coukd reproduce.

**Review by TrueBrain — APPROVED** [review]
Can reproduce it with the steps above, and with this PR applied I can no longer. Doesn't mean a lot, but at least it does something :D

**Pull request merged**
