### PR TITLE
Fix b4b98e5165: Use FALLTHROUGH attribute with correct indentation.

### PR DESCRIPTION
**Pull request by J0anJosep**
Use the same indentation for FALLTHROUGH attribute and add it to script_stationlist.

### CODE REVIEW

**Review by LordAro — COMMENTED** [review]
I seem to recall that it was necessary for me to put the FALLTHROUGH attribute as the very last statement in the case, even if that was outside the {}. Are you sure this doesn't cause issues?

**Comment by J0anJosep** [comment]
@LordAro  I don't know. In my computer it doesn't cause issues.
I will look at the output of the checks later.
Anyway, there are two cases for {} here:
```
switch () {
	case A: {
		FALLTHROUGH;
	}

	case B: 
		if () {
		
		}
		FALLTHROUGH;

	default: break;
}
```
In the first case you can add the FALLTHROUGH attribute inside the {} and in the second you must add it outside.
Anyway, I will wait for more official developers' opinions and logs to see whether it causes problems.

**Comment by frosch123** [comment]
According to example 55 in
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0068r0.pdf
FALLTHROUGH inside } is valid. (see also 7.6.8)

Whether compilers actually understand this, is a different issue.

**Comment by TrueBrain** [comment]
Just as a word of warning: the CI currently has no compiler that uses `FALLTHROUGH` (it is only enabled for GCC >= 7 and MSVC2017+; all others have it defined to nothing). So this patch needs manually validation for both compilers before merging!

**Review by LordAro — APPROVED** [review]
Confirmed no new warnings with gcc7.3

**Pull request merged**
