### PR TITLE
Possible fix for #7430: when train visits station, only reset time_since_pickup if has room to load

### PR DESCRIPTION
**Pull request by MingweiSamuel**
#7430

### CODE REVIEW

**Comment by LordAro** [comment]
For me, it makes sense to only reset time_since_pickup when cargo is actually loaded, not before. If a train with spare capacity for some cargo comes into a station, but for some reason doesn't pick any up, the cargo is still "old" and the pickup time shouldn't be reset. It's time since cargo pick up, not time since last (nonfull) train arrival

**Comment by nielsmh** [comment]
The time since load needs to be reset even when there is no cargo available to load on the station, since that value is used for station rating calculation. If a player that doesn't receive any cargo on their station due to low rating can't raise their rating by having vehicles attempt to load, they will never be able to compete.

I haven't looked at the code in detail, but the idea presented sounds reasonable.

**Comment by MingweiSamuel** [comment]
I've split the PR into two commits:
* The first one contains the functional changes; making `if (cap_left > 0) {` its own branch and only setting `ge->time_since_pickup = 0;` in there. Note the wrong indentation.
* And the second one just fixes the indentation (which produces a big diff)

Should be a little easier to review (edit: though it will fail the commit checker)

**Review by LordAro — DISMISSED** [review]
Seems fine to me (does need commits merging though)

**Comment by MingweiSamuel** [comment]
Alright, squashed, looks like github automatically dismissed the review on force push unfortunately. I'm not too familiar with gh's system.

Copy of old commit without indentation: https://github.com/MingweiSamuel/OpenTTD/commit/d0c1353ae4ecdd8bb3921935298d40df7068efe5

**Review by LordAro — APPROVED** [review]

**Pull request merged**
