### PR TITLE
Fix #11528: Don't auto-build past tunnelbridge ends

### LINKED ISSUE #11528: [Bug]: When building a path through an existing one, the path is also laid under bridges
### Version of OpenTTD

OpenTTD 20231121; Windows 10

### Expected result

The area under/after the bridge is not affected, the rails/roads are laid up to the first tile of the bridge

### Actual result

The first time everything works as it should, but if you re-lay tracks through an existing one, the tracks will be laid under the bridge.

https://github.com/OpenTTD/OpenTTD/assets/115672237/36f46c00-2192-4e32-a786-2587b92922fa

The bug also appears on roads, tunnels and diagonal tracks.

https://github.com/OpenTTD/OpenTTD/assets/115672237/2f4d04e6-d875-410a-8010-a57bcfa261ea

https://github.com/OpenTTD/OpenTTD/assets/115672237/f0987fd3-52ae-45bf-b5a3-40b953597fbd

### Steps to reproduce

1. Build a bridge and a path across it
2. Pass the new path through existing one again

### PR DESCRIPTION
**Pull request by LordAro**
## Motivation / Problem

#11528 - autodragging over existing rail/road would start under a bridge, which is not expected behaviour

## Description

Keep track of whether we're under a tunnel or bridge when dragging and toggle as appropriate.

## Limitations

Feels very "just increase complexity" and there's probably additional edge cases that aren't covered, or are created, by this change.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Is it possible to make it continue on the other side of a bridge if you drag over it?

**Comment by LordAro** [comment]
That's what it does :)

Causes a certain amount of weirdness if you drag over different/multiple bridges though...

**Comment by PeterN** [comment]
Hmm, I dragged over a bridge and it did not continue on the other side.

**Comment by Kuhnovic** [comment]
This is similar to my PR (draft) from quite a while ago: https://github.com/OpenTTD/OpenTTD/pull/9616 

One thing to keep in mind is that the "drag and hold ctrl to delete"-behavior will behave different from the "drag to build"-behavior. There are already differences, this will add more differences. Not bad or good per se, but something to consider.

**Comment by LordAro** [comment]
The differences as far as the code is concerned is just a toggle of whether the road/rail is built or deconstructed, so i'm not quite sure what the overall problem with the complexity is there.

Though I do agree that as a whole this function is starting to get a bit on the unreadable side

**Comment by LordAro** [comment]
On the other hand, your PR is much more "complete" in terms of what it achieves. What would you say still needs doing to it to bring it "up to spec" ?

**Comment by Kuhnovic** [comment]
@LordAro The main thing I struggled with was the visualisation of it. I messed around quite a bit to get the highlighting to look somewhat good, but it always felt like a giant hack. 

For sure it needs a rebase and a fresh look, the PR is quite old and there's a good change some of the construction logic has changed by now. Unfortunately I have quite limited time available for development ATM...

**Review by TrueBrain — APPROVED** [review]
Might not be perfect, but it is another step in the right direction.

And yeah, all the scoping, it is a bit annoying. I guess we could take a look at "why", as having the if-condition and if-increment not in the if is a bit weird. But, not for this PR!

**Pull request merged**
