### PR TITLE
Feature: Allow or disallow large aeroplanes to land on airports with short runways

### PR DESCRIPTION
**Pull request by SamuXarick**
For people who want to test this in-game, I suggest combining #7502 + #7503 + #7505, to better understand what's the intention being presented here. Experiment giving orders, sending to hangar and autoreplacing aircraft of different types on different airports.

### CODE REVIEW

**Comment by PeterN** [comment]
Apart from 151 lines of code, what does this actually add?

**Comment by SamuXarick** [comment]
Force players to use the right aircraft/airport types for once. Just look at 1.9 title savegame.

More options for setting up servers, via max station spread, forcing small airports, while also forcing small aircraft type on them.

Also, in case of using unknown NewGRFs, it can also help by always pointing to the correct aircraft models for airports.

**Comment by Eddi-z** [comment]
how does this need 150 lines instead of... 10?

**Comment by SamuXarick** [comment]
Because the setting could be switched while airplanes were heading to hangars. It is to ensure that the same hangar is reachable, or to pick another.

Code also needs to prevent aircraft orders on incompatible airports/hangars.

**Comment by SamuXarick** [comment]
Needs #7503 for a more user friendly autoreplace (but not really a must have)

~~actually, autoreplace needs more changes than just a gui change :(~~ On second thought, it doesn't.
What to do about autoreplace:
Looks like nothing has to be done. I can replace a small plane with a large plane. If the airports have long runways, it's fine, if they don't it's not fine, but autoreplace, itself... nothing changes.

**Comment by LordAro** [comment]
I don't think this is going to go anywhere, I'm afraid

In theory, I like the idea of not being able to route large planes to small airports, but existing behaviour must be preserved, and I can't imagine adding an extra setting will interact well with the existing plane crash setting, or indeed the cheat for not crashing planes (which to be fair, could be removed)

There's already a news item for when planes are routed incorrectly STR_NEWS_PLANE_USES_TOO_SHORT_RUNWAY, and given the increased chance of crashing, I figure it's probably fine the way it is

**Pull request closed without merging**
