### PR TITLE
Fix 2fd90960: Missing default vehicles and industry acceptance/production.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Some default definitions are used across multiple climate types and rely on climate-independent cargo slot even though they specified a climate-dependent cargo type.

This no longer works since #11719 since cargo types are now cargo labels, which don't exist in some climates.

image

## Description

Add MixedCargoType that indirectly allows multiple labels to be specified for these.

Default definitions for vehicles, industries, and  industrytiles now use either a CargoLabel or a MixedCargoType, which is resolved during finalisation.

This is not applied to town houses as they don't have any cargo overlap.

image

## Limitations

Still a chance of unintended behaviour with old pre-label NewGRFs.

(A revert would also fix this issue, and all the limitations with that are known...)

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
Does every `GetCargoIDByLabel` call need to first call `GetActiveCargoLabel` ? If so, maybe merge the two?

**Comment by PeterN** [comment]
> Does every `GetCargoIDByLabel` call need to first call `GetActiveCargoLabel` ? If so, maybe merge the two?

No, only those that access a `std::variant<>` cargo_label of default definitions during NewGRF finalisation need the extra call.

**Review by rubidium42 — DISMISSED** [review]

**Comment by PeterN** [comment]
This now caters for default industries that aren't cross-climate, but could potentially be substituted and set up that way by NewGRFs—this means it uses the three mixed cargo types even if the industry is only single-climate.

**Review by michicc — APPROVED** [review]

**Comment by PeterN** [comment]
Fixes #11995

**Pull request merged**
