### PR TITLE
Fix for 'Huge screenshot' warning being shown incorrectly

### LINKED ISSUE #8232: "Huge screenshot" warning incorrect for heightmap / minimap screenshots
## Version of OpenTTD
1.10.2

## Expected result
Unless the map is greater than 67,108,864 tiles total size (8,192 x 8,192), no "Huge screenshot" warning is generated when taking a heightmap or minimap screenshot.

## Actual result
Even on a 128x128 map, a "Huge screenshot" warning is still generated when trying to take a heightmap or minimap screenshot. In my case (1080p monitor, maximized windowed mode on Windows 10), the warning says that the screenshot will be 15360 x 8136 pixels when fully zoomed out, even though the actual dimensions of the resulting screenshot is only 128x128 and it only takes a few milliseconds to take the screenshot.

This seems to be caused by the following, which only takes into account the viewport size and not the actual map size and whether the screenshot is a minimap or heightmap screenshot:
https://github.com/OpenTTD/OpenTTD/blob/6dfe5c852eba98dd51d5ff7b65817113213e091f/src/screenshot_gui.cpp#L56-L58

## Steps to reproduce
For best results, do the following steps on a monitor resolution of 1080p or higher.
1. Generate a new map, The size of the map does not matter.
2. Zoom all the way out.
3. Open the screenshot menu.
4. Click "Minimap screenshot" or "Heightmap screenshot".
5. Look at the warning generated, notice the incorrect dimensions.
6. Click through the warning.
7. The output size matches the map size, and not the viewport size scaled by the zoom level.

### PR DESCRIPTION
**Pull request by abmyii**
Fixes #8232.

### CODE REVIEW

**Comment by James103** [comment]
Commit checker has failed. The commit message should be in the form "Fix #8232: ...".

**Comment by abmyii** [comment]
Updated - thanks.

**Review by nielsmh — APPROVED** [review]
Looks correct to me.

**Review by techgeeknz — COMMENTED** [review]
We actually have more than one implementation of the screenshot function, which I'm currently trying to solve. I'll cherry-pick your commit into https://github.com/OpenTTD/OpenTTD/pull/8224

**Comment by abmyii** [comment]
> We actually have more than one implementation of the screenshot function, which I'm currently trying to solve. I'll cherry-pick your commit into #8224

Cool. I assume this PR should be closed in favour of yours?

**Comment by techgeeknz** [comment]
> Cool. I assume this PR should be closed in favour of yours?

We'll let the maintainers decide that one. I'll rebase my branch on yours if the cards fall in your favour.

**Comment by LordAro** [comment]
Thanks both, I've merged @techgeeknz 's PR

**Pull request closed without merging**
