### PR TITLE
Fix #6742: Only possible to build station next to competitor by using CTRL+click

### LINKED ISSUE #6742: Only possible to build station next to competitor by using CTRL+click
Hello, 

I don't know if it's actually a bug or not, but I discovered that it is possible to build a rail station directly next to other player airport (see attached screenshot) using ctrl+click (building a station with possibility of combining two stations into one).

It is **not possible** to build station directly by just clicking (without ctrl), because that way an popup pops up saying that: 
**Can't build railroad station here...
Adjoins more than one existing station/loading area**

So I think it should not be allowed even using ctrl+click. If I am wrong, just close/delete this issue. :)

adjoined_heli_and_train

Version 1.8.0, playing on Rpi 1/b+, custom build (without any changes to the source code).

### PR DESCRIPTION
**Pull request by Hopman**
Building stations next to an existing station of a competitor only worked by using CTRL+click. 
#6742 
This PR implements the suggested changes:
- keep the possibility to build stations there
- remove the need for CTRL+click

### CODE REVIEW

**Comment by Hopman** [comment]
@SylvainDevidal you are correct.

The string "STR_ERROR_TOO_CLOSE_TO_ANOTHER_STATION" only appears in this one location, the language files and in scripts. 

If desirable, I can extend the PR with another commit that removes the string completely.

**Comment by TrueBrain** [comment]
Sorry for the slow reply: that would be very much appreciated. Please remove it from all language files! Thank you :)

**Comment by Hopman** [comment]
Updated the PR.

**Comment by frosch123** [comment]
I tried this, it now allows building a station next to a competitor station without CTRL.

However, if there are two competitor stations nearby, it still says "adjoins more than one existing station".
Is it also possible to improve this second case?

**Comment by Hopman** [comment]
> Is it also possible to improve this second case?

Looking into it.

**Comment by frosch123** [comment]
Current PR is #6906.

**Pull request closed without merging**
