### PR TITLE
Doc: README.md: add Apache 2.0 licensing info for CheckAtomic.cmake

### PR DESCRIPTION
**Pull request by jayaddison**
## Motivation / Problem
I'm hoping to play OpenTTD on Debian `trixie`, but it's not yet available due to a build failure on 32-bit ARM; something to do with unavailability of 64-bit atomic functions (which may not be required for OpenTTD).  However: while looking into a fix, I figured it could be worth adding a license reference for the relevant CMake buildfile.

## Description
Adds the Apache-2.0-with-LLVM-exceptions license from LLVM v14 (still the one they use with v18 today) to the `src/3rdparty` dir and README file.

## Limitations
I'm not a lawyer, and I'm not completely certain whether the exceptions-clauses for LLVM's license would mean that it can be omitted here (I've read them for the first time a few hours ago).  On balance I think it's probably safest to document and include the license, since I don't see a significant downside to that.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by rubidium42** [comment]
To make the origins and link to the license more obvious, I have introduced a 3rdparty in the CMake folder and moved CheckAtomic and its license into a llvm folder in there. Furthermore I added a comment at the top of CheckAtomic.cmake detailing it's different license.

I guess these changes should be squashed and backported.

**Review by PeterN — APPROVED** [review]
Assuming this is still needed after the C++20 move.

**Comment by jayaddison** [comment]
Thanks @PeterN @rubidium42!

**Comment by jayaddison** [comment]
Slightly off-topic, but: OpenTTD is available in Debian `trixie` again, and I'm really enjoying playing it :)  Thank you for developing and maintaining it (and for handling the update/fixup here).

**Pull request merged**
