### PR TITLE
Codechange: Sort and filter sign names directly rather than through string system.

### PR DESCRIPTION
**Pull request by PeterN**

### CODE REVIEW

**Comment by PeterN** [comment]
Probably need to handle if Sign::name is null.

**Comment by SamuXarick** [comment]
Faster, but still…
unnamed 1956-09-16

**Comment by PeterN** [comment]
This is now a fairly major improvement when a lot of signs are placed, and signs are added/remove regularly. This is not a normal situation but is achievable with debug options on some AIs (AIAI in this case).

sign-sorter

* master: ~240ms/t, game runs at 0.1x speed
* this PR: ~10ms/t, game runs at faster than real-time.

**Comment by nielsmh** [comment]
This makes me wonder how much performance gain could be had by (somehow) optimising the entire FormatString flow.

**Comment by PeterN** [comment]
Using FormatString once will still needlessly (for the purposes of sorting/filtering) duplicate each string, but it may help.

**Review by LordAro — APPROVED** [review]
Code looks fine, but 6 commits looks like a lot, perhaps some of them should be merged together?

**Comment by PeterN** [comment]
Closes #7303

**Pull request merged**
