### PR TITLE
Fix #7667: Buying an engine after buying wagons doesn't give a comple…

### LINKED ISSUE #7667: Buying an engine after buying wagons doesn't give a complete train.
## Version of OpenTTD
master, revision 5981ed248

## Expected result
I get a complete train by buying a few wagons, and then an engine.

## Actual result
The engine is placed on a line by itself in the depot.

## Steps to reproduce
1. Start game with default base set at a sane year (I used 1930, but likely it doesn't matter)
2. Place a depot for trains
3. Open the buy menu, and buy 2 passenger wagons (or something else probably, didn't test)
4. Buy an engine
5. Get 2 lines in the depot:
Screenshot_20190723_203412

Bisected this behavior back to d54b6ac09b6fe88c09f7886739fe9c05f16b8222 as the first bad revision.

Many thanks to andythenorth for finding it was an OpenTTD bug.

### PR DESCRIPTION
**Pull request by stormcone**
…te train.

This commit sets the 'data' argument to it's original value as it was before d54b6ac.

### CODE REVIEW

**Comment by michicc** [comment]
I really don't think this is right. Changing it to `GB(p1, 16, 8)` OTOH would make it match the comment for `p1`.

**Comment by stormcone** [comment]
I'm not sure which comment you mean. In `CmdBuildVehicle`:
https://github.com/OpenTTD/OpenTTD/blob/2817cd41f1b42a7d3901a92c6cda85a90765600a/src/vehicle_cmd.cpp#L81-L84
it says bits 0..15.

In CmdBuild&lt;VehicleType&gt; functions 'data' is 'unused', except the case of trains, where it says:
https://github.com/OpenTTD/OpenTTD/blob/2817cd41f1b42a7d3901a92c6cda85a90765600a/src/train_cmd.cpp#L715
So actually we only need `CmdBuildVehicle`'s `p1`'s bit 0.

OTOH, originally it was GB(p1, 16, 16), so that's why I chose this again.

**Comment by michicc** [comment]
I mean this one:
https://github.com/OpenTTD/OpenTTD/blob/2817cd41f1b42a7d3901a92c6cda85a90765600a/src/vehicle_cmd.cpp#L83-L83

In my understanding the 'vehicle type specific bits' are exactly what should be passed to `CmdBuild<VehicleType>`. And incidentally, the commit you've quoted changed that data from bits 16-31 to only bits 16-23. I.e. start bit 16, length 8 -> `GB(p1, 16, 8)`.

**Comment by stormcone** [comment]
Now I see, you are right. I updated the commit.

**Review by michicc — APPROVED** [review]

**Comment by andythenorth** [comment]
Thanks!

**Pull request merged**
