### PR TITLE
Add GH Actions CI workflow

### PR DESCRIPTION
**Pull request by LordAro**
Largely copied one-for-one from the azure pipeline jobs. Except the windows job, which @glx22 did.

Doesn't check x86 on Linux. Should it? idk.

Removes the need for the ci-* docker images in OpenTTD/CompileFarm

### CODE REVIEW

**Comment by LordAro** [comment]
Of course, the existing Azure CI is sad because it's been removed..

**Review by glx22 — APPROVED** [review]
Seems to work as expected.
Problem matchers could be a nice addition, but no hurry.

**Comment by LordAro** [comment]
Problem matchers?

**Comment by glx22** [comment]
https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md

**Comment by TrueBrain** [comment]
Tips and tricks to get started on problem matchers (but, really, for another PR):

Example of how to enable them:
https://github.com/TrueBrain/actions-flake8/blob/master/entrypoint.sh#L6

Example of a GCC Problem Matcher:
https://github.com/microsoft/vscode-cpptools/blob/master/Extension/package.json#L98

Or implemented in a GitHub Action:
https://github.com/ammaraskar/gcc-problem-matcher

**Comment by glx22** [comment]
I also found https://github.com/ammaraskar/msvc-problem-matcher but as already said, it can wait for another PR.

**Pull request merged**
