### PR TITLE
Codechange: use standard int types

### PR DESCRIPTION
**Pull request by rubidium42**
## Motivation / Problem

Using custom typedef for types that are standard types.
Mostly `(u)intXX` that can become `(u)intXX_t`, but also `WChar` becoming `char32_t`.

## Description

Automatic replacements; script in commit message.
Manual removal of the `typedef`s from stdafx.h.

## Limitations

Breaks quite some patches.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by TrueBrain** [comment]
I think this would help for new developers to join in, as this makes this project more like other C++ projects. Similar to the efforts of converting to `std::string` etc; it just makes things easier for new joiners.

But, it is a total patch-killer, and as such, I think it is good to involve patchpacks; either by supplying seds or something, so they can go through a similar conversion.

**Comment by rubidium42** [comment]
> I think this would help for new developers to join in, as this makes this project more like other C++ projects. Similar to the efforts of converting to `std::string` etc; it just makes things easier for new joiners.
> 
> But, it is a total patch-killer, and as such, I think it is good to involve patchpacks; either by supplying seds or something, so they can go through a similar conversion.

The probably should wait to just before branching 14, or at least just before the first beta. Regarding the sed, that's in the second paragraph of the automatic change commit of this PR.
And yes, the commits need to get a better description before this gets merged. But alas, it's more proof-of-work and something to get the discussion going than it already being polished to get to be merged.

**Comment by TrueBrain** [comment]
> The probably should wait to just before branching 14, or at least just before the first beta. Regarding the sed, that's in the second paragraph of the automatic change commit of this PR. And yes, the commits need to get a better description before this gets merged. But alas, it's more proof-of-work and something to get the discussion going than it already being polished to get to be merged.

Well, what I more meant is: we should actual talk to patchpack owners; that kind of "involving". If for them this means it is a HUGE hassle to keep up-to-date with upstream, we shouldn't do this.

**Comment by PeterN** [comment]
I would like to see this if possible -- I had done global search & replaces to see what it looks like :-)

However we can at least start to use the correct types piecemeal for future changes?

**Review by TrueBrain — APPROVED** [review]
Everyone I talked to signed off on this, as in:

@JGRennison  indicated it doesn't bother him, and he will deal with it.
@PeterN, myself and OP would like to see this change.
Nobody else spoke up against it.

In general I think this is a good improvement, as everyone these days assume `uint32_t`. And as these days it works on all OSes, why not convert the rest to it so we can no longer use `uint32` at all. This also makes things just slightly easier for new contributors, as it complies with modern expectations of a codebase.

And anyone else that runs a patchpack, there is enough information in this PR to do this on your own code too, saving you a lot of trouble. But can't deny, this will hurt a bit.

But so yeah, let's do this!

(you most likely have to check if this needs a rebase; just wanted to give the approval to make a point :D )

**Pull request merged**
