### PR TITLE
Doc: AAT_STATION_AIRPLANE_LAND triggers only a single tile, not all airport tiles. #7181

### PR DESCRIPTION
**Pull request by PeterN**

### CODE REVIEW

**Review by planetmaker — APPROVED** [review]
Indeed. By design. Maybe "for the touchdown tile" would be even better description

**Comment by michicc** [comment]
Shouldn't the commit message be `Doc #7181: ...`, or is the checker unhappy with that?

**Comment by PeterN** [comment]
It's happy with the old style, I suppose I could amend the commit later.

**Comment by michicc** [comment]
Squash and change message?

**Pull request merged**
