### PR TITLE
Fix 11ab3c4ea2f: Vehicles could not be refitted to cargo IDs higher than 32.

### PR DESCRIPTION
**Pull request by PeterN**
This shuffles the bit packing around to give more space to cargo ID.

### CODE REVIEW

**Comment by andythenorth** [comment]
PR fixes the vehicle refit bug found here: https://www.tt-forums.net/viewtopic.php?p=1217911#p1217911 

I looked at the patch and it looks sane to me, but I didn't check if all the changes to bit counts are correct.

**Comment by PeterN** [comment]
@andythenorth Technically 8 bits is too many, however by specifying that many bits we will get an error message if CargoID is out of range, rather than it being silently wrapped at 32 (or 64)

Additionally the scripting interface only provides for CargoID and subtype parameters, so is not affected by the shuffling.

**Comment by PeterN** [comment]
In the bit packing, the following changes are made:

* Bit 5 is moved to bit 24
* Bit 6 is moved to bit 25
* CargoID increased from bits 0-4 to 0-7

**Review by planetmaker — APPROVED** [review]
yep, let's fix this bug :)

**Comment by PeterN** [comment]
This is incomplete for autorefitting, however in trying to follow the flow for autorefit it seems it was buggy before. Trying to work out what values are valid :-)

CT_AUTO_REFIT = 0xFD, which would have been truncated to cargo type 0x1D with the original bit packing, which may or may not be valid depending on NewGRFs in use.

**Pull request merged**
