### PR TITLE
Fix: keep NewGRF order for object class sorting

### PR DESCRIPTION
**Pull request by perezdidac**
## Motivation / Problem

A filter for objects was added in https://github.com/OpenTTD/OpenTTD/pull/8603, but the change also made the object class list to be sorted alphabetical. This adds some value but breaks others as stated in https://github.com/OpenTTD/OpenTTD/issues/8817.

## Description

This change modifies the logic to sort the list of object classes to keep the order of the NewGRF list. See:

image

Note that since the code was based on using ObjectClass pointer rather than ObjectClassID, I am also reverting to use ObjectClassID back as before of https://github.com/OpenTTD/OpenTTD/pull/8603 as it's needed to sort.

I will apply the same sorting logic to https://github.com/OpenTTD/OpenTTD/pull/8706.

## Limitations

None.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by stormcone** [comment]
What do you think about a drop down menu where you can select the sort order? Similar to other places, like the build vehicle menu.

**Comment by perezdidac** [comment]
> What do you think about a drop down menu where you can select the sort order? Similar to other places, like the build vehicle menu.

Yes, I like the idea if I can do it without clogging the UI too much. This will require some more changes so better doing it in a separate PR so we can merge this fix into 1.11 first to not break current use cases. WDYT?

**Comment by stormcone** [comment]
It's fine for me. :)

**Review by LordAro — APPROVED** [review]
LGTM

**Pull request merged**
