### PR TITLE
Change: Log AI/GS Squirrel crashes in white text for readability

### PR DESCRIPTION
**Pull request by andythenorth**
## Motivation / Problem

* improve legibility of errors in AI / GS debug log

## Description

* white on grey is more legible than red on grey

## Limitations

* probably someone will disagree

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
No
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* No
* This PR affects the save game format? (label 'savegame upgrade')
* No
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
 Not really
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)
No

### CODE REVIEW

**Comment by SamuXarick** [comment]
I disagree 👎 . There's also yellow text for Warnings.

**Comment by LC-Zorg** [comment]
I think you're both right. The red error color is used not only here. I think it should stay red as something important. But yeah, a red wall of text isn't fun to read and pick up important points. So what do you think about the orange/gold color of the bug description with the red color of the main information preserved?

Something like this...
Debug recolor 2 1

versus this...
Debug recolor 0

**Comment by LC-Zorg** [comment]
In principle, the description could also be white. However, it seems to me that orange fits better in this place and is also quite readable.
Debug recolor 2 2

**Comment by andythenorth** [comment]
White is the most legible.  

I picked white because it's the most legible.

Everything is irrelevant. Unix shell doesn't go to red for errors unless you install some fancy text formatter for it.

**Comment by 2TallTyler** [comment]
With the disclaimer that I've only dabbled with AI/GS development and haven't really used the log much...

I support making this more legible, although I think yellow warning text and white error text isn't quite right. Maybe they can both be white? I also like the orange error text as it's suitably severe looking while being significantly more readable than red.

**Comment by andythenorth** [comment]
Amended PR, GSLog.Error now remains red, I don't use it so I don't care.  If the semantics of the colour are more important than legibility so be it.

Squirrel crashes are white. This is the change I wish to see made.  At this point the script is dead, the meaning of the colour is irrelevant.

image

**Review by 2TallTyler — APPROVED** [review]
Suggested squashed commit title: `Change: Log AI/GS Squirrel crashes in white text for readability`

**Pull request merged**
