### PR TITLE
Codechange: Use correct invalid cargo constants.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Both CT_INVALID and INVALID_CARGO have the value 0xFF but refer to different things. They have been mixed up in the past.

## Description

Rename INVALID_CARGO to INVALID_CARGO_BITNUM, and use CT_INVALID consistently, unless INVALID_CARGO_BITNUM is actually intended.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
Perhaps rename CT_INVALID to `CARGO_TYPE_INVALID` while you're at it?

**Comment by PeterN** [comment]
I considered renaming it but it does appear in the script API, so I'm not sure it's feasible (but maybe that's a separate enum)

Also it's used in a lot of tables which would no longer be (barely) aligned ;)

But that possibility is one of the reasons for using `IsValidCargoID()` everywhere. There are other changes to cargo types I have in the works as well which involve separating CargoID from CT_xxx, but small steps.

**Comment by PeterN** [comment]
Oh and as the warnings (that didn't show for me) say, there's also the CargoID / CargoType discrepancy. I guess I should fix that before this change :-)

**Review by 2TallTyler — APPROVED** [review]
I haven't verified that you've used the right type for each use, but I assume you (and the warnings you mention) have. 🙂

**Pull request merged**
