### PR TITLE
Add: AI/GS Reinstate custom settings profile.

### PR DESCRIPTION
**Pull request by SamuXarick**

### CODE REVIEW

**Comment by PeterN** [comment]
Why?

**Comment by TrueBrain** [comment]
Owh, @SamuXarick , we talked about this. No more Pull Requests without giving context WHY we would want this. @PeterN is being nice. I am not.

I don't see how this is useful; given there is no further reasoning, closing this topic. You are not allowed to bring up the same topic or discuss "why did you close this PR" for at least 6 months.

**Comment by SamuXarick** [comment]
Because it is a requirement when creating settings for an AI/GS. Why make it a requirement if then it's not accessible?

**Comment by PeterN** [comment]
"Custom" does not make sense in the context it is used. Instead it should probably be removed.

**Pull request closed without merging**
