### PR TITLE
Fix #7003: Freetype fonts were scaled by both GUI and Font zoom levels.

### PR DESCRIPTION
**Pull request by PeterN**

### CODE REVIEW

**Comment by nielsmh** [comment]
This breaks the font size setting with True Type fonts.

image

Only the bitmap symbols in station signs have been scaled, the TT font has not.

**Comment by PeterN** [comment]
That... works fine for me. What? EDIT Ah, I know why...

**Comment by PeterN** [comment]
So there is an issue now that throughout the windows they tend to be scaling by gui zoom level, but some times it should now been by font zoom level instead. Or possibly both in a single widget... Seems a wide scope :/

**Comment by nielsmh** [comment]
It should be enough to update the FONT_HEIGHT_NORMAL etc. macros, but maybe the result of those are scaled by the GUI size too? (I would think they shouldn't be.)

**Comment by PeterN** [comment]
I'm mistaken, these issues already existed, just it's easier to see now that it's very easy to use a massive font. These two commits solve the issue in the PR title.

**Review by LordAro — APPROVED** [review]

**Pull request merged**
