### PR TITLE
Update simplified_chinese.txt

### PR DESCRIPTION
**Pull request by bruceCzK**
Make 'go non-stop via' more accurate in chinese. It's a bit confusing before.

## Motivation / Problem

Just a small change to language file.

### CODE REVIEW

**Comment by James103** [comment]
Translations are handled exclusively via eints. Open an issue at https://github.com/OpenTTD/team/issues/new/choose to get started.

**Comment by frosch123** [comment]
@OpenTTD/zh_cn  Please review this change, and transfer it to the WebTranslator, if appropiate.

**Comment by clzls** [comment]
> @OpenTTD/zh_cn Please review this change, and transfer it to the WebTranslator, if appropiate.

@bruceCzK I reviewed this change and decided to change string STR_ORDER_GO_NON_STOP_VIA to "经由（不停车）"(non-stop via), not this one "通过不停车" (pass, non-stop), for a clearer image.

**Comment by bruceCzK** [comment]
OK. “经由” is better. But there’s also ’Go via’, if you use ‘经由’ for this one, I think the other one should be changed as well.

**Comment by clzls** [comment]
> OK. “经由” is better. But there’s also ’Go via’, if you use ‘经由’ for this one, I think the other one should be changed as well.

STR_ORDER_GO_VIA "Go via" has also been changed to '经由'.

**Comment by bruceCzK** [comment]
Thank you very much.

**Pull request closed without merging**
