### PR TITLE
Codechange: [Script] Improve copying a list into another empty list.

### PR DESCRIPTION
**Pull request by michicc**

### CODE REVIEW

**Comment by LordAro** [comment]
It's not clear how this makes any difference at all - if the list is empty, surely the iteration doesn't do anything?

**Comment by SamuXarick** [comment]
Sem Título

**Comment by glx22** [comment]
The iterations happens on the added list, not on the destination.

**Review by LordAro — APPROVED** [review]
Ah, that makes sense

**Pull request merged**
