### PR TITLE
Doc: Add guide to releasing OpenTTD

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

@michicc wrote a really nice guide to releasing OpenTTD in a series of Discord posts. Let's not lose it.

## Description

I adapted the guide to the best of my understanding. Please ensure it's correct and suggest anything I've missed or misworded. I'm inviting you to nit-pick. 😃 

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by frosch123** [comment]
Here is the previous version of the release guide: https://wiki.openttd.org/en/Development/Doing%20an%20OpenTTD%20release
The part on "After creating a branch for a new version" got lost in this PR.

I think there should only be one guide, delete the wiki page afterwards?

**Comment by 2TallTyler** [comment]
Some steps I'm unclear about, from the linked release guide (might need some input from @TrueBrain):
- `run "make regression"` — Is still still required? How is this done?
- `Poke package maintainers on IRC: blathijs (debian), heffer (fedora).` — Do we still do this now that we only offer the generic Linux build?

**Comment by rubidium42** [comment]
>     * `run "make regression"` — Is still still required? How is this done?

At least the CI runs it automatically, so if it builds it should be fine. Not sure how it's done in MSVC, but when using make it's still literally `make regression` instead of `make`.

>     * `Poke package maintainers on IRC: blathijs (debian), heffer (fedora).` — Do we still do this now that we only offer the generic Linux build?

This is about the upstream maintainers. They are the ones that update the package that is in the Debian/Fedora (derived) distributions. Practically it's not much more than 'blathijs, heffer: new release', although I don't think heffer is on our IRC channel. And I've not seen a poke recently, so I guess it could be left out. It used to be a courtesy thing in the past.

**Comment by glx22** [comment]
> > ```
> > * `run "make regression"` — Is still still required? How is this done?
> > ```
> 
> At least the CI runs it automatically, so if it builds it should be fine. Not sure how it's done in MSVC, but when using make it's still literally `make regression` instead of `make`.
> 
For MSVC it's under `Test` menu (when using "open directory" mode).
Anyway regression is a required CI check, only admins could force merge a PR with broken regression.

**Review by rubidium42 — APPROVED** [review]

**Pull request merged**
