### PR TITLE
Rail fences in snow or desert

### PR DESCRIPTION
**Pull request by pi1985**
This allow to draw rail fences in snow or desert tiles

### CODE REVIEW

**Comment by Eddi-z** [comment]
that diff looks way too large for such a simple feature, maybe split it up into more logical sections? makes it easier to review

**Comment by pi1985** [comment]
Hmm... this patch makes simple feature, there isn't logical parts. You may mean changes in newgrf_commons.cpp, water_cmd.cpp - corrects showing snow background.
Without other changes game crashes or can't compile.

**Comment by andythenorth** [comment]
This PR is against issue #6315

**Review by nielsmh — CHANGES_REQUESTED** [review]
Separate the change into at least two commits. First change the scheme for fences to your new storage format, without adding the snow/desert logic. Then a separate commit adding the snow/desert logic to this.

You also need to use the correct commit message format, otherwise the PR will be rejected by the automated checks. [See the wiki for this](https://wiki.openttd.org/Coding_style#Commit_message).

**Pull request closed without merging**
