### PR TITLE
Change: Recolour graph windows to brown

### LINKED ISSUE #8633: Graph window - Improving the aesthetics of the window
## Version of OpenTTD
20210114-master (applies to change #8557)
## Expected result
The window looks good and fits stylistically with the rest of GUI
zzg 07

zzg 06

## Actual result
The colors of the guide lines are too bright and irritate the eyesight.
The dark background creates a kind of internal screen that, unlike the other windows (vehicle window, extra viewport), has no frame.
zzg 00

## Solutions
1. Changing the colors of the guides to less contrasting - more about it in another issue (#8630)
2. Adding a frame for the dark area of the ghaph - it can be a single shadow that gives a shallow niche or a double shadow (recess) separating the graph area from the rest. The latter solution would also work for light backgrounds and the option to change the background.
## Note
It is not particularly important, it's only detail, but in my opinion it gives an interesting effect, consistent with the rest of the interface.

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

The dark graphs introduced in #8557 look great, but the windows don't match stylistically with other GUI elements. @ldpl suggested changing the window color to brown to match the map.

EDIT: I had attempted to recolour a bunch of other windows, but realized the scope creep made reviewing difficult, so I've reduced the scope to just recolouring graph and other information windows brown.

Closes #8633. 

## Description

brown_graph

The following graph windows are now brown:
- Operating profit graph
- Income graph
- Cargo delivery graph
- Company performance graph
- Company value graph
- Cargo payment rates graph

Also, several non-graph windows make sense to be brown too:
- Detailed performance rating
  - Note: I also made the company performance numbers orange, to match other brown windows
- Company league table
- Sign list

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by TrueBrain** [comment]
Screenshots or it didn't happen! :D

**Comment by frosch123** [comment]
Nice idea. Some notes:

1. Your list is missing the industry directory and fund-industry window :)
2. I think town GUI and local authority should have the same color. Giving the local authority the same color as the toolbars sounds weird to me. For me those two windows belong together like vehicle view and vehicle details.

<s>3. I would expect town directory to have the same colour as the town view. Though argueably that is not the case for the industry directory. Not sure whether industry and town directory would be readable with the cream colour.</s>

For reference, an earlier page about the same idea: https://wiki.openttd.org/en/Development/GUI%20Style%20Guide#window-colours

Edit:
4. Sign-rename window: Brown, grey, grey+1CC ?
5. The graph windows have plenty of colours in the curves themself. A neutral background works better.

So, I tend to agree with ldpl. The changes do not really improve the visibility. I guess they are inconsistent for a reason.

**Comment by ldpl** [comment]
This would've been much easier to discuss as several separate changes but here's my opinion:
- "Consistency" - mostly irrelevant. Just pick whatever looks nicer as that categorization is questionable anyway.
- Graphs, Sign list and league table - Brown is better.
- Detailed performance - was better in grey. and you didn't even recolor buttons.
- Towns - awful change, cream is ugly af, quite aggressive for a background in general and red and green text is nearly unreadable on it. IMO industries should be switched to brown as well.
- Local authority - no, god no. Leave dark green for toolbars if anything :p

UPD. I forgot I had night mode on, so changed my opinion a bit after disabling it xD

P.S. Story book also has 1cc brown.

**Comment by 2TallTyler** [comment]
Thank you both for the feedback. I have updated the original post.

I have reverted town and local authority windows to brown. Industries probably have to stay cream, since a lot of NewGRF industries insert custom text which we can't recolour orange to match town windows.

I've changed the buttons on the detailed performance window to brown, which required extending MakeCompanyButtonRows() to take a Colours parameter.

I also recoloured the buttons on the cargo payment graph from orange to brown. The closest parallel here I think is enabling/disabling industries in the small map, which of course are not buttons...but this inconsistency is out of scope here.

> Sign-rename window: Brown, grey, grey+1CC ?

All rename windows are system grey including for player-owned things like stations and vehicles. I don't see a need to change this.

**Comment by ldpl** [comment]
I still think detailed performance looked better in grey but brown is ok too now. And mb making numbers orange like in the town window will improve it even further.

Brown cargo buttons look nicer than orange.

> Industries probably have to stay cream, since a lot of NewGRF industries insert custom text which we can't recolour orange to match town windows.

Well, if there ever was a good time to do that it would be now. As 1.11 already messes with industry sets in cargo colours. And gamescripts now can add a custom industry text too so they'll also become a hindrance in the future.

**Comment by 2TallTyler** [comment]
~~I agree that this is a good opportunity to change the industry window colour, since we are already changing the graph background. I'll include this in the next push.~~ EDIT: Reverted this as it's out of scope.

> @ldpl: And mb making numbers orange like in the town window will improve it even further.

Thoughts?

orange_performance

**Comment by 2TallTyler** [comment]
~~Industries are now brown with black/orange text, and even NewGRFs which use yellow text don't look that bad. See the PR description for a screenshot.~~ EDIT: This has since been reverted, as it's out of scope.

I went with the orange numbers for the detailed performance rating.

**Comment by stormcone** [comment]
Personally I don't like these changes. I find it better when the different thing's windows have different color, because I can easier distinguish them without taking a closer look. Like when the industry window has other color than the town window.

**Comment by 2TallTyler** [comment]
EDIT: I could go either way on the industry window, and the primary scope of this PR is graphs and related info windows being brown. I have simplified the PR to only graph windows.

If someone has a strong preference on the industry window colour, they can open a new PR. It is out of scope for this one.

**Comment by LordAro** [comment]
You're still changing the signs list window to brown. Seems out of scope for this - given industry directory is brown & station list is grey

**Comment by 2TallTyler** [comment]
I'm not opposed to splitting up this PR for each window type, but this isn't an oversight in colour choice. The sign list is global like the industry window, not split per company like the station list.

**Comment by LC-Zorg** [comment]
Few comments:
1. Why do you want to make a change that can be done with NewGRF?
2. The issue of improving consistency is very debatable and up to the player. For example, graphs are part of finance for me - the finance window is gray, why should the graphs be brown? So does the sign list - the sign input window is gray.
3. The issue of improving the aesthetics is even more debatable. To me, the brown window doesn't look bad. I'd say it's even quite nice, especially with the lines tweaked. Thanks. But the Detailed performance rating window doesn't look good anymore. Orange text on a brown background is not more legible at all, it is quite the opposite. See that here, in a very small group, there are voices against this change. Among players, many of whom may have become attached to the classic look, this change may also be perceived negatively.
4. Haven't you thought about leaving the choice to the players?
Extensive options could be created, but even if you gave a simple option: New / Old, this change would be neutral at worst and positive for many. An interesting solution could be adding the GUI style / theme selection option. There is also an option that I mentioned in the topic of city names, where the player could choose passive NewGRF - among them there could be those that change the appearance of the GUI.

**Comment by 2TallTyler** [comment]
A few answers:

1. GUI window colours cannot be changed by NewGRFs.

2. In the colour scheme I determined from other windows, windows about global game information (map, town and industry directories, town windows, goals, etc) are brown while windows about specific companies (finance, station and vehicle windows, etc) are grey with a 1CC title background. Grey windows are for system windows like save/load, rename dialogs, etc. This colour scheme could be changed or reinterpreted, but this is my proposal for the core developers to consider. 

3. I think it's important that the detailed performance window match the performance graph. And orange text on a brown background is very common in OpenTTD - see the town window, for example. 

4. NewGRF GUI themes is extraordinarily out of scope for this PR. :)

**Comment by LC-Zorg** [comment]
> 1. GUI window colours cannot be changed by NewGRFs.

NewCC Set

Zrzut ekranu 2021-03-08 092152

There are add-ons that do this. Probably the problem is that the window colors and the company colors are linked. Perhaps NewGRF cannot currently change a specific element. The question is, is it a big problem to make both changes independent and to create appropriate opportunities?

3. Just because it's common doesn't mean it's more legible. If you want to change something, it should be for the better, not the worse. I agree that orange looks more interesting in terms of color, but it just worsens readability. A few separated numbers next to each other in a city window is not the same as a monolithic string in that window.

I checked what it would look like with black text and it seems... less colorful, but, in my opinion, more important, it is clearer.
Black letters

4. I am just writing that there are other ways to do the same that will not cause anyone a sense of loss. For me, this change would not be bad. But I kinda dislike the fact that you don't include in this PR of players who like and prefer the current look.

**Comment by 2TallTyler** [comment]
Ah, I was not aware of that NewGRF. I would note, though, that it simply changes the entire colour palette of the game; it is still not possible to recolour specific GUI elements via NewGRF.

I welcome other thoughts on orange vs. black text in the detailed performance rating window.

It is not feasible to allow users to opt-out of every single change, and I have not heard from anybody that they prefer the current look over this change. Please understand that I am not unilaterally making changes with no concern for other users. I am trying to contribute to making OpenTTD a better game for all, and my proposals are all subject to approval or rejection by the core developers. I welcome input from anyone and often incorporate constructive suggestions into my proposals (see my back-and-forth with ldpl here and in my other recent PRs), but opposing change just because you fear a hypothetical user might be upset is not helpful feedback. Nor is it our job to worry about that; let's leave that to the core developers. :)

**Comment by TrueBrain** [comment]
Right, we talked it over a bit. A few minor requests:

1) please keep the performance strings black. Orange doesn't fit the rest of the game, and looks a bit off/weird :) Also, so close to the release, changing strings is a bit troublesome. So I rather not, if we can :) (bit of a silly reason, I know)
2) please rebase, so we no longer see those pesky CI warnings :D

Otherwise, good to go!

**Review by TrueBrain — APPROVED** [review]

**Comment by LC-Zorg** [comment]
I think it would be worthwhile in the future to consider adding a color selection option for some windows - without going into details, just 2, 3 options like: Brown (default), Gray (classic). Changing the color could also be useful for purple windows, which are not very legible given the small GUI size. Anyway, this is a matter of a different PR. ;)

**Pull request merged**
