### PR TITLE
Fix #8153: Report autoreplace failure when new vehicle cannot carry the cargo

### LINKED ISSUE #8153: Autoreplace does not report failures due to refittability
## Version of OpenTTD
1.10.1
## Expected result
When I'm setting some vehicles to be replaced with some policy (either immediately or when they're old) I expect them to be replaced
## Actual result
Sometimes it happens that some vehicles get "stuck" indefinitely and never get replaced.

## Steps to reproduce
1. Load the save game attached: [bugboats.sav.zip](https://github.com/OpenTTD/OpenTTD/files/4639447/bugboats.sav.zip)
2. The first company has some "Clipper" ships that are 38 years old. They are set to be replaced immediately but they never get replaced.

### PR DESCRIPTION
**Pull request by Chr12t0pher**
Fixes #8153

> For more information we'll have to modify the variables that are passed to the string template, I can see this is done here:
> 
> https://github.com/OpenTTD/OpenTTD/blob/c972a63c8cbee7fa8d6d5af2cbbecb8c75ee561a/src/vehicle.cpp#L1058-L1067
> 
> Should I be adding some extra logic here to set a third parameter (cargo type) if the error message is my new one? Seems like there's a couple of conditionals for building the message depending on the error here already.
> 
> Made a barebones save for easier testing too - [bugboats.zip](https://github.com/OpenTTD/OpenTTD/files/4678745/bugboats.zip)

### CODE REVIEW

**Comment by nielsmh** [comment]
You should definitely try to include as much useful information to the player as possible:
- Tell the player which specific cargo type was not supported
- If the failure is due to orders requiring an impossible refit, tell the player which number order is the offender

**Comment by TrueBrain** [comment]
Hello @Chr12t0pher ; it has been a while since you opened this draft Pull Request. Is it ready for review? Or were you still working on this? :)

If it was ready, please do rebase it and hit the `Ready for review` button. If you are no longer interested in this, also no problem, but please let us know so we can clean our Pull Request list a bit :)

Thank you!

**Comment by TrueBrain** [comment]
I rebased your work and made some minor coding-style fixes, nothing crazy :)

**Review by LordAro — APPROVED** [review]
LGTM

**Pull request merged**
