### PR TITLE
Readme in Markdown syntax, 2nd attempt

### PR DESCRIPTION
**Pull request by auge8472**
Work was done in #6718 but as a result of mistakes I made, we decided to give it a 2nd, clean try.

### CODE REVIEW

**Comment by TrueBrain** [comment]
Looks good! Commit checker has a bit of issues with UTF-8 it seems, but that is an issue on our side :) We are working on it!

**Comment by TrueBrain** [comment]
Right, checks are working now. If you click on Details, and click on `Docker logs`, you will see that in a few places there are trailing whitespaces :) Please fix those, amend (`git commit --amend`) them to your commit and force push :) Thank you!

**Comment by auge8472** [comment]
What a never ending story! Jenkins tells me, I am an unknown user because the e-mail-address can not be detected. If I run `git config --list` in my local repository I get the expected values for my name, my e-mail-address, etc. pp.

Do I have to threaten the software? **\*grml\*** `<irony off />`

**Comment by TrueBrain** [comment]
No no, this is not your fault; it is mine :) Let me look at this :)

**Comment by TrueBrain** [comment]
There we go! This takes ~10 minutes :)

**Review by TrueBrain — APPROVED** [review]

**Comment by TrueBrain** [comment]
Thank you very much!!

**Comment by auge8472** [comment]
Only one word, announced with a few: **phew!** :-)

**Pull request merged**
