### PR TITLE
Prepare for 1.10.2 release

### PR DESCRIPTION
**Pull request by LordAro**
Quite a few changes in the end, but don't think we need an RC?

### CODE REVIEW

**Review by frosch123 — DISMISSED** [review]

**Comment by LordAro** [comment]
NB waiting to see if @ldpl gets any further with desync debugging

**Comment by nielsmh** [comment]
I really want a fix for #8066 into 1.10.2, we keep getting reports of it and it feels bad to tell people to play 1.10.0-RC1.

**Comment by LordAro** [comment]
I agree, but I'd rather not wait any longer. The amount of desyncs that @ldpl keeps finding isn't good...

**Comment by andythenorth** [comment]
If we have fixes for bugs in prod, we should ship those fixes early and often :)

"Releases are cheap"? :)

**Review by Yexo — APPROVED** [review]

**Pull request merged**
