### PR TITLE
Extended heightmap support

### PR DESCRIPTION
**Pull request by ZornsLemma**
Hi,

Back in 2012 there was some discussion (at https://www.tt-forums.net/viewtopic.php?f=32&t=61140) about adding support for "extended heightmaps", which effectively allow a scenario to be defined as a series of bitmaps and textfiles and then loaded into OpenTTD to start a new game with, just as a PNG/BMP heightmap can be used at the moment. This has the advantage that the user gets to choose the NewGRFs they want to use instead of the scenario creator having to decided this, since they're just starting a new game as far as OpenTTD is concerned. Extended heightmaps also offer the possibility of the user choosing the size of map to play the "scenario" on, instead of this being baked in. 

There's a draft spec for how this should work on the wiki: https://wiki.openttd.org/Terkhen/Scenario_format#Metadata_file

As discussed recently in the thread linked above, I've taken the existing patches (mostly by Terkhen, I think) and extended them to support loading an extended heightmap with height and town layers (the full spec has many different layer types).

I'd appreciate it if someone could do a brief review of the code on my branch and let me have any feedback, be it on minor problems or things which are just "not done in the OpenTTD way". There are a few particularly iffy points noted via comments containing the string 'EHTODO' which would probably benefit most from some expert attention. I'd like to avoid adding more code to support other features of the spec if I'm doing this in the wrong way!

The individual commits on my branch are just me talking to myself as I developed the code; anyone interested in doing a review should almost certainly just diff my branch against master.

Please let me know if you have any questions, of course!

Cheers.

Steve

### CODE REVIEW

**Comment by nielsmh** [comment]
Some general comments:
- The commit history needs to be squashed at some point, doesn't have to be right away. I don't think it's a good idea to add this in a single huge commit, better to make it several logical commits.
- I haven't figured out yet if the stuff under `eh-test/` is proper automated test data, or just for manual testing, but at the very least it needs to be moved to somewhere else in the tree.
- Overall the code looks pretty good.

**Comment by nielsmh** [comment]
The build fails on Windows, probably due to some differences in STL structure. Some includes seem to be missing.
Also one of the things it complains about is `auto_ptr`, you should probably use `unique_ptr` instead.

The build on Mac also fails due to a problem with STL includes.

The commit checker isn't going to be happy until the commit messages have been changed.

**Comment by ZornsLemma** [comment]
Thanks very much for taking a look!

Could you please let me have the failed build output for Windows? I don't have a Windows dev environment I can use but if I can see what went wrong I might be able to work out what the problem is. I'd hope if I can fix that then there's a chance of it building on the Mac too.

I did try using unique_ptr but it failed to build (on Linux, which is what I'm doing my development on); I think g++ only enables it if building with -std=c++14, not -std=c++11 as OpenTTD seems to use. My inclination is to stick with auto_ptr for now and rewrite the code to use raw pointers once it's otherwise finished; auto_ptr is really just a minor convenience as I'm using it here to avoid needing to remember to delete the memory at every early return.

The stuff under eh-test is just manual test data for my convenience and to serve as examples for anyone who wants to play with this; I want that in git for now but it would be removed before submitting any final pull request.

I'm happy to rework the commit history before eventually submitting a final pull request; at the moment I was just looking for the kind of feedback you've given before pushing on with the implementation of some more layers and see how that goes. Thanks once again for taking a look, I appreciate it!

**Comment by michicc** [comment]
OTTD is already using `unique_ptr`, even on Linux, so I'd guess you made an error somewhere. `auto_ptr` should really not be used due to the bad semantics of it.

The output of all CI checks can be viewed with the Details link.

**Comment by ZornsLemma** [comment]
You're right; the problem is that I was trying to use std::make_unique. I've pushed a commit which changes auto_ptr to unique_ptr, cheers!

I'll take a look at the CI checks. I didn't realise there would be an automated build, I thought nielsmh had tried to build it himself.

**Comment by Eddi-z** [comment]
It's actually a bit buried. You need to click on "details" in the CI build, but that output is horrible. then scroll to the bottom there and click on "view more details", then you can click on the platform you wish to check, and there it has the full output log

**Comment by andythenorth** [comment]
Thanks for this!  Extended heightmaps is something that's wanted, so it's good to see this PR.  

However there has been no progress for 3 months, and it's failing the automated checks.  I do close some older PRs if they have no progress, as it keeps the project healthy.  I'll close this one in a month or so if nothing changes.  Thanks!

**Comment by ZornsLemma** [comment]
Thanks, please do feel free to close it straight away if that's better for you. I do intend to pick this up again at some point in the future, but it's unlikely to be within the next month. (And if anyone else is reading this, do feel free to do build on what I've done here.)

**Comment by minexew** [comment]
With this patchset, is it possible to create extended heightmaps from SAV/SCN?

If not, is this something that should be worked on?

**Comment by ZornsLemma** [comment]
This work is not complete - this was just a draft pull request to get some initial feedback from the OTTD devs. At the moment it only allows loading of extended heightmaps (and a very limited form of them at that). Ultimately I would like to see it extended to allow saving of extended heightmaps, and at that point you would then be able to load a SAV/SCN and save it out as an extended heightmap, but that functionality doesn't exist yet. There are some patches on the forum thread which would probably be helpful in supporting this, but they're not complete.

I am not personally working on this at the moment - I may pick it up again in the future, of course. My work was built on some other people's earlier incomplete efforts, and if anyone feels keen to pick this up before I come back to it please do. (It would probably be good to just post a note on the forum thread to avoid duplicating effort.)

**Comment by TrueBrain** [comment]
Hi @ZornsLemma ! Hopefully you got the feedback you were looking for! As you pointed out yourself, you are not actively working on this Pull Request, I am going to close it for now. At any point feel free to reopen it, and if you want us to challenge your ideas or implementation, just let us know!

Cheers!

**Comment by ZornsLemma** [comment]
Thanks, that makes sense!

**Pull request closed without merging**
