### PR TITLE
Fix: rebase to 1.9 branch for backport PRs

### PR DESCRIPTION
**Pull request by glx22**

### CODE REVIEW

**Review by LordAro — DISMISSED** [review]

**Review by TrueBrain — DISMISSED** [review]
There is a variable "System.PullRequest.TargetBranch". Possibly it is better if we pick up that variable (if it is available) to run the CI against?

(And possibly better to first do that in master; after that backport it to branch)

**Comment by TrueBrain** [comment]
First needs fixing of https://github.com/OpenTTD/CompileFarm/issues/29 btw.

**Comment by glx22** [comment]
Second commit was just to check #7354 in non master, seems to be working fine

**Review by PeterN — DISMISSED** [review]

**Comment by glx22** [comment]
I think this PR should be a test PR that will be closed once CI is fixed and #7354 is backported.

**Comment by glx22** [comment]
`[command]/usr/bin/docker run -e TARGET_BRANCH=release/1.9 --rm -v /home/vsts/work/1/s:/home/vsts/work/1/s -w /home/vsts/work/1/s openttd/compile-farm-ci:commit-checker`
Now just need CompileFarm fix for the full test

**Comment by TrueBrain** [comment]
Superseded by https://github.com/OpenTTD/OpenTTD/pull/7359

**Pull request closed without merging**
