### PR TITLE
Fix #13110: [Script] convert table keys to string when generating JSON

### LINKED ISSUE #13110: [Crash]: CTD when calling GSAdmin.Send
### Version of OpenTTD

14.1, on Windows 10

### Steps to reproduce

Start a new game with the game script attached to this crash report. Wait 60 seconds. Crash to desktop happens.

### Upload crash files

[OpenTTD.zip](https://github.com/user-attachments/files/17850298/OpenTTD.zip)
[Schmitt_City_Growth.zip](https://github.com/user-attachments/files/17850302/Schmitt_City_Growth.zip)

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem
It's possible to create slots in squirrel table with a non string key:
```
	local test={};
	test[true]<-true;
	test[0]<-0;
	test["test"]<-test;
```
which triggers an assert when doing `GSAdmin.Send(test);` or just crash when asserts are disabled.

## Description
Replace the assert with a forced conversion to string.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Is it possible to instead convert the integer to a string automatically, so that it can "just work"?

**Comment by glx22** [comment]
Now the key is always converted to string first.

**Comment by glx22** [comment]
```
	local key1 = "test";
	local key2 = true;
	local key3 = 0;
	local key4 = {};
	local t = {};
	t[key1] <- "test";
	t[key2] <- true;
	t[key3] <- 0;
	t[key4] <- {};
	GSAdmin.Send(t);
```
produces `{"(table : 0x25BAB9EA6F0)":{},"0":0,"test":"test","true":true}`

**Review by PeterN — APPROVED** [review]
Well, exposing addresses is maybe less bad than hard crashing, so... :)

**Pull request merged**
