### PR TITLE
Add: Conditional order for max. reliability (patch by Cirdan, #6360)

### PR DESCRIPTION
**Pull request by Eddi-z**
Note: not tested myself

### CODE REVIEW

**Comment by planetmaker** [comment]
+1

**Review by planetmaker — APPROVED** [review]
I like the patch

**Comment by michicc** [comment]
Did anyone check loading of old savegames? As far as I can see, `OrderConditionVariable` is directly stored in the save game, thus modifying the enum in the middle breaks old saves.

**Comment by nielsmh** [comment]
@michicc that sounds plausible, will test. I think the best course of action is to just add another commit with the needed savegame fixups, rather than reverting and reworking.

**Comment by nielsmh** [comment]
Can confirm the bug is present.

Saving this orders list in 1.8.0:
image

Loads as this orders list after this patch is applied:
image

**Pull request merged**
