### PR TITLE
Workaround CMake/Xcode duplicate file name issue

### PR DESCRIPTION
**Pull request by Bouke**
## Motivation / Problem

9b56505feca991736c323ae64e3fc5416522de70 separated the code into a library and executable. This [triggers a bug in CMake's Xcode project file generation](https://gitlab.kitware.com/cmake/cmake/-/issues/20501). The result is a failing build. The suggested workaround is to rename one of the offending files, which is what this PR does. With this change Xcode will happily build the project.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Can you please fix your commit message match our style rules.

**Comment by Bouke** [comment]
> Can you please fix your commit message match our style rules.

Done!

**Comment by Bouke** [comment]
I've resolved the merge conflict.

**Review by TrueBrain — APPROVED** [review]

**Comment by TrueBrain** [comment]
It is MSVC 20-old all over again. Stupid stuff :P

**Comment by Bouke** [comment]
Not sure if it really is Xcode or just CMake generating invalid build instructions (from what I gather in the linked bug description, it seems the latter). All in all, no not ideal.

**Comment by PeterN** [comment]
I think this should be deferred, pending a PR that introduces a CI check to ensure that source filenames are unique.

**Comment by Bouke** [comment]
> I think this should be deferred, pending a PR that introduces a CI check to ensure that source filenames are unique.

A PR that introduces a check for duplicates will fail because of this issue. So let's first start with this, so Xcode project file generation is at least fixed. The duplicate checker can be merged later. If there's a duplicate introduced in the mean time (small chance), we'll resolve it then.

**Pull request merged**
