### PR TITLE
Feature: [NewGRF] Increase size of persistent storage to 256.

### PR DESCRIPTION
**Pull request by michicc**
Don't see a reason why not. Memory usage is basically negligible.

The feature test thingy is something we don't really do, do we? The OTTD revision var is basically useless right now though, so there needs to be some way to feature test.

### CODE REVIEW

**Comment by planetmaker** [comment]
Indeed, there is likely little reason to not increase it.

You increase the savegame version in the comments, but not in the actual definition of that very constant in  src/saveload/saveload.cpp

**Comment by andythenorth** [comment]
This is useful anyway, but is most useful in combination with 16 cargos in / 16 cargos out at industries.   (Using more cargos will quickly exhaust 16 storages for various production mechanics that industry sets might use).

**Comment by michicc** [comment]
> You increase the savegame version in the comments, but not in the actual definition of that very constant in src/saveload/saveload.cpp

Oops :smile: Will change tonight.

**Comment by frosch123** [comment]
I am not a fan of feature-test bits. Most GRF authors won't test them.
What would a GRF do, if the requirements are not met? Show an error and disable?

I prefer OTTD showing errors when a NewGRF uses something that does not exist. 
PersistentStorageArray::StoreValue/GetValue should trigger something like ErrorUnknownCallbackResult. (Though in this case it cannot be added to older versions of course.)

**Comment by michicc** [comment]
Old OTTD version will not show an error but just return 0 for the storage place. As such, triggering an error in this version doesn't help at all. The usual way used to be the revision test and then an action B, but revision needs to be re-thought now.

**Comment by planetmaker** [comment]
I guess I got convinced that the additional ttdpatch flag is not needed... I believe it will go unused. Yet I do not have a really strong opinion on that.

**Comment by andythenorth** [comment]
IMHO the issue of providing an OpenTTD version string is separate from this PR.

**Review by frosch123 — APPROVED** [review]
I still think that noone will check that flag in 8 months.

But since noone else wants to approve, I am not going to argue about a bit.

**Pull request merged**
