### PR TITLE
Codechange: Use std::make_unique instead of passing new into a unique_ptr.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Mixing `std::unique_ptr` with `new`.

## Description

Replace assignment from `new` with `std::make_unique` instead.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by rubidium42 — DISMISSED** [review]

**Comment by LordAro** [comment]
There was a reason (that I can't remember) why we couldn't use this before. Have those reasons gone with C++20?

**Comment by PeterN** [comment]
Long ago if they were. `std::make_shared<byte[]>` is the one that is/was missing.

Some of these could perhaps just be using `std::vector` instead, but that's a bit more of a rabbit hole.

**Comment by michicc** [comment]
It looks like the buffer is always overwritten or memset'ed anyway to me, so one could use `std::make_unique_for_overwrite` for a small performance speed-up.

**Comment by PeterN** [comment]
Given that `std::make_unique` will actually initialise the allocated array, it seems better to just remove the `MemSetT`s after.

I've removed the change to grf.cpp as that one is better done with `std::vector`.

**Review by michicc — APPROVED** [review]

**Pull request merged**
