### PR TITLE
Codechange: Add missing override specifiers.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Methods incorrectly marked `virtual` and/or not marked `override`.

## Description

This change marks methods that override base classes with `override`. Many of these were found with a linting tool. There may be some missing.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
Is there a warning we could enable to avoid these? Feels like there could

**Comment by PeterN** [comment]
> > Is there a warning we could enable to avoid these? Feels like there could
> 
> Good point. There is -Wsuggest-override. I will add that and update this PR (which of course will fail with the flag because there are more missing...)

Eh, 3rdparty screws it up of course :(

**Comment by LordAro** [comment]
Add -Wno-suggest-override to 3rdparty/CMakeLists ?

**Comment by PeterN** [comment]
> Add -Wno-suggest-override to 3rdparty/CMakeLists ?

Don't think that is possible, the subdirectories add files to the main project and is it all built together. And besides the bits that link to squirrel from OpenTTD would still trip up.

We have precedent with previous changes that add override, so I'll just do it as a separate commit.

**Review by frosch123 — APPROVED** [review]
We have plenty of modifies in 3rdparty/squirrel for all kind of warnings.

**Pull request merged**
