### PR TITLE
Fix: Script/AI construction of rail track and waypoints

### PR DESCRIPTION
**Pull request by JGRennison**
Scripts/AIs could not build rail track or waypoints as these command calls were not updated when the bit command p1/p2 bit allocations were changed to accommodate the increase to 64 rail types in bf8d7df734.

### CODE REVIEW

**Comment by LordAro** [comment]
Oh dear. This seems like exactly the sort of thing that could be added to the regression test, do you think you could look at doing that?

**Comment by PeterN** [comment]
Oops, somehow some bits were done but not all. @LordAro, that would be nice, but can come separately though?

**Comment by LordAro** [comment]
It can, but this is the very definition of a regression! It'll just get forgotten about until it breaks the next time if it's left until later

**Comment by TrueBrain** [comment]
Indeed this clearly needs a regression case :D I am surprised there isn't one yet tbh :)

**Comment by TrueBrain** [comment]
Euh .. no, there is no way to write a regression case for this without grfs I think :D As nothing was broken before, just wrong :) Sorry, my bad :D

**Comment by TrueBrain** [comment]
Indeed this clearly needs a regression case :D I am surprised there isn't one yet tbh :) Well, I guess there is only one for one axis, not for the other or something silly.

@JGRennison could you please add the regression entry to the regression set? Tnx!

(sorry for earlier more confusing messages; it was clearly too early to think straight)

**Comment by LordAro** [comment]
`bin/ai/regression/tst_regression/main.nut:1007` for easy locating - looks like it only tests building in one direction

**Comment by JGRennison** [comment]
I've added some regression tests for rail track and waypoints.
These pass as committed and fail if 7660851 is no longer applied (i.e. when tested after running `git revert -n 7660851`).

**Review by TrueBrain — APPROVED** [review]

**Comment by TrueBrain** [comment]
Perfect :D Tnx a lot!

**Pull request merged**
