### PR TITLE
Add: No plane crashes unless runway is too short option

### PR DESCRIPTION
**Pull request by SamuXarick**
https://www.tt-forums.net/viewtopic.php?p=1193823#p1193823

### CODE REVIEW

**Comment by Eddi-z** [comment]
~I kinda have two problems with this PR:~
~1. the title is confusing and misleading. the existing option already does what you claim you added, while you actually renamed the existing setting and added a new one~
~2. the new setting effectively duplicates the cheat that is already there, and i'm not convinced that this is a good idea~
I'll retract this, this was written in a spur of the moment, and my understanding of how the original code worked diverged from how it actually works

**Comment by SamuXarick** [comment]
```
plane crash | large aircraft | small airport | cheat enabled | probability
------------+----------------+---------------+---------------+------------------------
          0 |             no |            no |            no | (return)
          0 |             no |            no |           yes | (return)
          0 |             no |           yes |            no | (return)
          0 |             no |           yes |           yes | (return)
          0 |            yes |            no |            no | (return)
          0 |            yes |            no |           yes | (return)
          0 |            yes |           yes |            no | (return)
          0 |            yes |           yes |           yes | (return)
------------+----------------+---------------+---------------+------------------------
          1 |             no |            no |            no | 0x4000 << 1 (return)
          1 |             no |            no |           yes | 0x4000 << 1 (return)
          1 |             no |           yes |            no | 0x4000 << 1 (return)
          1 |             no |           yes |           yes | 0x4000 << 1 (return)
          1 |            yes |            no |            no | 0x4000 << 1 (return)
          1 |            yes |            no |           yes | 0x4000 << 1 (return)
          1 |            yes |           yes |            no | 0x4000 << 1 / 20 = 1638
          1 |            yes |           yes |           yes | 0x4000 << 1 / 1500 = 21
------------+----------------+---------------+---------------+------------------------
          2 |             no |            no |            no | 0x4000 << 1 / 1500 = 21
          2 |             no |            no |           yes | 0x4000 << 1 / 1500 = 21
          2 |             no |           yes |            no | 0x4000 << 1 / 1500 = 21
          2 |             no |           yes |           yes | 0x4000 << 1 / 1500 = 21
          2 |            yes |            no |            no | 0x4000 << 1 / 1500 = 21
          2 |            yes |            no |           yes | 0x4000 << 1 / 1500 = 21
          2 |            yes |           yes |            no | 0x4000 << 1 / 20 = 1638
          2 |            yes |           yes |           yes | 0x4000 << 1 / 1500 = 21
------------+----------------+---------------+---------------+------------------------
          3 |             no |            no |            no | 0x4000 << 2 / 1500 = 43
          3 |             no |            no |           yes | 0x4000 << 2 / 1500 = 43
          3 |             no |           yes |            no | 0x4000 << 2 / 1500 = 43
          3 |             no |           yes |           yes | 0x4000 << 2 / 1500 = 43
          3 |            yes |            no |            no | 0x4000 << 2 / 1500 = 43
          3 |            yes |            no |           yes | 0x4000 << 2 / 1500 = 43
          3 |            yes |           yes |            no | 0x4000 << 2 / 20 = 3276
          3 |            yes |           yes |           yes | 0x4000 << 2 / 1500 = 43
```

**Comment by SamuXarick** [comment]
without patch:
```
plane crash | large aircraft | small airport | cheat enabled | probability
------------+----------------+---------------+---------------+------------------------
          0 |             no |            no |            no | (return)
          0 |             no |            no |           yes | (return)
          0 |             no |           yes |            no | (return)
          0 |             no |           yes |           yes | (return)
          0 |            yes |            no |            no | (return)
          0 |            yes |            no |           yes | (return)
          0 |            yes |           yes |            no | (return)
          0 |            yes |           yes |           yes | (return)
------------+----------------+---------------+---------------+------------------------
          1 |             no |            no |            no | 0x4000 << 1 / 1500 = 21
          1 |             no |            no |           yes | 0x4000 << 1 / 1500 = 21
          1 |             no |           yes |            no | 0x4000 << 1 / 1500 = 21
          1 |             no |           yes |           yes | 0x4000 << 1 / 1500 = 21
          1 |            yes |            no |            no | 0x4000 << 1 / 1500 = 21
          1 |            yes |            no |           yes | 0x4000 << 1 / 1500 = 21
          1 |            yes |           yes |            no | 0x4000 << 1 / 20 = 1638
          1 |            yes |           yes |           yes | 0x4000 << 1 / 1500 = 21
------------+----------------+---------------+---------------+------------------------
          2 |             no |            no |            no | 0x4000 << 2 / 1500 = 43
          2 |             no |            no |           yes | 0x4000 << 2 / 1500 = 43
          2 |             no |           yes |            no | 0x4000 << 2 / 1500 = 43
          2 |             no |           yes |           yes | 0x4000 << 2 / 1500 = 43
          2 |            yes |            no |            no | 0x4000 << 2 / 1500 = 43
          2 |            yes |            no |           yes | 0x4000 << 2 / 1500 = 43
          2 |            yes |           yes |            no | 0x4000 << 2 / 20 = 3276
          2 |            yes |           yes |           yes | 0x4000 << 2 / 1500 = 43
```

**Comment by TrueBrain** [comment]
Closing in favor of #7302  Adding more settings isn't helping; we already have enough of those. Besides, we have a cheat preventing it, so it should not be based on the setting.

**Pull request closed without merging**
