### PR TITLE
DOS version music loading, new Win32 music driver

### PR DESCRIPTION
**Pull request by nielsmh**
This patchset improves music handling by adding a decoder for the TTD DOS music files (also TTO compatible), and replaces the old Win32 music drivers using MCI and DirectMusic with a new that uses Win32 MidiOut directly.

Additionally there are some changes to how playlists and title screen music are handled that should make things more in-line with original TTD.

Support for DOS version music playback is direct in the new Win32 music driver, but in all other music drivers has been added by writing the decoded music to a temporary standard MIDI file. The way and location this file is written may not be optimal, and whether the other music drivers still actually work is unknown. This part especially needs review.

### CODE REVIEW

**Comment by orudge** [comment]
This will require a bit of a review! Impressive work, though.

Something that jumps out at me initially is that you've removed the DirectMusic driver. In some ways I like this because it's a pain these days (not being part of the Windows or DirectX SDKs), but at the same time it did tend to offer - in my own experience - better quality MIDI playback on cheap audio hardware on Windows 9x. From Windows XP onwards, the DirectMusic GM synth was accessible via the standard Win32 MIDI playback APIs I believe. This may not be considered a major issue though, and perhaps the other devs are happy to drop support for it. I'd be tempted to boot up an old Win98 VM and see how the new driver works though (I'll have to hunt around for my old VM images!)

I seem to recall on Windows XP there was a large delay switching tracks using MCI (to be fair, this may have been in TTDPatch) - I assume that's not an issue with your driver now?

First review point that I can notice, based on the commit checker failure, is that all the commit messages need to be in the approved format:

Valid keywords: (Add|Feature|Change|Remove|Codechange|Cleanup|Fix|Revert|Doc|Update|Prepare)

For instance, 'Fix: [YAPF] Infinite loop in pathfinder.', 'Feature: Implement new MIDI driver.', etc. You should be able to do a git rebase -i, then use 'r' to reword, then git push -f and the pull request will be updated automatically.

**Comment by nielsmh** [comment]
First, I am working on cleaning up the patchset, reordering and merging changes, and fixing commit titles. It will take a while :)

On the Win9x case of DirectMusic, while it is a point, I'm not sure its worth keeping the code and build complications around for. These days, anyone using a Win9x machine most likely does only as a retro-PC and not a daily driver. For retro gaming purposes, sticking to whatever synth your sound card can support is more authentic, IMO!

**Comment by nielsmh** [comment]
As a note, the changes in "DOS music loading for non-Windows music drivers (untested)" are not tested on any of the drivers changed, but the `GetSMFFile` function itself is tested on Windows, and seems to work correctly. The changes to drivers are mostly trivial and "should" work, but of course you never know :)

**Comment by nielsmh** [comment]
Splitting this into more PRs using different branch names.

**Pull request closed without merging**
