### PR TITLE
Add #6410: [YAPF]  Use a max penalty for finding the nearest road vehicle depot

### PR DESCRIPTION
**Pull request by SamuXarick**
Implemented a maximum path cost penalty when searching for the closest road vehicle depot for YAPF
#6410

### CODE REVIEW

**Comment by PeterN** [comment]
What does this solve?

**Comment by SamuXarick** [comment]
Apparently it changes nothing, but makes the pathfinder quit earlier if it goes past the max_penalty.

Seems that the penalty is only used for automatic servicing. Manual sending to depot still uses unlimited penalty.

**Comment by J0anJosep** [comment]
@SamuXarick  Yes, it leaves earlier and the max_distance penalty is used. For consistency, either max_distance should be used or removed from the code. I forgot to add a patch for it, but I wrote them two years ago (YAPF and NPF):
https://github.com/J0anJosep/OpenTTD/commit/d6a311b0c4f5480ac6b9632ff374d25650544cf6
https://github.com/J0anJosep/OpenTTD/commit/3680d95f7eb9e83019d2f81f7a15219467b68701
Sorry for forgetting about it. Double work done here.

Anyway, I don't see why a change in max_distance is needed.

**Comment by SamuXarick** [comment]
Because [https://github.com/OpenTTD/OpenTTD/blob/25a060b4ae9d7c6a145e7a8ca371fb2182826359/src/pathfinder/yapf/yapf.h#L62-L70](https://github.com/OpenTTD/OpenTTD/blob/25a060b4ae9d7c6a145e7a8ca371fb2182826359/src/pathfinder/yapf/yapf.h#L62-L70)

Oh, I did that for NPF too, included it in my other patch request #6928 

https://github.com/OpenTTD/OpenTTD/pull/6928/commits/e556519297061fd37a369ab4f21c763d9205fe72#diff-fe68d910d6c0b0a8d81eb65e88e60fb1

**Comment by J0anJosep** [comment]
> Because
> 
> [OpenTTD/src/pathfinder/yapf/yapf.h](https://github.com/OpenTTD/OpenTTD/blob/25a060b4ae9d7c6a145e7a8ca371fb2182826359/src/pathfinder/yapf/yapf.h#L70)
> 
> Line 70 in [25a060b](/OpenTTD/OpenTTD/commit/25a060b4ae9d7c6a145e7a8ca371fb2182826359)
>  FindDepotData YapfRoadVehicleFindNearestDepot(const RoadVehicle *v, int max_penalty); 
> 
> Oh, I did that for NPF too, included it in my other patch request #6928
> 
> [e556519#diff-fe68d910d6c0b0a8d81eb65e88e60fb1](https://github.com/OpenTTD/OpenTTD/commit/e556519297061fd37a369ab4f21c763d9205fe72#diff-fe68d910d6c0b0a8d81eb65e88e60fb1)

In the file you referenced, both max_distance and max_penalty are used and their meaning is the same. It is explained in the comments. If it is an inconsistency, it shouldn't be dealt here but in a separate commit.

**Comment by TrueBrain** [comment]
We recently switched from Jenkins as CI to Azure Pipelines as CI. This means you need to rebase before this Pull Request will pass its checks. Sorry for the troubles!

**Comment by andythenorth** [comment]
Same issue is addressed by #7009, which is merged.

**Pull request closed without merging**
