### PR TITLE
Codechange-Commits from #6599

### PR DESCRIPTION
**Pull request by Eddi-z**
As only the first 2 changes were considered for #7049, here is the rest

### CODE REVIEW

**Comment by PeterN** [comment]
What is this PR about?

**Comment by Eddi-z** [comment]
Mainly to have these commits not-lost in case someone wants to review them?

**Comment by PeterN** [comment]
Sorry but PRs should be well formed with intentions, goals and reasons, not just a collection of random commits just to keep them around.

**Comment by Eddi-z** [comment]
I don't know what you want to hear. the commits have a description, and a tiny bit of details are in #6599, the original ticket. i was asked to turn the patches into a PR, so here you are. Do what you want with it.

**Comment by PeterN** [comment]
I'm closing this now as the remaining patches do not form a coherent sequence. We can still pick bits and pieces if we wish.

**Pull request closed without merging**
