### PR TITLE
Prepare for 1.10.0 release

### PR DESCRIPTION
**Pull request by LordAro**
All merged backport-requested PR to this point (still 2 open)

### CODE REVIEW

**Comment by LordAro** [comment]
Would appreciate someone else going over the list of backported PRs (and not requested backported)

I don't think I've missed any, but...

**Comment by glx22** [comment]
No missing requested backports for me. Maybe #7990 could be in too.

**Review by glx22 — DISMISSED** [review]
LGTM

**Comment by LordAro** [comment]
Now ready for review :) Don't think we've forgotten anything else...

**Review by glx22 — DISMISSED** [review]
seems correct

**Review by TrueBrain — APPROVED** [review]
YOLO

**Pull request merged**
