### PR TITLE
Fix: unicode characters in Romanian town names

### PR DESCRIPTION
**Pull request by nikolas**
Many of these town names were using the 'a with ~ above it' character, which should
actually by 'a with u above it'. There were other missing accents as well which I've
added.

### CODE REVIEW

**Comment by LordAro** [comment]
>Message contains non-ASCII characters or tabs: 'Many of these town names were using the '\xe3' character, which should'

heh.

**Review by planetmaker — APPROVED** [review]
Thanks, this also seems alright.

And I see... what LordAre means... the commit message needs to be changed to NOT contain the characters in question.

**Review by planetmaker — CHANGES_REQUESTED** [review]
the non-unicode characters sadly need to be removed from the commit message.

**Comment by nikolas** [comment]
done

**Review by planetmaker — APPROVED** [review]
So, now the commit message checker is also satisfied...

**Pull request merged**
