### PR TITLE
Feature: Raise a corner of land automatically when building aqueducts

### PR DESCRIPTION
**Pull request by SamuXarick**

### CODE REVIEW

**Comment by SamuXarick** [comment]
nontbourne bridge transport 1950-04-25
nontbourne bridge transport 1950-05-11

**Comment by andythenorth** [comment]
I agree that aqueducts should not be limited by slopes.  However terraforming isn't the correct solution: Rail/road bridges use foundations to solve the same issue.  

It would be better to permit foundations for canals.  I am happy to make the case that this would be good for the game, lots of other things have been made more permissive on slopes over time (e.g. road depots and drive-in roadstops). 

Foundations would also imply allowing lowering of land next to a canal.

I don't know if there are implementation problems with foundations for canals, nor how rivers should be handled.

_Issues_
- Aqueducts currently work differently to rail/road bridges, they're built like tunnels from a single tile, not dragged like rail/road bridges
- frosch indicated that water on foundations might not be possible

**Comment by nielsmh** [comment]
Viewed with the (terribly dark) sunglasses of realism concerns, aqueducts should probably also occupy the tile height below them, requiring a two tile heights below for rail/road to be built.

**Comment by TrueBrain** [comment]
Given no developer showed interest in this for the last 2 months, I am going to call this a day. Sorry, but this doesn't seem to itch others as much as it does you.

Thank you for the contribution though!

**Comment by Hexus-One** [comment]
Is it possible to re-open this?
If aqueducts are indeed similar to tunnels then i think they should exhibit the same terraforming behaviours (eg how tunnels raise land to accomodate the other end). It would be more convenient for players.
Also I think it would give PR #7607 a bit more liberty in path options.
Makes me wonder though - should plain canal tiles also have the same behaviour? And locks as well?

**Comment by andythenorth** [comment]
I tried to re-open, but GitHub UI says no - 'Reopen pull request' button is disabled.

**Comment by Rito13** [comment]
> I agree that aqueducts should not be limited by slopes. However terraforming isn't the correct solution: Rail/road bridges use foundations to solve the same issue.
> 
> It would be better to permit foundations for canals. I am happy to make the case that this would be good for the game, lots of other things have been made more permissive on slopes over time (e.g. road depots and drive-in roadstops).
> 
> Foundations would also imply allowing lowering of land next to a canal.
> 
> I don't know if there are implementation problems with foundations for canals, nor how rivers should be handled.
> 
> _Issues_
> 
> * Aqueducts currently work differently to rail/road bridges, they're built like tunnels from a single tile, not dragged like rail/road bridges
> * frosch indicated that water on foundations might not be possible

[#11012](https://github.com/OpenTTD/OpenTTD/pull/11012) has been closed because it allowed foundations for canals to solve such issue. Althoug in the current state it was useless, as it allowed to build aqueducts on foundations but not canals and it didn't allow to rise land under the aqueduct that was on foundation, like the stations and other buildings do.

> I tried to re-open, but GitHub UI says no - 'Reopen pull request' button is disabled.

If it is possible and if @SamuXarick want to work on this I would opt for reopening this PR because it works much better (Does not crash the game and shows appropriate messages when failed to terraform the land.) than [#13545](https://github.com/OpenTTD/OpenTTD/pull/13545) and implements exactly the same feature.

**Pull request closed without merging**
