### PR TITLE
Fix fdc2e85: Double close of file handles

### PR DESCRIPTION
**Pull request by nielsmh**
When unpacking downloaded content, the downloaded .gz file was being opened with `fopen`, the OS file handle given to zlib, and then afterwards zlib told to close the file.

But the `FILE *` object was never closed with `fclose`, meaning the stdio library would have a hanging file object, whose file handle was now invalid or referred to a different file. This caused asserts during shutdown with Microsoft's C library in debug mode.

Fix this by properly duplicating the OS handle and `fclose`ing the `FILE *` object, before giving the handle to zlib.

### CODE REVIEW

**Comment by PeterN** [comment]
Is this not enough?

```
-       gzFile fin = gzdopen(fileno(ftmp), "rb");
+       gzFile fin = gzdopen(dup(fileno(ftmp)), "rb");
```

**Comment by nielsmh** [comment]
At the very least the "else if" at the bottom would also need changing so ftmp is properly closed.

And apparently dup() is too POSIX for Microsoft, and _dup() is too ANSI for everyone else?

**Comment by LordAro** [comment]
Concur with @PeterN , the anonymous lambda is a bit too dirty for my tastes

**Comment by PeterN** [comment]
Looks okay to me and is exactly what the [zlib documentation](https://www.zlib.net/manual.html) says to do.

**Review by PeterN — APPROVED** [review]

**Pull request merged**
