### PR TITLE
Add: [Actions] msys2/MinGW CI

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem
Sometime we inadvertently break compilation with MinGW, and it can be unnoticed for a long time (until me or @LordAro happen to try to build with MinGW). 

## Description
I added MinGW to the CI build (for 32bit and 64bit).

## Limitations
~~32bit currently fail, but it's not caused by this PR ;)~~

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by michicc** [comment]
Will compiling both 32-bit and 64-bit give us much extra info, or would one of them be enough for 99% of the good test? Doing just one could make sure CI run time doesn't get too long (applies to MSVC 2017 as well).

**Comment by glx22** [comment]
Sometimes 32-bit fails while 64-bit passes. It was the case here, I needed 3 extra commits to build 32-bit.

**Comment by TrueBrain** [comment]
Wow, takes 13 minutes to run a MingW build .. what is taking so long for this target?

Anyway, still more warnings to fix before we can merge this: https://github.com/OpenTTD/OpenTTD/actions/runs/582953728 :)

**Comment by LordAro** [comment]
I've never been able to work out how to fix the format & function-cast warnings. I suspect the best solution is just to disable them

**Comment by glx22** [comment]
Yeah I tried many things for these warnings, but nothing worked.

**Comment by michicc** [comment]
The warning on `src/3rdparty/squirrel/squirrel/sqfuncstate.cpp#L88` seems to imply that OTTD_PRINTF64 is not defined properly, which would be an actual problem.

**Comment by glx22** [comment]
But it's defined properly and it's the only place we get a warning.

**Comment by TrueBrain** [comment]
Otherwise maybe you can PR the fixes for mingw from this PR, so we can at least accept that?

Adding CI targets that generate warnings isn't that nice, especially as we are currently completely clear of any :) So I guess that would take some more effort to fix/change .. but that doesn't mean we shouldn't already accept the fixes that do work :D

**Review by TrueBrain — APPROVED** [review]

**Comment by TrueBrain** [comment]
Is it just me, or is the caching not really working? Every run it takes 90s to setup MSYS2, despite it saying it loaded it from cache. Bit odd, I think?

**Pull request merged**
