### PR TITLE
Fix #7244 #7226: OPF doesn't take 90 deg turns into account.

### LINKED ISSUE #7244: OPF ships locked in a reverse-loop
## Version of OpenTTD
master-g45ce517105
## Expected result
opf ships should know they can't do a 90 degrees turn after a reverse
## Actual result
opf ships get stuck in a reverse-loop, doing 180 degree turns against an obstacle, reverse, advance a tile, and do 180 degree turn again, heading back against the shore again.
## Steps to reproduce
Load savegame, ships 78, 59, 77, 75, 79, 81, 80.
[Koln Mines Shipping, 1996-12-30.zip](https://github.com/OpenTTD/OpenTTD/files/2877606/Koln.Mines.Shipping.1996-12-30.zip)

### PR DESCRIPTION
**Pull request by J0anJosep**

### CODE REVIEW

**Comment by michicc** [comment]
You need a comma between the two issue numbers in the commit messages (or maybe even `Fix #7224, Fix #7226`, but I think there was a change to the CI to get rid of the ugly second Fix).

**Comment by michicc** [comment]
Oh, and I think you got your numbers wrong.

**Comment by J0anJosep** [comment]
Yes. I will correct them.

**Comment by michicc** [comment]
Bad commit checker 😞 

`Fix #7244, 6ca637b8c1:` is supposed to be alright according to the CI log.

**Review by michicc — APPROVED** [review]

**Pull request merged**
