### PR TITLE
Fix #7970: [Win32] Disable event loop on crash to prevent recursive faults

### LINKED ISSUE #7970: Crash in crash handler - Assertion failed at line 2981 of window.cpp
## Version of OpenTTD
Last tested: d7a928a-windows-win32 (Windows 7 Ultimate)

## Expected result
No crash in crash handler

## Actual result
Crash in crash handler - `Assertion failed at line 2981 of window.cpp: HasModalProgress() || IsLocalCompany()`
No crash log created (a crash in the crash handler does not produce a crash log).

## Steps to reproduce
??? (Seems to randomly occur, especially with starting new games, testing scripts, loading games, saving the config, etc.)

### PR DESCRIPTION
**Pull request by glx22**
Closes #8175

### CODE REVIEW

**Review by LordAro — COMMENTED** [review]
I can't speak for its correctness, but it definitely looks better...

**Comment by nielsmh** [comment]
This should not affect the ability of the screenshot to generate, right?

**Comment by glx22** [comment]
Hmm I should try that. I just tested with the broken save from #7970.

**Comment by glx22** [comment]
Ok I checked, screenshot is generated. And there's an issue in the crash dialog (not related to this change), `_crash_desc` doesn't fit.

**Review by Yexo — APPROVED** [review]

**Pull request merged**
