### PR TITLE
Codechange: Replace custom rounded square root logic with standard library functions

### PR DESCRIPTION
**Pull request by 1f5**
## Motivation / Problem
The old function is complicated and slow, because it calculates the square root using only integers. This might be useful for code running on systems where no floating point numbers are available, but we don't have such limitations. Using standard library functions is faster and need less code.

## Description
Replaces the whole function logic by simply getting the square root of the input and rounding it. The output is cast to uint32_t.

## Limitations
Performance increase should not be noticeable during normal gameplay.
Does not remove any tests.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
Definitely going to need some numbers on "it's faster"

**Comment by LordAro** [comment]
Probably on a variety of platforms & architectures (we support many, remember)

**Comment by frosch123** [comment]
OpenTTD multi-player relies on a deterministic progression of the game state.
That's why all game logic only uses integers, and no floats.
I am not aware of `IntSqrt` being part of some performance critical code-path.

As such I value potential non-determinism/desyncs worse than some CPU cycles.

**Comment by rubidium42** [comment]
OpenTTD's logic for the state loops does not use floating points numbers/calculations. This rule was introduced to prevent desyncs due to implementations of floating point logic differing between platforms.

So, the bar for adding floating point calculations in the state loop is very high as you need to essentially prove that there is no platform where the floating point square root behaves different.

**Comment by 1f5** [comment]
Thanks for clarifying this.

**Pull request closed without merging**
