### PR TITLE
Add problem matchers to CI

### PR DESCRIPTION
**Pull request by LordAro**

### CODE REVIEW

**Comment by glx22** [comment]
So `repo.msys2.org` seems to be back. But while it was down I tried some stuff to auto update `vcpkg`, and it was not very easy to do using `run-vcpkg` action, so I ended rewriting windows workflow (see [here](https://github.com/glx22/OpenTTD/pull/1/check)). I also fixed linux failure.

**Comment by LordAro** [comment]
Would you say that "doing it ourselves" is better than using the run-vcpkg action?

**Comment by glx22** [comment]
run-vcpkg action doesn't seem to support automatic update for vcpkg without a trick (using `git fetch` and giving `FETCH_HEAD` to run-vcpkg).
It's also possible to [force the vcpkg commit id](https://github.com/glx22/OpenTTD/pull/3) to use, but that means we must change it whenever we want to upgrade vcpkg or one of the libs we need.

**Comment by TrueBrain** [comment]
I would suggest we first ask the action-maintainer to add the ability to do this; we cannot be the only one who would like this :) As I make actions myself, I always truly appreciate others asking for their use-case .. it improves actions for all :)

**Review by TrueBrain — APPROVED** [review]

**Pull request merged**
