### PR TITLE
Feature: Toyland-specific river graphics

### PR DESCRIPTION
**Pull request by zephyris**
Let's make some better river sprites for Toyland!

toylandrivers

## Motivation / Problem
When using base graphics, Toyland rivers re-used the temperate river bank and river rapids sprites. This was an _OK_ match, but didn't look great.

## Description
I've drawn dedicated Toyland river sprites, borrowing from the original sprites to match Toyland style. I used yellow for the river tiles, like the yellow on shore tiles, and borrowed Toyland rocks for the rapids. Uses 32bpp sprites for water slope shading and the rocks make the rivers clearly impassable for boats.

## Limitations
Water slopes aren't shaded when using 8bpp blitters.

## Checklist for review
~~Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)~~

### CODE REVIEW

**Comment by PeterN** [comment]
Not sure if this situation is worth dealing with... I suppose it can come up in game when removing rivers. The river edges on sloped tiles are quite wide, and are overlapping the rocks.

image

**Comment by PeterN** [comment]
Yes, #11491 was the same. To be clear it's the build system at fault, we appear to copy the files during configure rather than during build.

And yes, I think the different shading of the edges makes them look wider.

**Comment by glx22** [comment]
Yeah build system uses `file(GLOB_RECURSE...` to get the file list at config time, so adding a new file doesn't trigger a reconfig.
Something I may look at (but not very urgent as we don't touch grfs very often).

**Comment by glx22** [comment]
Will need a rebase, and addition of the 3 new files in `media\baseset\orig_extra\CMakeLists.txt`

**Review by rubidium42 — APPROVED** [review]

**Pull request merged**
