### PR TITLE
Fix: Wrong punctuation in Simplified Chinese

### PR DESCRIPTION
**Pull request by wensimehrp**
## Motivation / Problem

The current Simplified Chinese translation contains many punctuation and formatting problems.

## Description

This PR changes the zh_CN language file and corrects the incorrectly implemented translations. This includes:

- Adding spaces between Chinese characters and non-Chinese characters.
- Fixing various punctuation marks, including commas, periods, question marks, quotation marks, etc.
- Removing extra spaces and improving readability.

## Limitations

A known problem is that the function handling line breaks (which is different between OSes, I guess) only creates a new line when a space (breaker) is present or there are too many characters in one line. Unfortunately, full-width punctuations aren't counted as breakers, so the merge of this PR might decrease the readability of the whole script, which goes against the initial goal. That being said, this problem may be minor in most cases, and could be solved if #11766 is merged or full-width characters are counted as additional breakers.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Translation changes should be done with the web translator.

**Comment by WenSimEHRP** [comment]
> Translation changes should be done with the web translator.

I thought this is too much

**Review by PeterN — DISMISSED** [review]
"Probably fine"

Looks more consistent for sure.

**Comment by WenSimEHRP** [comment]
Everything should be done now.

**Review by LordAro — DISMISSED** [review]
I'm not going to merge it because I don't trust the WT to not break horribly. Needs @truebrain or @frosch123 to confirm that This Is Fine.

**Review by TrueBrain — DISMISSED** [review]
I too have absolutely no clue what eints is going to do. Maybe it reverts these changes. Maybe it keeps them.

But you know, only one way to find out. Worst case, we have to take eints down and someone actually has to read up on how eints works. We will manage :P

In other words: YOLO!

**Review by TrueBrain — APPROVED** [review]

**Pull request merged**
