### PR TITLE
Change: allow GS to mutate vehicle orders (previously AI-only)

### PR DESCRIPTION
**Pull request by andythenorth**
## Motivation / Problem

* For features or gameplay changes:
    * What was the motivation to develop this feature?
        * GS can't manipulate vehicle orders. 
    * Does this address any problem with the gameplay or interface?
        * It addresses that GS can't manipulate vehicle orders.
    * Which group of players do you think would enjoy this feature?
        * This feature is about extending the GS API to be more comprehensive, and not trying to anticipate in advance if GS authors can be trusted to use it wisely :)

## Description

* For features or gameplay changes:
    * What does this feature do?
        *  Makes existing AI control over vehicle orders available to GS 

## Limitations

Describe here
* Is the problem solved in all scenarios?
   * Not sure, I just removed the -game flag from doxygen comments
* Is this feature complete? Are there things that could be added in the future?
   * Not sure, I just removed the -game flag from doxygen comments
* Are there things that are intentionally left out?
   * Not sure, I just removed the -game flag from doxygen comments
* Do you know of a bug or corner case that does not work?
   * Not sure, I just removed the -game flag from doxygen comments
   * Works in my simplistic test script
   * Might need pre-condition enforced for company etc, not sure?
## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
    * Nope
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
    * Nope 
* This PR affects the save game format? (label 'savegame upgrade')
    * Not AFAIK
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
        * This will need doing, I will push again when I've figured out how to do that
    * The compatibility wrappers (compat_*.nut) need updating.
        * Not sure, hoping a reviewer might tell me :)
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * Nope

### CODE REVIEW

**Comment by SamuXarick** [comment]
I think you should take this opportunity to allow GS's access more AI-only functions. ScriptGroup comes to mind. However this might uncover some unintended behaviours, must thread with care.

**Review by LordAro — APPROVED** [review]
Sure, why not

**Review by LordAro — CHANGES_REQUESTED** [review]
Actually no, needs changelog

**Comment by 2TallTyler** [comment]
Should just be b0402faee1bbd2dd83a6fa9d0cfb2901cc393429, I think.

**Pull request closed without merging**
