### PR TITLE
Fix: Spectator color

### PR DESCRIPTION
**Pull request by SamuXarick**
unnamed 2002-01-06

### CODE REVIEW

**Comment by PeterN** [comment]
This is wrong, it should be uncoloured so that when not highlighted, it stays black.

**Comment by nielsmh** [comment]
Is this really correct? Shouldn't it have no colour code at all instead? Most other menus have black text when normal, and white text when highlighted. The exceptions are Client list and Spectate in the Companies menu in multiplayer.

image
image

**Comment by nielsmh** [comment]
In fact, shouldn't it say "Global goals" rather than Spectator? Since they're not the goals for the spectators, but the goals for everyone.

**Review by nielsmh — CHANGES_REQUESTED** [review]
Per the above comments, this is the wrong fix.

**Pull request closed without merging**
