### PR TITLE
Fix #12551, 8746be8: Reinstate current order test when removing road stop.

### LINKED ISSUE #12551: [Crash]: Assertion failed at line 114 of D:\\a\\OpenTTD\\OpenTTD\\src\\core\\pool_type.hpp: index < this->first_unused
### Version of OpenTTD

Nightly build 20240421,Windows

### Steps to reproduce

I don't know WHAT HAPPENED

### Upload crash files

[OpenTTD.zip](https://github.com/OpenTTD/OpenTTD/files/15050886/OpenTTD.zip)

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

#12144 replaced pool iteration with FindVehiclesWithOrder, however the test for current_order being OT_GOTO_STATION was erroneously removed.

## Description

Reinstate the check of current_order.

Likely fixes the cause of #12551, @JGRennison has been able to reproduce.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
This should fix the cause but not the symptoms. I'm not sure if we should do that, or how to do that.

**Comment by JGRennison** [comment]
> This should fix the cause but not the symptoms. I'm not sure if we should do that, or how to do that.

Whilst it's apparently been there for a long time, the last_station_visited clearing behaviour in `GetOrderStationLocation` seems to me to be very surprising in a "Get" function of that type. Nothing about it's name or documented purpose suggests that it should do something like that. It seems a bit of a footgun.
Renaming it to make clearer that it's a destructive operation, or moving the clearing to whichever call site at which the clearing behaviour is intended might be an idea.

**Comment by PeterN** [comment]
Yes, it will also skip orders if the station is invalid for the vehicle. Not really a Get operation :-)

**Review by rubidium42 — APPROVED** [review]
I would not bother too much about broken saves for now. If the 12551 issues keep coming after this has been fixed then it might potentially be worth considering trying to implement a workaround for broken saves.

**Pull request merged**
