### PR TITLE
Remove DirectMusic driver

### PR DESCRIPTION
**Pull request by nielsmh**
The DirectMusic driver is troublesome, as the API is deprecated by Microsoft, not includes in current SDKs, and not supported in 64 bit builds at all. The new Win32 music driver solves the issues the old MCI-based driver had on modern Windows, so DirectMusic is no longer needed in that respect.

The main drawback of removing the DirectMusic driver is that it's the only way to use the Microsoft GM softsynth on Windows 9x/Me, meaning anyone on those OS must use whatever synth their hardware provides. I think that's an insignificant sacrifice.

### CODE REVIEW

**Comment by michicc** [comment]
In my very subjective view, the default DirectMusic synth sounds better than the MCI one. Also, it is neither completely removed from the SDKs nor 64-bit Windows.
Windows Vista did indeed not have any 64-bit DirectMusic support, but Windows 7 added some stuff back in. It did not add the high-level things we use, but the low-level handling is apparently back in. It might be possible to use this together with the new custom MIDI file handling.

**Comment by nielsmh** [comment]
The only difference I can tell, when listening side by side, is that DMusic performs a little fade-out when you stop a song.

**Comment by TrueBrain** [comment]
@michicc: do you mean you want to keep the current dmusic implementation? (I can read your comment in both ways :D).

Possibly an idea is that we make the new driver the default first, keeping the current code for those who want to check out the difference. Of course that currently only works for 32bit Windows binaries :)
Then again, keeping something that only works for a subset of all the Windows users is possibly not that helpful.
That said, dropping dmusic would make me really happy, as it is a bit of a pain to add it to the Compile Farm for only 32bit Windows (and the way to install the headers is also not really nice :D).

**Comment by michicc** [comment]
@TrueBrain: Mainly I meant to try to re-write the DMusic driver into a low-level driver, which in theory also works for 64-bit and with the current SDK only. Of course, I don't know yet if that is in fact feasible.

@nielsmh: A short sample of what I mean: http://www.icosahedron.de/openttd/patches/Ottd_Midi.mp3
MME/MCI driver first, DirectMusic second. This is a Windows 10 x64, 32-bit OTTD, default Microsoft HDA drivers for some Realtek sound hardware, no other explicit MIDI settings done.

**Comment by nielsmh** [comment]
@michicc: Strange, I don't get any reverb effects when using the MS synth.

I'm not sure if it really makes sense to write a new driver using the MS synth directly, instead of just using one of the OSS softsynths available and getting identical results on all platforms.

**Comment by nielsmh** [comment]
Okay, apparently if you pass the "port" parameter to the DMusic driver it triggers a different mode or compatibility settings of sort, and no effects are applied.

So, effects: `musicdriver = "dmusic"`

No effects: `musicdriver = "dmusic:port=0"`

I wonder if it isn't possible to activate the effects/deactivate the compatibility mode through the MIDI interface, with some sysex or similar.

**Comment by michicc** [comment]
Port 0 is most of the time the legacy MIDI mapper, while the default DirectMusic port uses a separate, DirectMusic only software synth (would be port 2 on my box, but YMMV).

**Comment by nielsmh** [comment]
Keep it for now then, #6779 fixes a few bugs instead.

**Pull request closed without merging**
