### PR TITLE
Fix f5381798: Docking station tile area was being misused

### PR DESCRIPTION
**Pull request by SamuXarick**

### CODE REVIEW

**Comment by LordAro** [comment]
What makes you think this is wrong? It certainly wasn't caused by f538179 - the function structure predates that

**Comment by SamuXarick** [comment]
Before docking tiles, there was only 1 tile, and the area had to be set manually to 1 width, 1 height.
https://github.com/OpenTTD/OpenTTD/commit/f538179878370b3bec8bf1575dc30c1377461ebc#diff-249239106fd58103249d1178388d72feL404

The way it works now it puts in a rectangle area the possible locations of docking tiles.
`*ta = this->docking_station` already includes values for `ta->tile`, `ta->w` and `ta->h`
The `break;` was causing `ta->w` and `ta->h` to be redefined to only the docking tile at the top corner. For a single docking tile, that is still correct, but for multiple docking tiles for the same station, that was only partially correct.

With `return;` instead of `break;` the problem is solved. This in turn also makes `ta->w = 1;` and `ta->h = 1;` obsolete, because all other StationType types all have a `return;`, making that part of the code unreachable. Therefore I cleared it.

**Comment by PeterN** [comment]
This change looks correct, however I'd like to know how this problem manifests. You've stated this fixes the problem without actually saying what problem it fixes other than it was "misused".

**Comment by SamuXarick** [comment]
My explanation was actually wrong, the problem is worse than I thought.

Charningstone Transport, 15th Jul 1950 (2)

On this screenshot, `ta->tile` is the tile at the top corner of the white recangle area. `ta->w` is 5 and `ta->h` is 8. The area encompasses the two docking tiles of the same multi-dock station.

The `break;` was causing `ta->w` and `ta->h` to be redefined to only the tile at the top corner. In this case it's not even a docking tile.

`Station::GetTileArea` is called by YAPF and NPF, via `CalcClosestStationTile`.

Savegame
[Charningstone Transport, 29th Jun 1950.zip](https://github.com/OpenTTD/OpenTTD/files/4237846/Charningstone.Transport.29th.Jun.1950.zip)

**Comment by SamuXarick** [comment]
[Charningstone Transport, 5th Aug 1954.zip](https://github.com/OpenTTD/OpenTTD/files/4237974/Charningstone.Transport.5th.Aug.1954.zip)
With the fix, pathfinder sends ships towards the right corner. Without it, it sends towards the north corner.

image

**Review by LordAro — APPROVED** [review]

**Pull request merged**
