### PR TITLE
Remove: Support for macOS before 10.9

### PR DESCRIPTION
**Pull request by nielsmh**
Remove all assumptions and code paths that are only relevant for builds intended to support macOS earlier than 10.9. This simplifies the Cocoa video driver a lot and makes it much easier to follow the code.

So far this is barely just smoke-tested on my own machine with macOS 10.13.

### CODE REVIEW

**Comment by orudge** [comment]
If we're dropping support for <10.9, the enable_osx_g5-related stuff can go too, since OS X hasn't run on PPC since 10.5.

**Comment by glx22** [comment]
If I correctly understand https://developer.apple.com/documentation/coreservices/carbon_core/gestalt_manager?language=objc the following blocks can be removed too
https://github.com/OpenTTD/OpenTTD/blob/d1b7eb2de1d79acfcae1e591cf66d95be6b5f5c7/src/os/macosx/macos.mm#L33-L41
https://github.com/OpenTTD/OpenTTD/blob/d1b7eb2de1d79acfcae1e591cf66d95be6b5f5c7/src/os/macosx/macos.mm#L68-L81
That should remove the deprecated warnings.

And I think some other conditional stuff in this file can be removed too.

**Comment by michicc** [comment]
Unfortunately, the alternative to `Gestalt` was only introduced in 10.10 (see https://developer.apple.com/documentation/foundation/nsprocessinfo/1410906-operatingsystemversion?language=objc). 10.9 has no official, non-deprecated system function.

**Comment by nielsmh** [comment]
Closing in favour of #8078 - I don't see myself finishing or cleaning up this one any time soon.

**Pull request closed without merging**
