### PR TITLE
Change: Use seconds for AI start delay

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

I was asked to break #10605 into smaller PRs for review. Most of the optional real-time units in it are indeed optional, but settings stored in days are annoying since there isn't a real-time unit which corresponds to it for a simple string swap -- the number itself would have to be converted (1 day = 2 seconds).

AI start delay doesn't need to be in days as it's a player setting to determine how much head start they get, and seconds almost make more sense.

## Description

Use seconds for AI start delay.

## Limitations

"Seconds" is 2 seconds per day, so it relies on https://github.com/OpenTTD/OpenTTD/pull/10607 for complete accuracy, doesn't count when the game is paused, and goes faster when in fast-forward. Probably not a big deal, as that's what I'd expect from any game using time as a unit.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by TrueBrain** [comment]
Thanks a lot for splitting up the PR; much easier to review like that :D

I have no code-wise comments, just a practical one: should we convert the settings when loading the first time after this PR? I believe we have a version-number in the config file, and I believe there is already some boilerplate to do these kind of things .. might be nice? Otherwise people all of a sudden see their AIs start a lot faster than they expect?

**Comment by 2TallTyler** [comment]
Yes, although I'll need some help figuring out how to change AI settings without crashing while starting the game. 🙂 The latest commit shows what I tried.

**Comment by 2TallTyler** [comment]
As discussed on Discord, setting conversion will wait for you or @glx22 to change the start date from a per-AI config setting to a global setting. Then we can merge that PR and this one at the same time to avoid having to do any setting conversion, since nobody will have a chance to generate a config file with the old values. 😄

**Comment by LC-Zorg** [comment]
This setting by seconds will be visible when the player selects a pace other than 100%, or it will be always like this?

**Comment by 2TallTyler** [comment]
Superseded by #10653.

**Pull request closed without merging**
