### PR TITLE
Fix #8162: Improve Error Message When Converting Town Owned Road

### LINKED ISSUE #8162: Converting town-owned road returns ambiguous/unhelpful error message
## Version of OpenTTD
master-20200509 (since NotRoadTypes was merged)

## Expected result
The error message returned is something like "owned by {TOWN}" (`STR_ERROR_OWNED_BY`).

## Actual result
The error message returned is "incompatible road" (`STR_ERROR_INCOMPATIBLE_ROAD`).

## Steps to reproduce
1. Load a roadtype NewGRF.
2. Start a new game.
3. Attempt to convert the road type to something else for a town-owned road.

## Note
The following appear to be the only two unique occurences of the error message. They were both added in the NRT branch.
https://github.com/OpenTTD/OpenTTD/blob/b8a896d52cdb9e2423b5fd745cc3d72d1ce7e09d/src/road_cmd.cpp#L2398
https://github.com/OpenTTD/OpenTTD/blob/b8a896d52cdb9e2423b5fd745cc3d72d1ce7e09d/src/road_cmd.cpp#L2444

If both are removed, then the error message may also need to be removed as well as it would no longer be used.

### PR DESCRIPTION
**Pull request by TrevorShelton**
This changes the error when you attempt to convert a road owned by a town to another road, specifying that it's owned by the town rather than simply being incompatible. As the original poster of the issue pointed out, these seemed to be the only occurences of the incompatible road string, so now it's unused, but they would be left untouched in case of future use or since changing it to a different error would do the work of removing it then. If requested, it likely wouldn't be too difficult to remove the string entirely.

### CODE REVIEW

**Comment by LordAro** [comment]
Unused strings should be removed (in a separate commit, to keep changes clean)

I'd consider a different (title) message for the commit as well - the abbreviations don't look great. "Fix #8162: Improve error message when converting town owned road", perhaps.

**Comment by TrevorShelton** [comment]
Alright, changed the title to that.

**Comment by nielsmh** [comment]
Please just remove the old string from all the language files at once, instead of one file/one commit at a time.

**Comment by TrevorShelton** [comment]
Oh, sorry, didn't come back to read this until I was done erasing it from all of the files. Is there a way to merge these or do I have to go back and use something else to do the erasure? (Sorry, fairly new to github commits.)

**Comment by LordAro** [comment]
Yes... Using the GitHub web interface isn't the greatest normally, and especially not when you have to edit multiple files. Get a local checkout, and edit the files there.

https://guides.github.com/introduction/git-handbook/
https://help.github.com/en/github/using-git/about-git-rebase

**Review by LordAro — APPROVED** [review]

**Pull request merged**
