### PR TITLE
Automatic save when losing connection to a network game

### PR DESCRIPTION
**Pull request by nielsmh**
A basic fixed-name autosave that triggers when a client loses connection to a network server.

### CODE REVIEW

**Comment by stavrossk** [comment]
How is this used? Will my game restore if I load the autosave?

**Comment by nielsmh** [comment]
It can't reconnect you to the network game, but it can be used to resume it as a single-player game. The original request ticket #986 talks about some more potential use cases.

**Comment by stavrossk** [comment]
@nielsmh Great feature, thanks!

**Comment by PeterN** [comment]
What conditions cause a netsave? I tried simply running a server and shutting it down, but no netsave was created.

**Comment by nielsmh** [comment]
@PeterN I only tested/developed for actual error situations, the tests I did myself were: Kill server process (instant connection reset), suspend server process for 20 seconds (client drops connection due to timeout), suspend client process for a while (when resumed, client is too far behind server to catch up and drops connection).

The original ticket does talk about server shutdown and game resets so those cases probably ought to be handled as well.

**Comment by nielsmh** [comment]
Updated to also perform the save when the server shuts down or restarts with a new world.

Right now it's controlled by a single setting that's not exposed in the GUI. I imagine most people will just want to leave it on, but should it have a GUI, and should save on network error and save on server shutdown be separate settings?

**Review by michicc — APPROVED** [review]

**Pull request merged**
