### PR TITLE
Change: Treat extended waypoint classes as 'WAYP' class.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Authors have asked for more custom waypoint classes, as lumping all waypoints into just one class gives a very big list.

My plan on the easiest way to achieve this is to treat all classes with the MSB as 0xFF as a waypoint class.

WIth #12595, this is almost implemented. However, to use the feature requires support from NewGRFs, and if they add this support then they will not work properly in 14.x

## Description

So this PR is intended to provide a little "forward-compatibility" for 14.x, by translating new waypoint classes to the standard 'WAYP' class.

This maps the extended custom waypoint clases (where the first byte of the label is 0xFF) to the standard 'WAYP' label, allowing use of them before the feature exists.

## Limitations

This also assumes that more-waypoint-classes plan with 0xFF as MSB is reasonable.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by bootmii** [comment]
I feel like this isn't the best time to do this, and I'd prefer this to be in 14.2 over 14.1. But I trust @PeterN's judgment. I'm sorry I was rude to you and called this PR "stupid".

**Comment by 2TallTyler** [comment]
To clarify the "why" a bit from our Discord discussion:

The purpose of this future-proofing is to allow GRF authors to make waypoints that have classes, which show up in classes in nightlies (and eventually 15.0+), but also work in older versions of OpenTTD like 14.1. That way, they can make classes without having to wait a whole year for the next release.

I very much like the idea, but let's not hold up 14.1 while we decide on this. We can ship a 14.2 if we decide to do this.

**Comment by rubidium42** [comment]
I guess this requires retargetting the 14 branch now.

**Comment by PeterN** [comment]
Probably, a backport from master would need 1) changing for 14.x and 2) reverting again.

**Review by rubidium42 — APPROVED** [review]

**Comment by PeterN** [comment]
Seems a bit pointless at this point.

**Pull request closed without merging**
