### PR TITLE
Fix #6233: Improve lock pricing and infrastructure counting, to achieve better consistency

### LINKED ISSUE #6233: Lock price for when built on sloped river and bare land tiles
**_Samu_ opened the ticket and wrote:**

> This is a patch that attempts to fix two things:
> 
> 1 - Pricing calculations for building locks on a sloped river tile, without taking into account the cost for clearing a river tile.
> 2 - Pricing calculations for building and demolishing locks on a sloped bare land tile, taking into account the cost for building, demolishing and maintaining a canal tile. This canal tile isn't actually built or demolished, but its associated costs are simulated, much in the sense to mimic what happens on the upper and lower tiles of a lock. Objective here is to achieve pricing consistency.
> 
> 
> Why do I think this patch is needed:
> 
> 1 - First issue doesn't become apparent when using default prices without the help of a NewGRF. I used BaseCostsMod 5.0 to expose the problem more clearly. The issue becomes apparent when the parameter setting "build canal, also affects 'canal maintenance'" is set to a much lower value. I used 1/8 for my testings.
> 
> 2 - Second issue is actually more like an "opinionated fix", to maintaining a consistent pricing scheme. If the value for building a canal was instead so blatantly much higher than the cost for building a lock itself, the flaw would become exposed: building several locks in a row would be cheaper than building a single contiguous canal line.
> 
> Refer - #4711
> http://dev.openttdcoop.org/projects/basecosts

**Attachments**
- [lock pricing adjustments.patch](https://bugs.openttd.org/task/6233/getfile/10133/lock+pricing+adjustments.patch) (4.27 KiB)

**Reported version**: _1.5.0-beta1_
**Operating system**: _All_

---

### PR DESCRIPTION
**Pull request by SamuXarick**
When building lock:
- don't add the cost for clearing river
- if not building on a river, simulate canal build price and add it to the landscape clearing cost
- if not building on a river, simulate canal maintenance count

When removing lock:
- if it was not built on a river, simulate the cost for clearing a canal tile and add it to the cost for clearing the lock itself
- if it was not built on a river, subtract canal maintenance count

When transfering ownership:
- old owner: subtract canal maintenance count if it was not built on a river
- new owner: simulate canal maintenance count if it was not built on a river

After loading a savegame:
- simulate canal maintenance count if it was not built on a river

### CODE REVIEW

**Comment by frosch123** [comment]
This seems to do multiple things:
* Change how locks are counted as infrastructure.
* Change construction checks of locks by not checking the clear-result in case of IsWaterTile.
* Change cost of building/clearing locks.

I do not agree with the new counting of infrastructure. The old one made more sense to me.

I am unsure whether the clear-check can fail for IsWaterTile.

I do not quite understand the intention of the cost change. I guess there are different ideas of what is part of a lock.
However, the diff seems to make construction of locks on rivers cheaper, which does not make much sense to me. I would expect the reverse.

**Comment by nielsmh** [comment]
Conceptually, a river should not be able to support a lock by itself. Building a lock on a river should entail effectively converting the river to a canal on those tiles. So, thumbs down from me.

**Comment by SamuXarick** [comment]
For consistency!

When building a canal on a river, it doesn't include the cost for clearing river. When building a ship depot on a river, it doesn't include the cost for clearing river. Even the north and south parts of a lock don't include the cost for clearing river. The watered part of a dock doesn't include the cost of clearing river either. So it would also make sense to make the middle tile of a lock to not include the cost of clearing the river.

As for simulating canal price and canal count… This canal tile isn't actually built or demolished, but its associated costs are simulated, much in the sense to mimic what happens on the upper and lower tiles of a lock. Objective here is to achieve pricing consistency, but mostly to fix a flaw that can be exposed using BaseCostsMod 5.0 as I reported in #6233.

If the value for building a canal was instead so blatantly much higher than the cost for building a lock itself, the flaw would become exposed: building several locks in a row would be cheaper than building a single contiguous canal line.

**Comment by TrueBrain** [comment]
We recently switched from Jenkins as CI to Azure Pipelines as CI. This means you need to rebase before this Pull Request will pass its checks. Sorry for the troubles!

**Comment by andythenorth** [comment]
Per Frosch's review, this won't be accepted as a change, both conceptually, and in the way it's implemented.  Thanks for contributing!

**Pull request closed without merging**
