### PR TITLE
Feature: Added Spanish town names

### PR DESCRIPTION
**Pull request by rasputino**
I added Spanish (from Spain) town names with its own town name generator. I did the differentiation of Latinamerican and Spanish cities.

2020-05-14 11_03_27-Window

### CODE REVIEW

**Comment by James103** [comment]
Commit message format needs to be followed, since otherwise commit checker has failed.

**Comment by rasputino** [comment]
I'll fix the problems and try again

**Comment by LordAro** [comment]
This pull request will do fine - just needs some [rebasing](https://help.github.com/en/github/using-git/about-git-rebase)

**Comment by nielsmh** [comment]
Shouldn't this be a NewGRF town name set?

**Comment by planetmaker** [comment]
> Shouldn't this be a NewGRF town name set?

I'm also strongly in favour of the NewGRF approach. The integrated townname lists are somewhat deprecated for a decade.

**Comment by rasputino** [comment]
> 
> 
> This pull request will do fine - just needs some [rebasing](https://help.github.com/en/github/using-git/about-git-rebase)

Could you help me with some tips? thanks

**Comment by rasputino** [comment]
> 
> 
> Shouldn't this be a NewGRF town name set?

There is one, but has no MakeTownGenerator

**Comment by glx22** [comment]
PRs should be based on `master`, not on release branches

**Comment by LordAro** [comment]
Didn't even spot that the first time round. You can't fix that from this PR, so closing. Also see the above comments - we're generally opposed to adding further town name generators (they're old and creaky and should be extended using NewGRFs instead)

**Comment by James103** [comment]
> we're generally opposed to adding further town name generators (they're old and creaky and should be extended using NewGRFs instead

Will all the existing town name generators (except for a fallback one) eventually be converted to NewGRFs that are shipped with the base game? This could even apply to old save games - just load the NewGRF that corresponds to the town name generator used in the savegame.

**Comment by rasputino** [comment]
> 
> 
> PRs should be based on `master`, not on release branches

Thanks, I didn't know it

**Comment by rasputino** [comment]
> 
> 
> Didn't even spot that the first time round. You can't fix that from this PR, so closing. Also see the above comments - we're generally opposed to adding further town name generators (they're old and creaky and should be extended using NewGRFs instead)

The problem is that is surprising to find Catalan town names and not Spanish town names. Catalunya is just a region of Spain, thus from my point of view, Catalan town names should be replaced by Spanish town names or just add the Spanish town names.

**Comment by Yexo** [comment]
The Catalan town name generator was the last town generator added directly to OpenTTD in August 2006. I'm not going to bother find exactly when NewGRF support for new town names was added, but I suspect that was shortly afterwards (definitely before 2008).

>Catalan town names should be replaced by Spanish town names

That'll break existing savegames.

>or just add the Spanish town names.

That's your goal, but not an argument in itself.

The list of hardcoded town name generators is a historical artifact from before the NewGRF approach was finished (or even started). At this point we're simply not accepting any new hardcoded town name generators. There is a perfectly fine alternative: write a NewGRF that generates the town names you want (and make it available via the online content service).

>Will all the existing town name generators (except for a fallback one) eventually be converted to NewGRFs that are shipped with the base game? This could even apply to old save games - just load the NewGRF that corresponds to the town name generator used in the savegame.

While this might be theoretically possible, it's definitely going to be hard to do without changing town names in existing savegames. There doesn't seem to be a large advantage to doing so: it's basically a lot of work for very little benefit. If you or someone else wants to take this on, feel free to try, but please discuss you approach first (not here, rather on IRC/new issue/forums).

**Pull request closed without merging**
