### PR TITLE
Change: Use selected group as parent when creating a new group.

### PR DESCRIPTION
**Pull request by PeterN**

### CODE REVIEW

**Review by nielsmh — APPROVED** [review]
Looks like it works as intended. The livery copying looks a bit strange to me (I'd expect it to inherit rather than copy) but I trust PeterN to extend his own code in the most appropriate way.

**Comment by J0anJosep** [comment]
Great idea. I also expected to inherit liveries instead of copying them.

**Comment by PeterN** [comment]
Inheritance is set by the in_use flag, in the case of inheritance colour1/colour2 are set to the parent. This is because when using 2cc mode, the two colours can actually inherit from different parent groups independently, but GetEngineLivery returns a Livery struct, not two colours.

When changing a parent livery, PropagateChildLivery() applies that change to all the group's children recursively.

Turns out there's some left over code in GetEngineLivery that traverses parents when it's not actually necessary. Oops.

**Comment by PeterN** [comment]
Okay, I think it should check the group ID exists and return an error if not, instead of silently creating a top-level group. Going to fix it :-)

EDIT: Other functions also do it this way, so for consistency I'll leave this as is and then change them all together, possibly.

**Pull request merged**
