### PR TITLE
Fix: [AdminPort] #12411 Send Network Welcome Packet to admin port after game creation completed

### LINKED ISSUE #12411: [Bug]: Admin packet SERVER_WELCOME can send UINT32_MAX as seed
### Version of OpenTTD

13.4, 14.0-RC3, g9954187680, windows, linux

### Expected result

after a newgame is started, the actual game seed should be sent, not the GENERATE_NEW_SEED. Seems the new seed is updated to late.

### Actual result

this is the log of my admin-bot :
regular start of the bot, it get both packets and the game seed :
```
20240402 121219 S3(1):server_do_packet Admin_Packet_ServerProtocol
20240402 121219 S3(1):server_do_packet Protocol 3
20240402 121219 S3(1):server_do_packet Admin_Packet_Server_Welcome
20240402 121219 S3(1):server_do_packet Welcome name OpenTTD France version 20240331-master-g9954187680 dedicated 1
20240402 121219 S3(1):server_do_packet Welcome gameseed 1012292036 startingyear 730485 landscape 2 map 512*512
20240402 121219 S3(1):server_game_new with gameseed 1012292036
```

newgame on the console

```
20240402 121330 S3(1):New game 183, 1012292036
20240402 121330 S3(1):server_game_close 183
20240402 121330 S3(1):server_game_close closing companies from game 183
20240402 121330 S3(1):server_game_close closing clients 1
20240402 121330 S3(1):server_game_close closing game into database 183
...
20240402 121334 S3(1):server_do_packet Admin_Packet_Server_Welcome
20240402 121334 S3(1):server_do_packet Welcome name OpenTTD France version 20240331-master-g9954187680 dedicated 1
20240402 121334 S3(1):server_do_packet Welcome gameseed 4294967295 startingyear 730485 landscape 2 map 512*512
20240402 121334 S3(1):server_game_new with gameseed 4294967295
```

The game seed received is GENERATE_NEW_SEED value. Dont know what to do with this.

### Steps to reproduce

Start a dedicated server with admin port setup properly
connect the bot to the admin-port
receive packet protocol and welcome
launch a newgame on the console or wait for an automatic newgame
check the generation seed in the welcome packet. The value is UINT32_MAX, not the real generation seed.

### PR DESCRIPTION
**Pull request by MuxyDuGoulp**
## Motivation / Problem
ADMIN_PACKET_SERVER_WELCOME is sent too early when a newgame is issued with an external bot already connected through AdminPort.

See #12411.

## Description
Move the sending of the packet to a better appropriate place when the game creation is over : `NetworkOnGameStart`

Closes #12411.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested') : **No**
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md) : **No**
* This PR affects the save game format? (label 'savegame upgrade') : **No**
* This PR affects the GS/AI API? (label 'needs review: Script API') : **No**
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF') : **No**
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by 2TallTyler** [comment]
Thanks for this. Please use the PR template that was prefilled in the form, it's there for a reason. 😉 

To link the issue, you can write `Fixes #12411`.

**Comment by rubidium42** [comment]
I think the content of the new function should become part of `NetworkOnGameStart`.

**Comment by MuxyDuGoulp** [comment]
where can i find the PR template ?

**Comment by rubidium42** [comment]
> where can i find the PR template ?

https://github.com/OpenTTD/OpenTTD/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1

Furthermore please rebase instead of merge master into this branch. See https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md for more information. As long as there are no merge conflicts, you do not need to rebase/update your branch for every change that reached master.

**Comment by MuxyDuGoulp** [comment]
Initial comment updated according to template.

**Comment by 2TallTyler** [comment]
Great, thank you.

Now you will have to squash all your `Merge branch 'master' into master` commits using an [interactive rebase](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec), or our automated checks won't allow this PR to be merged. 🙂

**Comment by MuxyDuGoulp** [comment]
not sure all is fine :[

**Comment by 2TallTyler** [comment]
Since this is such a simple code change, you might want to start over with Git. 😉 

First, you will need to use the command line interface for GitHub — using the web interface is not powerful enough, and neither was GitHub Desktop last I tried it. If you are not doing this already, here are the [instructions to set it up for OpenTTD](https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md#pull-requests).

You will need to reset your master branch and then create a branch for this feature.

1. Fetch the latest version of OpenTTD master branch with `git fetch upstream`
2. Reset your master branch with `git reset --hard upstream/master`
3. Create a new branch "welcome-packet" for this feature with `git checkout -b welcome-packet`
4. Make your code changes and commit normally. You will need to open a new PR, since you'll be merging from a different branch (welcome-packet, as opposed to master).

**Comment by MuxyDuGoulp** [comment]
made some cleaning
made a fork in my GitHub account
clone my OpenTTD Repo on my local PC (windows) using Tortoise Git
create a branch and swtich to it
made the changes
launch a full build
commit and push
from my GitHub account, detected the changes, create a new PR
when the PR will be accepted and merged, what should i do with the branch (delete ?) ?

**Pull request closed without merging**
