### PR TITLE
Backport master into release/13

### PR DESCRIPTION
**Pull request by rubidium42**
## Description
Note: quite a few manual interventions were needed regarding the script/ai/gs changes, so that might warrant some extra checking.

Backport of all closed Pull Requests labeled as 'backport requested' into `release/13`.
- https://github.com/OpenTTD/OpenTTD/pull/10399
- https://github.com/OpenTTD/OpenTTD/pull/10451
- https://github.com/OpenTTD/OpenTTD/pull/10462
- https://github.com/OpenTTD/OpenTTD/pull/10466
- https://github.com/OpenTTD/OpenTTD/pull/10488
- https://github.com/OpenTTD/OpenTTD/pull/10487
- https://github.com/OpenTTD/OpenTTD/pull/10489
- https://github.com/OpenTTD/OpenTTD/pull/10444
- https://github.com/OpenTTD/OpenTTD/pull/10496
- https://github.com/OpenTTD/OpenTTD/pull/10507
- https://github.com/OpenTTD/OpenTTD/pull/10471
- https://github.com/OpenTTD/OpenTTD/pull/10513
- https://github.com/OpenTTD/OpenTTD/pull/10535
- https://github.com/OpenTTD/OpenTTD/pull/10551
- https://github.com/OpenTTD/OpenTTD/pull/10555
- https://github.com/OpenTTD/OpenTTD/pull/10572
- https://github.com/OpenTTD/OpenTTD/pull/10573
- All language changes

### CODE REVIEW

**Comment by glx22** [comment]
I know I marked ScriptText changes to be backported, but the validation breaks existing GS.

**Comment by rubidium42** [comment]
> I know I marked ScriptText changes to be backported, but the validation breaks existing GS.

Hmm... not sure whether we want to do that in a point release.

**Comment by glx22** [comment]
So I removed the label from the 2 ScriptText PRs. This PR needs to be updated to remove the 7 related commits.

**Comment by rubidium42** [comment]
> So I removed the label from the 2 ScriptText PRs (#10492 and #10545). This PR needs to be updated to remove the 7 related commits. Also added the label to #10507 and #10535.

Updated the PR with those removals and additions.

**Review by michicc — APPROVED** [review]
Not idea if that is all that should be backported, but let's start somewhere.

**Pull request merged**
