### PR TITLE
Codechange: Remove assert when trying to intersect two tile areas and…

### PR DESCRIPTION
**Pull request by J0anJosep**
… one of them is empty.

### CODE REVIEW

**Comment by PeterN** [comment]
When would this assert trigger currently?

**Comment by J0anJosep** [comment]
On master, it doesn't. I think it doesn't make sense the first TileArea may be empty and the second one can't be empty. I find it strange. Moreover, part of the assert and its previous line are kind of redundant.

The assert was added in r18726, where the intersection of TileAreas is used for GetProductionAroundTiles. The TileAreas of industries aren't empty. So the assert would only be triggered if the location of an industry has no tiles (that doesn't happen right now: industries have at least one tile).

Anyway, I would like to intersect TileAreas where one of them may be empty (like the area of a station when its last tile is removed).

**Comment by LordAro** [comment]
I'm not a fan of this PR as it stands - it's just a single codechange for no clear benefit.

I'm also not sure when it could trigger either - there was already a check for 0-width TileAreas, and I don't see when a TileArea with height but not width could be used
Personally I think both height and width should have asserts on them - a TileArea with a 0 dimension doesn't make any sense to me at all, kind of like dividing by 0

**Comment by nielsmh** [comment]
An empty tile area would usually be indicative of a bug, I think. The real problem would be if you could remote crash a server by sending it a (forged) command that causes it to intersect an empty tile area, I'm not sure if that's possible.

**Comment by J0anJosep** [comment]
Stupid and non-sense and wrong commit. Closing.

**Pull request closed without merging**
