### PR TITLE
Feature: Added Spanish town names

### PR DESCRIPTION
**Pull request by rasputino**
I added Spanish (from Spain) town names with its own town name generator. I did the differentiation of Latinamerican and Spanish cities.

I think I fixed the validation problems from the last PR.

I know that you're generally opposed to adding further town name generators instead a NewGRFs. But I think is important to reflect in the program a big country like Spain as a default option like many others town name generators.

2020-05-14 11_03_27-Window

### CODE REVIEW

**Comment by James103** [comment]
It is not recommended to PR from the `master` (or other default) branch of your repository. Instead, you should create a branch in your repository, move the changes there, and then open a pull request.

**Comment by rasputino** [comment]
> 
> 
> It is not recommended to PR from the `master` (or other default) branch of your repository. Instead, you should create a branch in your repository, move the changes there, and then open a pull request.

Ok, I'll do it in that way next time. Thanks for your advice

**Comment by telk5093** [comment]
As I know, adding a new town names is highly not recommended currently. Why don't you make a NewGRF? And plus, you should not modify each language files. It should be done at Eints by each language's translators.

**Comment by nielsmh** [comment]
Make a NewGRF. New built-in town name generators are not accepted because they can not be versioned the same way a NewGRF town name set can be. Changes to the existing built-in town name generators can only be typographic in nature and they have a higher maintenance cost.

The BaNaNaS content service does not forbid having multiple "competing" entries that represent the same thing, even if there is already a Spanish town names set, you are free to upload a new, distinct one if you think you can do better.

**Pull request closed without merging**
