### PR TITLE
Minor sprite aligner enhancements

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Using the debug sprite aligner tool does not give very useful feedback on what is happening when aligning a sprite.

## Description

This PR adds two buttons:

- **Centre sprite** toggles whether the sprite should be either centred within the panel, or drawn with the offset centred. This has the effect of reversing the visual operation of the nudge buttons, although their action doesn't change.
- **Crosshair** toggles drawing a dotted crosshair at the sprite offset. This makes the offset clearly visible and so requires less fiddling with relative adjustments.

image

The wording and position of the buttons isn't all that great to be honest, but putting them there did mean that the window didn't need to be rearranged.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Changed wording to make it not look like and action, and also improved the layout of the list.

image

**Comment by PeterN** [comment]
Millions of force-pushes to satisfy the CI string linter :)

**Review by 2TallTyler — COMMENTED** [review]
I'm not sure the Offset/Sprite centred button should be be lowered depending on its setting. That implies an on/off toggle, not an A/B toggle. I could be easily convinced if there's a reason it's this way. 🙂

**Comment by PeterN** [comment]
True, it was originally a toggle, then I decided to make it clearer with the text changing instead. I'll change it.

**Comment by PeterN** [comment]
Hmm, actually that's how our buttons work, without it being lowered, the text wouldn't change. See the "Manual" / "Freeform" edges buttons on the terrain generator.

**Review by 2TallTyler — APPROVED** [review]
In that case, looks fine to me!

**Pull request merged**
