### PR TITLE
Add: A video driver that shows what areas of the screen are dirty.

### PR DESCRIPTION
**Pull request by techgeeknz**
This SDL-based video driver can be useful for debugging graphics routines.
It draws a dashed rectangle around all screen areas that have been marked dirty.

### CODE REVIEW

**Comment by techgeeknz** [comment]
Huh. The change to `CMakeLists.txt` somehow vanished when I `git stashed` :confused:

**Comment by LordAro** [comment]
Don't we already have this with "Toggle dirty blocks" in the about menu (or Ctrl+I) , or am I missing something obvious?

**Comment by techgeeknz** [comment]
> Don't we already have this with "Toggle dirty blocks" in the about menu (or Ctrl+I) , or am I missing something obvious?

I believe that is intended an end-user debugging feature for NewGRF authors. Specifically, it only marks the redrawn areas of viewports.

This works at a lower level, making it more useful for debugging and/or restructuring the graphics system.

**Comment by techgeeknz** [comment]
There doesn't seem to be a lot of interest in this; and I'm not entirely convinced that it's the best approach to the problem anyway. Closing.

**Pull request closed without merging**
