### PR TITLE
Add AI and GS to framerate window

### PR DESCRIPTION
**Pull request by nielsmh**
This can make the framerate window extremely tall, and it should maybe be made scrolling.

### CODE REVIEW

**Comment by PeterN** [comment]
`src/framerate_gui.cpp:495:9: warning: unused variable 'linecount' [-Wunused-variable]`

**Comment by PeterN** [comment]
As these happen in the game loop, and do affect the game loop total monitor, would it be possible to have these within sub-grouping of "scripts" in there, rather than appended to the end?

**Comment by nielsmh** [comment]
That's going to be really annoying :P Since the AIs are handled specially right now, with regard to strings.

**Comment by PeterN** [comment]
I think we're not meant to use snprintf:

src/safeguards.h:#define snprintf  SAFEGUARD_DO_NOT_USE_THIS_METHOD

I think seprintf() is our preferred call, this takes lastof() rather than lengthof()

**Comment by LordAro** [comment]
Should probably add safeguards.h in the relevant file.

Played around with it a bit, one suggestion - "AI n - {AI_NAME}" with the inclusion of the dash? I don't think the window is long enough that it's worth bothering about making it scroll

**Comment by SamuXarick** [comment]
wormai 2042-11-26
Hi. Can you make it 1-15 instead of 0-14? It would match the console 'companies' and other commands.

**Comment by nielsmh** [comment]
Okay I think that's most to-do items? Placed GS and AI under the Game loop heading, and fixed their numbering.
image

This may need testing to make sure everything is cleared/reset properly when the number of active scripts change, e.g. on game load, new game, and such.

**Comment by LordAro** [comment]
Would it be worth grouping all the AI/GS together with a "grand total" and having all the individual scripts nested underneath it?

**Comment by nielsmh** [comment]
Getting there...

**Comment by nielsmh** [comment]
I think this is everything.

The scripts total is a bit weird, since AIs not running every tick contribute less to the average, so the total can appear to be less than the simple sum.

**Comment by michicc** [comment]
Is this intended to be a squash or do you want to rebase/squash commits yourself?

**Comment by nielsmh** [comment]
This was initially intended to be a squash, but maybe it's worthwhile to separate commits for the AI/GS measurements and the resize/scroll behaviour?

**Comment by PeterN** [comment]
The scrolling does not work properly when clicking, you need to use `this->vscroll->GetScrolledRowFromWidget()` instead of `this->GetRowFromWidget()`.

**Review by PeterN — DISMISSED** [review]
Clicking to open a graph does not work properly with the scrolling; you need to use `this->vscroll->GetScrolledRowFromWidget()` instead of `this->GetRowFromWidget()`. Most windows have a local variable `this->vscroll` which is assigned in the constructor.

**Comment by nielsmh** [comment]
Squashed to two logical commits, should be ready for merge now.

**Review by PeterN — APPROVED** [review]

**Pull request merged**
