### PR TITLE
Add soundfont path for Flatpak

### LINKED ISSUE #6873: Jukebox not working in the flatpak version
A user of the flatpak version of OpenTTD reported an [issue](https://github.com/flathub/org.openttd.OpenTTD/issues/1) with the jukebox not playing any music. Indeed, the jukebox just keeps cycling through the original playlist without any playback.

Any ideas what could be causing this? How are the respective path to the individual tracks composing the playlist managed in the application?

### PR DESCRIPTION
**Pull request by ghisvail**
Closes #6873

### CODE REVIEW

**Comment by LordAro** [comment]
Incorrect commit message caused the CI failure - should start with `Add: ...`

But, I wonder whether flatpak is "notable" enough to be included in the default lookup list, as it is just a default - you can specify your own file with `./bin/openttd -m fluidsynth:soundfont=foobar`

**Comment by ghisvail** [comment]
> Incorrect commit message caused the CI failure - should start with `Add: ...`

Interesting.

> But, I wonder whether flatpak is "notable" enough to be included in the default lookup list,

Definition of _notable_ is subjective. Linux market share in the gaming space is below 1% according to the latest Steam survey, so not much _notable_ already. In addition, you've got fragmentation in the Linux distribution space with all these different distros, which may install stuff under different locations.

`Flatpak` provides a uniform medium of distribution and is supported by pretty much all the main family of distros today. In my opinion, it does not cost much to add a `Flatpak` specific entry to the search paths. The ideal solution would have been to enable injection of the soundfont path at build time via a configuration option...

> you can specify your own file with `./bin/openttd -m fluidsynth:soundfont=foobar`

...or at runtime via a command arg.

I wished I were advised about the existence of this feature back when I reported #6873  last year. Anyway.

Just for validation, this should work then:

`./bin/openttd -m fluidsynth:soundfont=/app/share/sounds/sf2/FluidR3_GM.sf2`

?

**Comment by PeterN** [comment]
Can you fix your commit message to comply with our commit checker requirements?

**Comment by LordAro** [comment]
Going to close this (and associated issue) as there's been no activity for 3 months, and it looks like there's an alternative solution anyway

**Pull request closed without merging**
