### PR TITLE
Change: [NPF] Add path cache for ships.

### PR DESCRIPTION
**Pull request by J0anJosep**
Trying to extend cached paths to ships and NPF.

I know const_cast is not a good way of doing it, but I don't have time to remove it now. If it is necessary, maybe in a few weeks...

### CODE REVIEW

**Comment by PeterN** [comment]
Yes, const cast probably needs to go.

**Comment by J0anJosep** [comment]
const_cast removed
I am not satisfied with this solution either.

**Comment by PeterN** [comment]
Is this working? I'm not noticing any performance improvement.

EDIT: I think it's a difference in how no path found is handled between YAPF and NPF.

**Comment by J0anJosep** [comment]
If you provide a savegame, I will look into it.

**Pull request closed without merging**
