### PR TITLE
Improve MSVC ARM64 support

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by LordAro** [comment]
No issues with this in principle, but the commit message needs to be changed to fit with our [in-house style](https://wiki.openttd.org/Coding_style#Commit_message)

**Comment by janisozaur** [comment]
What do you suggest?

**Comment by LordAro** [comment]
Rebasing the branch to squash the commits together should work - https://help.github.com/en/github/using-git/about-git-rebase

**Comment by janisozaur** [comment]
I asked what commit message do you suggest?

**Comment by nielsmh** [comment]
`Codechange: Improve MSVC ARM64 support`

**Review by LordAro — APPROVED** [review]

**Pull request merged**
