### PR TITLE
Fix #6854: Compilation with ICU 62

### LINKED ISSUE #6854: Build failure with icu-62.1
```
g++ -Wall -Wno-multichar -Wsign-compare -Wundef -Wwrite-strings -Wpointer-arith -W -Wno-unused-parameter -Wredundant-decls -Wformat=2 -Wformat-security -Winit-self -fno-strict-aliasing -Wcast-qual -fno-strict-overflow -Wnon-virtual-dtor -Wno-free-nonheap-object -rdynamic -DUNIX -D_FORTIFY_SOURCE=2 -DWITH_SSE -DWITH_SDL  -D_REENTRANT -I/usr/include/SDL -DWITH_ZLIB   -DWITH_LZMA   -DWITH_XDG_BASEDIR   -D_SQ64 -I/var/tmp/portage/games-simulation/openttd-9999/work/openttd-9999/src/3rdparty/squirrel/include -DWITH_PNG -I/usr/include/libpng16  -DWITH_FONTCONFIG -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -DWITH_FREETYPE -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -DWITH_ICU_LAYOUT -I/usr/include/icu-le-hb -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -DWITH_ICU_SORT   -DWITH_ICONV -DHAVE_NON_CONST_ICONV -DENABLE_NETWORK -DWITH_PERSONAL_DIR -DPERSONAL_DIR=\".openttd\" -DGLOBAL_DATA_DIR=\"/usr/share/games/openttd\"  -I /var/tmp/portage/games-simulation/openttd-9999/work/openttd-9999/objs/release -I /var/tmp/portage/games-simulation/openttd-9999/work/openttd-9999/objs/lang -I /var/tmp/portage/games-simulation/openttd-9999/work/openttd-9999/objs/setting -flifetime-dse=1 -std=gnu++14 -march=native -mtune=native -O2 -pipe -c -o fontcache.o /var/tmp/portage/games-simulation/openttd-9999/work/openttd-9999/src/fontcache.cpp
<command-line>:0:0: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
In file included from /var/tmp/portage/games-simulation/openttd-9999/work/openttd-9999/src/fontcache.cpp:20:0:
/var/tmp/portage/games-simulation/openttd-9999/work/openttd-9999/src/gfx_layout.h:84:29: error: expected class-name before ‘{’ token
 class Font ICU_FONTINSTANCE {
                             ^
make[1]: *** [Makefile:228: fontcache.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/games-simulation/openttd-9999/work/openttd-9999/objs/release'
make: *** [Makefile:56: all] Error 1
```

**Version:** git HEAD
**Operating system:** Linux

### PR DESCRIPTION
**Pull request by steils**

### CODE REVIEW

**Review by LordAro — APPROVED** [review]

**Comment by matthijskooijman** [comment]
For future reference, this actually fixes the build with ICU 61 and up. See [the ICU 61 changelog](http://site.icu-project.org/download/61):

> C++ call sites need to qualify ICU types explicitly, for example icu::UnicodeString, or do using icu::UnicodeString; where appropriate. If your code relies on the "using namespace icu;" that used to be in unicode/uversion.h, then you need to update your code. (#13460)

**Comment by matthijskooijman** [comment]
Also note that this PR did not fix the problem completely, see #6690 and the fix in 19076c24c1f3baf2a22d1fa832d5688216cf54a3.

**Comment by LordAro** [comment]
Only #6693 was strictly necessary for 61(.1), as far as I'm aware

**Comment by matthijskooijman** [comment]
I believe it was more a matter of compilation options: All the things fixed by 19076c2 are inside `WITH_ICU_SORT`, whereas the fixes in #6693 are guarded by `WITH_ICU_LAYOUT`.

Doesn't matter much, though :-)

**Pull request merged**
