### PR TITLE
Feature: Group liveries, and livery window usability enhancements.

### PR DESCRIPTION
**Pull request by PeterN**
This PR add liveries to vehicle groups, and makes some usability changes to the livery selection window, replacing the checkbox enable/disable with a 'default' option in the colour drop down.

### CODE REVIEW

**Comment by nielsmh** [comment]
A PR like this ought to have some PR screenshots, I say.

**Comment by andythenorth** [comment]
> A PR like this ought to have some PR screenshots, I say.

You probably meant for the new UI features, not just train colours, right? 😛 

horse horsey liveries 4
horse horsey liveries 3
horse horsey liveries

**Comment by PeterN** [comment]
Thanks Andy. Didn't have time earlier to post screenshots.

**Comment by andythenorth** [comment]
Company Colour defaults are now set like this:

group-livery-default


For ungrouped trains, RVs etc, the long established (and weird imo) settings for some types of vehicle are kept.  Note however that the checkboxes are now removed, reducing UI friction:

group-livery-trains


Liveries for groups do not offer settings by types of vehicle, 1CC and 2CC will be applied consistently to all vehicles in the group:

group-livery-group

Results:

group-livery-results


Group livery UI can also be opened directly from the groups window, with the correct group selected:

group-livery-direct-access

**Comment by andythenorth** [comment]
Just 2 more 😛 

horse horsey liveries 8
horse horsey liveries 7

**Comment by J0anJosep** [comment]
Looks good. I tested it and works as expected. But please run script/api/generate_widget.sh.

Some questions:

- (unrelated to this PR) Could be "New Colour Scheme" window renamed to "Name of the company - Colour Scheme"? And could its title widget have the company color as other company-related windows?
- Group hierarchy isn't shown in the Colour Scheme Window. Could it be added?
- Can the colour of a parent group change the colour of all its descendants? In other words, can group hierarchy be used for colour schemes?
- Shouldn't new icons have a similar style to those on openttd.grf or OpenGFX?

**Comment by PeterN** [comment]
> Looks good. I tested it and works as expected. But please run script/api/generate_widget.sh.

Ah yes. We really ought to make this part of the build process!
> 
> Some questions:
> 
>     * (unrelated to this PR) Could be "New Colour Scheme" window renamed to "Name of the company - Colour Scheme"? And could its title widget have the company color as other company-related windows?
Hmm, sounds reasonable, although the title widget is already the company colour. EDIT Or not. Confused as I was testing something else and it was. EDIT And it is in master, just broken in this PR, wow.
>
>     * Group hierarchy isn't shown in the Colour Scheme Window. Could it be added?
Possibly depending on the next point.
> 
>     * Can the colour of a parent group change the colour of all its descendants? In other words, can group hierarchy be used for colour schemes?
This will change how setting a colour to 'Default' will work. Currently it means to fall back to the system of picking the colour based on the original liveries system. With hierarchy in place it would mean falling back to the parent scheme.
> 
>     * Shouldn't new icons have a similar style to those on openttd.grf or OpenGFX?
It's based on the extra OpenTTD GUI sprites that already exist, but there's no icon for 'choose colour'.

**Comment by andythenorth** [comment]
I would ship what we've got, and consider group hierarchy stuff later.  Some things need to be used in prod for a while to see what really needs changed / improved :)

Also group hierarchy might be a moving target, e.g. #6053 and #6189

**Review by nielsmh — DISMISSED** [review]
I will admit to not testing this myself, but the code looks sound, and others' testing indicates it works as intended.
Were the new sprites final?

**Comment by PeterN** [comment]
Another update as I had, again, forgotten to run generate_widgets

**Comment by J0anJosep** [comment]
> This will change how setting a colour to 'Default' will work. Currently it means to fall back to the system of picking the colour based on the original liveries system. With hierarchy in place it would mean falling back to the parent scheme.

Well, instead of "Default", it should be "Inherited". But it is more consistent to inherit colour from parents, the same way autoreplacements work.

> I would ship what we've got, and consider group hierarchy stuff later. Some things need to be used in prod for a while to see what really needs changed / improved :)

I think it is better to deal with this now for keeping commits to master in a better order.

**Comment by J0anJosep** [comment]
About icons, it is my fault. I thought those icons were based on non-free graphics instead of being based on OpenGFX. Probably, some static newGRF must have had replaced the ones in OpenGFX when I checked this.

**Comment by PeterN** [comment]
@nielsmh Unless someone wants to improve them, I think the icons are fine.

Current version now displays the group hierarchy so the list order is the same as the group window, but does not affect how colour is assigned.

There's a small discrepancy anyway that when 'Default' is selected it shows the main company colour, but vehicles may not be that colour if the type-based liveries are used.

**Comment by PeterN** [comment]
Group hierarchy is now followed for liveries.

**Comment by andythenorth** [comment]
Tested, works for me.  

I thought I had found an issue where default was sometimes wrong for 2CC, but can't repro.  Only saw it in a savegame with groups created in a previous version of patch, assuming it was stale data.

**Comment by planetmaker** [comment]
It compiles and looks good. Let's ship it ;)

**Review by planetmaker — APPROVED** [review]
As by the comment... let's ship it

**Pull request merged**
