### PR TITLE
Change: Make "middle" the default stopping location for trains in platforms

### PR DESCRIPTION
**Pull request by EmperorJake**
## Motivation / Problem

By default, trains stop at the far end of a platform. This is how it was always done since TTD, but it looks unsightly and unrealistic, especially if the station is a through station and the train is much shorter than the platform.
image

For a long time, this was the only option. Since stopping in the middle became an option, I and many other aesthetics-focused players have set it to that because it just looks better in most circumstances. This PR makes changes the default setting to the middle out of the box.
image

Additionally, with the recent changes in https://github.com/OpenTTD/OpenTTD/pull/11102, new players may be less likely to figure out that the stopping position can be changed at all. 

## Description
image

This PR makes "middle" the default stopping position for trains at platforms. This is good because the middle is generally the more popular position for anyone who wants to change the default stopping position (i.e. players who care about aesthetics) and it will not affect other players because the stopping position is functionally identical. It will benefit new/casual players by improving the visuals of the game by changing a setting which they would otherwise have not changed or known it existed.

It is also the behaviour in line with more modern games such as Transport Fever 2 (in which stopping position can't even be changed).

## Limitations

Some players might prefer the old way (but they can always change it back)

It's not how TTD did it (but that's hardly a precedent for not changing stuff)

Could mess up AIs which change stopping position (I have not tested this yet)

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
"Realistic" is not a very good argument. Plenty of real life stations don't have trains stop in the middle. I don't think stopping position is important at all, so I have no other input here.

**Review by 2TallTyler — DISMISSED** [review]
This is an inconsequential yet subjective change, which makes it hard to review. 😉 

I am approving this, of course it takes another developer to agree and click Merge. 🙂 

I want to explain my decision-making process.

### Arguments for:
- Existing players will not have their setting changed, because the old default (or their choice) is saved in their config file
- Some people (myself included) think it looks better
- With #11102 players might not know they can change this
- @EmperorJake is a longtime player and NewGRF author who understands how realism-focused players play OpenTTD
- We should encourage PRs from new contributors, and remember that "scratching a personal itch" is often the gateway to many more contributions

### Arguments against:
- TTD didn't have the setting
- Some people might think the old default looked better and make a PR to change it back
- With #11102 players might not know they can change this (yes, this is in both categories 🙂)

### Non-arguments:
- AIs set stop position using a StopLocation enum and are already subject to the player's choice, so they'll be fine (or are already broken)

**Review by 2TallTyler — APPROVED** [review]

**Comment by TrueBrain** [comment]
Survey says ... well, with JGRPP over 50% has it to `middle`. Despite that not being the default. That are a lot of people who like that play-style :)

And I also fancy it myself more. Enough reasons to flip the switch if you ask me :)

**Comment by 2TallTyler** [comment]
I love the new survey. 😄

**Pull request merged**
