### PR TITLE
Add: Currency:  Indonesian Rupiah (IDR)

### PR DESCRIPTION
**Pull request by WilloIzCitron**
Adds a Currency of indonesia
With conversion rate of 19 to GBP.

### CODE REVIEW

**Comment by WilloIzCitron** [comment]
im lazy of commit naming smh

**Comment by ldpl** [comment]
Because of such a high conversion rate, this actually needs careful consideration and excessive testing. As most calculations are done in 64 bit types these eye-candy conversion rates eat up bits from useful values and this one just uses 2 more bits than everything else. And I remember there already being some issues with overflowing money, not sure if they were all fixed. It's also quite bad for the UI to have all those pointless numbers at the end. So I think it would be much better from both UI and implementation pov to add such currencies in thousands, so this one would be a "thousand rupiahs" currency with the conversion rate of 19.

**Comment by WilloIzCitron** [comment]
> Because of such a high conversion rate, this actually needs careful consideration and excessive testing. As most calculations are done in 64 bit types these eye-candy conversion rates eat up bits from useful values and this one just uses 2 more bits than everything else. And I remember there already being some issues with overflowing money, not sure if they were all fixed. It's also quite bad for the UI to have all those pointless numbers at the end. So I think it would be much better from both UI and implementation pov to add such currencies in thousands, so this one would be a "thousand rupiahs" currency with the conversion rate of 19.

ok imma fix it

**Comment by Wuzzy2** [comment]
> Because of such a high conversion rate, this actually needs careful consideration and excessive testing.

FYI: Everyone can already test this by using the manual currency and setting the max value. I think I'm going to play with such a fantasy currency from now on. I'll report back (in other issues) if I find any bugs.

About the "thausand rupees" thing: Shouldn't the suffix change then, or is this intended?

**Review by TrueBrain — APPROVED** [review]
I am not the biggest fan of using 19 instead of 19k, but I understand the other side of this problem. So why not.

**Pull request merged**
