### PR TITLE
Add: LSB_RELEASE_ID Linuxmint to .deb package

### PR DESCRIPTION
**Pull request by TopherLee513**
## Motivation / Problem

When compiling on Linux Mint for "Release" build type, CMake warns Mint is an "unknown" distro and asks CPack to package as "TXZ".

This commit adds Linux Mint to the Debian/Ubuntu line so that CPack will create a .deb package file.

## Description

Building for build type "Release" on Linux Mint will build a .deb package like it does for Debian and Ubuntu.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by TopherLee513** [comment]
Okay. I meant to update my fork of the 'master' branch after fixing the caps, oops... I'm not _exactly_ sure how to do the rebase and force-push it because I'm still a Git-Noob, but I'll figure it out. Thanks for your help.

**Comment by 2TallTyler** [comment]
If you're using git from the command line, you can start an interactive rebase with `git rebase -i HEAD~2` where `-i` asks for an interactive rebase in your default text editor, and `HEAD~2` means starting with the current head of your branch, and going back two commits. The text editor that opens gives instructions for what you can do with these commits, in this case a `reword` of your first commit.

I don't recall exactly how to get rid of a merge commit...you might just `drop` it, finish the rebase by saving the text file and closing it, and then rebasing your branch on master with `git rebase upstream/master` (assuming you've followed the instructions to set the remote upstream in https://github.com/OpenTTD/OpenTTD/blob/master/CONTRIBUTING.md). This type of rebase is not interactive, it just puts your commits atop upstream/master. You can always do `git log` to see your history (and `q` to quit the log).

Once you're happy, do `git push -f` to force-push to your remote, which will update this PR. Feel free to ask here or on Discord if you have any trouble!

**Comment by 2TallTyler** [comment]
Per @PeterN on Discord, `git reset HEAD~1` will undo the merge commit.

**Comment by TopherLee513** [comment]
Okay, I think I did this correctly... Let me know if I missed something and thank you (and Peter) so much.

**Comment by 2TallTyler** [comment]
Nice! Git stuff looks correct to me. One other thing, is that you deleted the PR template that's supposed to guide you to explain to use why this change should be made (look at any other PR for an example). Perhaps you could fill that out to help us review this better?

**Comment by TopherLee513** [comment]
Oh, wow. Yeah, sorry. I was a bit overwhelmed with that part. Was hoping it would be pretty easy to review since it was just one line in one file that was amended and pretty self-explanatory. I'll do whatever needs to be done to be compliant though. Once I figure this part out, I'll get it done. I assume I just need to edit the first comment...?

**Comment by PeterN** [comment]
Yes, just edit the original 'comment' -- I've put the template back in to make it a bit easier for you :-)

**Comment by TopherLee513** [comment]
Well shucks, thank you. I hope it's all nifty now. :)

**Review by PeterN — APPROVED** [review]

**Pull request merged**
