### PR TITLE
Change: Don't show scoring year in high score table

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

The high score table has two modes:
* In multiplayer games, it only appears at the end of the game, and shows companies who reached the end of the game. The table only contains the game that just ended. 
* In single player games or in the main menu, it shows your personal high scores in single-player games. The table contains your previous scores from other games. 

In this second case, the end year of the games in this table can be different. Currently we draw `_settings_game.game_creation.ending_year`, not the actual end year of the game, which is not stored anywhere.

## Description

There are so many other variables to the high score — duration, start and end year, NewGRFs, AI competition, etc., that are not recorded either. Storing the year doesn't really mean anything.

Let's remove this meaningless year from the high score table.

For simplicity, we'll do the same with the multiplayer table.

Supersedes and closes #11545.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
But `_settings_game.game_creation.ending_year` is the actual ending year of the game. It is stored... in the game.

**Comment by PeterN** [comment]
Okay, so it may not be the ending year of the other scores in the list...

**Comment by 2TallTyler** [comment]
Right, and I keep my setting set to 0, so when I open the high score table from the main menu or from the main toolbar (in a singleplayer game), it says `Top companies who reached 0`, which makes no sense.

The only place you lose information is when a single-player game ends, but even then, the games in that table may not have reached the year you've selected...so it's even more wrong than not displaying any year.

**Comment by PeterN** [comment]
What is different about multiplayer games that makes you want to keep the year for them, but not for single player games?

That doesn't make much sense to me.

**Comment by rubidium42** [comment]
I'd just keep it really simple and just remove the year, also when ending the network game.
As to be super pedantic, you get the high score shown in `ending_year + 1`, so it's not even reaching the year but finishing the mentioned year.

**Comment by 2TallTyler** [comment]
Okay, now the year is removed entirely.

**Review by PeterN — APPROVED** [review]

**Pull request merged**
