### PR TITLE
Change: Company Colour Scheme layout changes.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Feedback from Company Colour Schemes window.

* Position of colour selection dropdowns make them look like filters instead of actions.
* Tooltip of vehicle group buttons are the same as the vehicle livery scheme buttons.
* "Standard Livery" doesn't mean much.
* Blank groups are empty.
* The window is larger than necessary due to SetMinimalSize()

image
image

## Description

* Move dropdowns to bottom of window, to match most other windows that have actions at the bottom.
* Add per-vehicle type tooltips for the group colour buttons.
* Rename to "Default Livery".
* Show text if selected vehicle type group is empty.
* Remove SetMinimalSize() where the widget dimensions are already calculated from text size.

image
image

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by TrueBrain — DISMISSED** [review]
"To show" gives me the suggestion they are there just not showing, but I fail to find better wording, so I guess it is also the best I can come up with :D

Awesome work btw, these improvements really help for a n00b like me :)

**Comment by 2TallTyler** [comment]
Closes #9784?

Also, not feedback that should block merging this -- but I wonder if a dropdown on each row would be more obvious than selecting a row and then changing it with the dropdown on the bottom of the window. Or maybe that would look too busy.

**Comment by EmperorJake** [comment]
The "no groups to show" string gets cut off in certain cases 
image

**Comment by PeterN** [comment]
image

Slight adjustment. Empty group text now ends with "are set up" rather than "to show", it's now black so that it's easier to read, and it spans the whole row instead of just the left column.

**Review by TrueBrain — APPROVED** [review]

**Pull request merged**
