### PR TITLE
Add: Option for a new transfer feeder payment algorithm

### PR DESCRIPTION
**Pull request by JGRennison**
The original algorithm pays intermediate legs in feeder systems based
on the start and end stations of that particular leg.
This tends to result in large negative payments on the final leg for
journeys with many feeder legs, as the overall feeder payment increases
with the number of legs, and the final leg is penalised for discrepancies
between the previous leg payments and the actual payment for delivery
from the source to the destination.
The feeder share setting is a partial mitigation, however it is difficult
to tune as a suitable value depends on the number of legs and the network
topology, which are often not the same for all vehicles.

The new incremental algorithm pays the cargo payment from the source
station to the end station of the current leg, minus any previous
transfer feeder payments for each leg.
This prevents unbounded increase of feeder payments and therefore avoids
the issue of excessive negative payments on the final leg.
Feeder payments may be negative, e.g. in the case of poorly performing
or highly indirect legs. This is better than penalising the final leg.
This mode reduces the need to tune the feeder shares setting to the
current network.

The feeder share setting applies in the existing way for both modes.

### CODE REVIEW

**Comment by ldpl** [comment]
Doesn't need an option IMO. If it works better just use it, not like anyone would miss an old algorithm. Those profits are virtual anyway.

**Comment by michicc** [comment]
Indeed, as the transfer payment only affects vehicle statistics and not the real company profits, a setting is superfluous.

Either it is better (by some metric) than current, then it can just replace it, or it is worse. And if it would be worse, adding it is pointless.

**Comment by JGRennison** [comment]
The setting has been removed, the savegame bump is no longer required.
The diff is now a bit shorter.

**Review by LordAro — APPROVED** [review]
Just a bit shorter

**Pull request merged**
