### PR TITLE
Fix: build with icu >= 76 where icu-i18n and icu-uc become separated

### PR DESCRIPTION
**Pull request by fundawang**
In icu >= 76, `icu-i18n` and `icu-uc` becomes separated libs, so we should link against `icu-uc` explicitly. 

Upstream changes:
https://github.com/unicode-org/icu/commit/199bc827021ffdb43b6579d68e5eecf54c7f6f56

### CODE REVIEW

**Comment by PeterN** [comment]
Thanks, could you please alter your commit so that our commit checker likes it? — simply change `fix` to `Fix:`

**Comment by fundawang** [comment]
> Thanks, could you please alter your commit so that our commit checker likes it? — simply change `fix` to `Fix:`

Well, it is quite difficult, as github cli is banned here, I can only use web editor to make changes :(

Go with any other ways as you can.

**Comment by WenSimEHRP** [comment]
You should also change your commit message.

```
git commit --amend -m "Fix: ..."
git push -f
```

**Comment by fundawang** [comment]
> You should also change your commit message.
> 
> ```
> git commit --amend -m "Fix: ..."
> git push -f
> ```
I know that. But I cannot access git cli here. I can only do this via web page.

**Comment by TrueBrain** [comment]
No worries, we can fix this for you.

More to the point of this change: will it be backwards compatible? Or will ICU from before 76 now fail? (as in, do we need to add a version-check whether to link to what?)

**Review by TrueBrain — APPROVED** [review]

**Comment by fundawang** [comment]
> More to the point of this change: will it be backwards compatible? Or will ICU from before 76 now fail? (as in, do we need to add a version-check whether to link to what?)

No, in the past (icu < 76), `icu-i18n` had a dependency of `icu-uc`, which means linking against `icu-i18n` will get `icu-uc` linked automatically. In icu >=76, `icu-i18n` and `icu-uc` become independent libraries, so link against `icu-uc` need to be listed explicitly.

**Pull request merged**
