### PR TITLE
Real hovercraft, refittable to eels

### PR DESCRIPTION
**Pull request by frosch123**
## Motivation / Problem
Trains have taken over the gameplay of OpenTTD. It's time for revenge.

## Description
In their endless fight against trains, road vehicles have finally found the hero they deserve: Hovercraft.

## Limitations
No warranties, may result in endless marketing campaigns.

### CODE REVIEW

**Comment by James103** [comment]
Should that apply only to certain ships (via a NewGRF flag of some sort)? Otherwise, I disagree.

**Comment by ldpl** [comment]
Fantastic change! I'm so excited for all the possibilities it opens up for otherwise useless boats! Can't wait till it gets merged.

**Comment by James103** [comment]
Like I said above, only certain ships (such as the default hovercraft) should be able to go on land, while other ships (such as the oil tankers and other heavy ships) are confined to water areas only.

**Comment by TrueBrain** [comment]
What if we draw a sailor on the deck of each ship poring water over the land? Does that sound like a compromise?

(sorry, I am trolling; that is not nice of me, and I take it back :( )

**Comment by TrueBrain** [comment]
Please take the Pull Request template more serious next time, this is not acceptable from a dev. *drops mic*. *out*.

<3

**Pull request closed without merging**
