### PR TITLE
Remove MorphOS / AmigaOS / BeOS support and libtimidity support

### PR DESCRIPTION
**Pull request by TrueBrain**
Every commit explains why that part is being removed. In summary:

If #7086 drops, MorphOS / AmigaOS are no longer supported, and BeOS is suggested to upgrade to Haiku.
libtimidity was a PSP only music driver, which we forgot to remove when we dropped PSP.
NDS is NintendoDS, which had some leftovers from whenever.

### CODE REVIEW

**Review by michicc — APPROVED** [review]

**Comment by mikrosk** [comment]
> If #7086 drops

If may I ask, does this mean that SDL1 support is on its way to be removed?

**Comment by LordAro** [comment]
Probably not any time soon, but since SDL2 is well established at this point, I wouldn't want to suggest that the SDL1 driver will be around forever

**Comment by nielsmh** [comment]
I wanted to keep the SDL1 driver as an alternative until we're sure the SDL2 driver is at least as good/reliable, it's probably staying around for at least one more year.

**Comment by mikrosk** [comment]
Thanks for reply, guys. I ask because I'm the mysterious author of the unofficial Atari port mentioned here: https://www.tt-forums.net/viewtopic.php?t=83077 ... and we rely on SDL1 quite heavily, there is no point of having SDL2 ported to our platform.

I know, I know, I should have ported it back to upstream, shame on me! If that move would motivate you to keep SDL1 support in OpenTTD, perhaps it's time I'll take a look at OpenTTD again. :)

**Pull request merged**
