### PR TITLE
Codechange: Use null pointer literal instead of the NULL macro

### PR DESCRIPTION
**Pull request by M3Henry**
Use of nullptr is preferential to the NULL macro since C++11.

This was done with a simple `sed`

```bash
find src/ -name '*.[hc]' | xargs sed -i -e 's/\bNULL\b/nullptr/g'
find src/ -name '*.[hc]pp' | xargs sed -i -e 's/\bNULL\b/nullptr/g'
```

### CODE REVIEW

**Comment by TrueBrain** [comment]
a) you killed my browser. Mean! :P
b) does this prevent using NULL in the future, or how are we going to do this? Only converting it is just begging for new NULLs to sneak in, and we have to repeat this every N days :D

**Comment by M3Henry** [comment]
NULL should not be allowed in new code after this.

**Comment by TrueBrain** [comment]
What I meant to say: any way to enforce that? Compiler-flag? Or do we need to add this to the commit-checker? :)

**Comment by Eddi-z** [comment]
`##[error]*** b/src/stdafx.h:180: Preprocessor hash is put into the first column, before the tab indentation: '	#pragma warning(disable: 6011)   // code analyzer: Dereferencing nullptr pointer 'pfGetAddrInfo': Lines: 995, 996, 998, 999, 1001'`

doesn't sound right

**Comment by TrueBrain** [comment]
> `##[error]*** b/src/stdafx.h:180: Preprocessor hash is put into the first column, before the tab indentation: '	#pragma warning(disable: 6011) // code analyzer: Dereferencing nullptr pointer 'pfGetAddrInfo': Lines: 995, 996, 998, 999, 1001'`
> 
> doesn't sound right

This is our commit checker being paranoid. It is a new style we enforce. But for these patches we might want to make an exception for them :) I would vote we just overrule its outcome.

**Comment by M3Henry** [comment]
I have a script which I run periodically to keep this PR up to date. Otherwise there's not much left to do on this one.
```bash
find . ! -path './3rdparty/*' -name '*.h' | xargs sed -i -e 's/\bNULL\b/nullptr/g'
find . ! -path './3rdparty/*' -name '*.[hc]pp' | xargs sed -i -e 's/\bNULL\b/nullptr/g'
sed -i -e 's/hIMC != nullptr/hIMC != NULL/' video/win32_v.cpp
```

**Comment by michicc** [comment]
You either should drop the comment change in stdafx.h or reformat the whole block to conform to the new coding style (`#<indent>pragma` instead of `<indent>#pragma`).

Alternatively, you find an admin to force a merge ignoring the commit-checker. I would merge, but I'm not an admin.

**Review by michicc — APPROVED** [review]

**Pull request merged**
