### PR TITLE
Fix building unless WITH_ASSERT

### PR DESCRIPTION
**Pull request by BeWorld2018**
Fix building unless WITH_ASSERT define

### CODE REVIEW

**Comment by LordAro** [comment]
I'm struggling to see what this solves. Can you please fill out the template and elaborate what problem you're solving? We already build with and without asserts...

**Comment by BeWorld2018** [comment]
For example, in tgp.cpp :  you just missing last assert(found):

https://github.com/OpenTTD/OpenTTD/blob/dd798d688b7e9ea6c7d4d01aea976dde5ec75f60/src/tgp.cpp#L657-L678

Context for me : i build OpenTTD on MorphOS system (PPC) and i use my own makefile and i dont use -DNDEBUG and -DWITH_ASSERT .. so here a problem.

Thanks

**Comment by LordAro** [comment]
Yeah... we do not support that. Why on Earth do you maintain your own makefile? As far as I can tell, cmake exists for MorphOS

**Comment by BeWorld2018** [comment]
> Yeah... we do not support that. Why on Earth do you maintain your own makefile? As far as I can tell, cmake exists for MorphOS

because cmake is not ideal on MorphOS... i dont use it (not last version.. missing a lot of things...).

ok i close issue and use DNDEBUG.
Thanks

**Comment by LordAro** [comment]
If it helps, we don't require the "newest" version of cmake - only 3.9+

**Pull request closed without merging**
