### PR TITLE
Fix: Restore original cargo legend 'blob' dimensions.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

"Fix" in the losest terms... An off-by-one in a previous life made the 'blob' too narrow:

OpenTTD:

image

TTD:

image

## Description

Change the calculate from `(FONT_HEIGHT - 1) * 8 / 5` to `FONT_HEIGHT * 9 / 6`:

image

## Limitations

Duplicated arithmetic but it can't be a single constant...

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by 2TallTyler — COMMENTED** [review]
Why can't it be a `const int CARGO_LEGEND_BLOB_WIDTH = FONT_HEIGHT_SMALL * 9 / 6`?

`this->legend.width` and the like are already `FONT_HEIGHT_SMALL`, so it's the same calculation.

**Comment by PeterN** [comment]
Because FONT_HEIGHT_SMALL is not a constant, it's a sneaky macro to call GetCharacterHeight(FS_SMALL) that was used to simplify updating code long ago...

**Comment by PeterN** [comment]
But good call, there's no reason we can't search & replace all those :-)

**Comment by 2TallTyler** [comment]
Scope creep!

Do you want to do that first, or merge this and add that to the "later" list?

**Review by 2TallTyler — DISMISSED** [review]

**Review by 2TallTyler — APPROVED** [review]

**Pull request merged**
