### PR TITLE
Update IDR currency to current exchange rate

### PR DESCRIPTION
**Pull request by JulianGro**
## Motivation / Problem
This PR updates the exchange rate of IDR, since the current exhange rate does not fit at all.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by orudge** [comment]
It looks like IDR was added in https://github.com/OpenTTD/OpenTTD/pull/8616 as 19 instead of 19,000 due to theoretical overflow issues. I don't know if anyone is especially likely to have more than £485 trillion in a game though...

**Comment by James103** [comment]
As a workaround, you could make a custom currency with the following parameters:
* Exchange rate: Rp&nbsp;19&NoBreak;**,000** = £ 1 (the bolded text is part of the Suffix and not the number itself)
* Separator: `,` (depending on locale)
* Prefix: `"Rp" NBSP`
* Suffix: `,000` (depending on locale)

**Comment by JulianGro** [comment]
> 

That is a nice idea. I have no idea how to switch between , and . depending on locale though.

**Comment by telk5093** [comment]
Note that there was a similar issue of KRW (#7616) but it is rejected.

**Comment by JulianGro** [comment]
So I have given this some thought and exploration.
From my point of view the best thing to do is actually to go forward with the current changes.

Adding a "thousand" to the currency seems very alien to at least the Indonesian I have talked to.
Having the rate be rounded to something like 18000 makes the last three digits never change in-game, which looks weird to me and isn't how the rest of the currencies are. (Even on GBP you have to pay £4,921 for a bus, instead of a more realistic price like £4,900 or £5,000)
Also trying to add ".000" or ",000" as a postfix is too much for me and my knowledge of C++ and the codebase; Hardcoding it to ".000" would look weird in locales that would normally use ",", and haven't been able to use something like `digitsepcur` instead.

For the currency overflow consideration, I don't think this should be too much of a problem. There is already a currency that has a 4901 multiplicator. And realistically, if there is overflow problems you are going to run into them eventually. This would just make it 4 times faster than on the currency with the current highest multiplicator.

**Comment by nielsmh** [comment]
All money calculations in the game are still done in whole GBP, and currency conversion is only done to display the figures. I'm not sure if currency display also uses the OverflowSafeInt type, but if it does then any overflow should instead saturate and it would rather look like you hit the ceiling for amount of money in the bank long before you actually do.
I'm not sure how common it is to ever get that much money in regular games, but I suppose if enough complaints come in it could be possible to add some sort of "you have more money than we can show" indicator, or possibly even an ultra-long multiplication of sorts.

**Comment by James103** [comment]
> I'm not sure if currency display also uses the OverflowSafeInt type

I can confirm that it does by loading the savegame from #8253, spending some money while the currency is GBP, then switching to a currency such as EUR, USD, or JPY (where more than one of that currency = £1), then spending some more money and seeing that the available balance remains at INT64_MAX in the displayed currency.

**Comment by ldpl** [comment]
Overflow isn't just about the total amount of money in company, there are some other places that do calculations with currency rates, they all need checking. For example, I had to fix one of such issues in settings display for #8386 as even 5k rates were buggy prior to that change. So it's unclear what's the safe max for the multiplier is, someone needs to go over all the code that uses rates and check for the limits. I know for sure 50k multiplier is buggy so 19k is getting pretty close.

**Comment by LordAro** [comment]
Yeah, intentional design decision as stated in the original PR. Changing the suffix might be more appropriate, but as you say, there's no real good alternative

**Pull request closed without merging**
