### PR TITLE
Codechange: [CI] switch MacOS to the macos-14 runner

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

We have a few commits that cannot be merged because they fail on MacOS. Not because the code is wrong, but because the current MacOS version uses an older XCode, which don't have the proper fixes to make those PRs work.

## Description

Switch to `macos-14`. All issues that initially came from this, are resolved in other PRs.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by TrueBrain** [comment]
https://github.com/TrueBrain/OpenTTD/actions/runs/8208446751/job/22451933562 to show the release build is also working fine.

**Comment by TrueBrain** [comment]
(And yes, merging this requires changing which MacOS build is mandatory, and requires all PRs pending to rebase).

**Review by rubidium42 — DISMISSED** [review]
Do we want to force macos-14, or should we wait until macos-latest points to macos-14?

If we force it, we need to change it back to macos-latest at some point, or we'll run into trouble when macos-14 gets deprecated.
If we don't force it, builds will start failing at some random point in Q2 of 2024 and then we need to merge this PR at that unfortunate moment.

I personally think forcing macos-14 will have less impact on development as we can plan for it, instead of the migration happening at a random time.

Having said that, should we force macos-12 for the 14 branch, so that won't start failing when macos-latest becomes macos-14 and this PR has not been merged in there?

**Comment by TrueBrain** [comment]
I have been thinking about this for a bit, and I have approached this the wrong way.

In general, we should always backport CI commits, as otherwise it might be that something works on master, and not on the release. And fixing those problems is very annoying. Also, that way it is more likely that releases will keep working.

This close for a new release, that is the only moment one can debate about this. But as we plan to do another RC, there is a much lower risk.

That said, I am going to do this PR a bit different, and split it in three. One which adds vcpkg to all targets, manually. So no matter what GitHub decides to do, our workflows work. The other to change macos to 14. And the last to change macos CI to arm64. And we should backport them all, if you ask me, before next RC :) Or otherwise wait with the latest -> 14 till just after the release, and backport it then.

**Comment by TrueBrain** [comment]
https://github.com/TrueBrain/OpenTTD/actions/runs/8215061859/job/22468166938 to show it still works fine :)

**Review by rubidium42 — APPROVED** [review]

**Pull request merged**
