### PR TITLE
Fix #6145: Prevent ships without valid orders from moving

### LINKED ISSUE #6145: High CPU usage for ships with empty orders
**_moogtrain_ opened the ticket and wrote:**

> The game would lag with 100% CPU usage on a single core when many ships with empty order lists are let to roam freely on large bodies of water. On my system (2.4GHz i5, 4GB RAM), having > 80 ships running freely on a body of > 500 tiles is enough to make the lag visible. Having more ships on the body of water OR having the ship on larger bodies of water _ would cause the game to lag even more. 
> 
> Steps to reproduce:
> 
> 1. Create new game (of any size, 64x64 is enough) with one side of the map edges be water.
> 2. Build a ship depot on the edge of the map with water.
> 3. Build one ship, lock the new ship window and spam the "Clone ship" button till you get a lot of ships.
> 4. Deploy all the ships from the ship depot, all at once.
> 
> This bug can be used to grief on servers (via DoS) as it would cause slow clients to freeze and get disconnected from the server.
> 
> Affects both YAPF and NPF pathfinders and verified on both Windows and Linux platforms.

**Reported version**: _1.4.3_
**Operating system**: _All_

---

### PR DESCRIPTION
**Pull request by nielsmh**
Alternative to #6784, at least in some respects.

This also attempts to solve the problem of order cycling (current order going around the orders list) if all the stops on the orders list are deleted, but their station sign still remains.

### CODE REVIEW

**Comment by nielsmh** [comment]
Just tested the pathological case of a dock with the docking area at the top tile, still works.

image

**Comment by PeterN** [comment]
I still stand by my comment that making ships stop is inconsistent with everything else.

**Comment by nielsmh** [comment]
However, stopped ships don't block track/roads the same way trains and road vehicles do, but on the contrary have much greater risk of getting further lost if they just roam randomly.

**Comment by TrueBrain** [comment]
We recently switched from Jenkins as CI to Azure Pipelines as CI. This means you need to rebase before this Pull Request will pass its checks. Sorry for the troubles!

**Comment by andythenorth** [comment]
I am -1 for the highly personal reason that I often use orderless ships to test newgrfs :D

**Comment by nielsmh** [comment]
#6784 was merged so this is no longer relevant.

**Pull request closed without merging**
