### PR TITLE
Change: New English capitalization

### PR DESCRIPTION
**Pull request by sheepo99**
## Motivation
This a redo of PR #8144. The first of the changes to English.txt as to reflect the rules in the new [Manual of Style](https://wiki.openttd.org/en/Development/Manual%20of%20style).

## Description
This commit covers only **isolated changes** on capitalization (i.e lines that I don't intend to alter further beyond capitalization changes) to bring consistency with new capitalization rules. Similar capitalization alterations in lines to be rewritten/changed or reformatted will be submitted in later PRs.

### CODE REVIEW

**Comment by PeterN** [comment]
- Window captions should stay/be made title-case.
- News messages should stay/be made title-case.
- Cargo types should stay lowercase. There is specific code that has upper case and lower case versions, and the changes break that.
- In my opinion, labels should also stay/be made title-case.

Maybe the "manual of style" needs to be tweaked. But most of these changes don't add anything.

**Comment by sheepo99** [comment]
>  Cargo types should stay lowercase. There is specific code that has upper case and lower case versions, and the changes break that.

I wasn't notified of this before. How do the text strings break it? It works just fine when load the lang file in game.

> Maybe the "manual of style" needs to be tweaked. But most of these changes don't add anything.

Current capitalization et al. is inconsistent. This manual was made to set some rules in stone.

**Comment by FLHerne** [comment]
Reply mostly @PeterN

There was a lot of discussion on this subject previously, which seemed to reach a consensus that it was an overall improvement on the current situation which is very inconsistent.

There wasn't any one convention that pleased everyone (e.g. I agree about cargo names, mostly for compatibility), but that's clearly impossible.

Given that @sheepo99 dropped this last time because of perceived hostility to changes -- which I admit was probably my fault at least in part -- it would be nice to be polite.

P.S. it's not actually clear to me which titles you're referring to, none seem to be changed. I've only skim-read yet though.

**Comment by PeterN** [comment]
> > Cargo types should stay lowercase. There is specific code that has upper case and lower case versions, and the changes break that.
> 
> I wasn't notified of this before. How do the text strings break it? It works just fine when load the lang file in game.

Break as in break consistency. They are already capitalised in the places they need to be capitalised. The NewGRF spec (items_of_cargo) suggests lower case in these places, and that's what NewGRF authors do.

Enough from me.

**Comment by 2TallTyler** [comment]
I'm going to close this since it was reviewed and then left unfinished for two years. #11134 did some work in this area, going the opposite direction from the Manual of Style in a few areas just to stay internally consistent. I'm not personally opposed to future changes, I just wanted to be consistent even if that means consistently "wrong." 😛 

To be clear, @sheepo99 or others should feel welcome to update and reopen this PR, or a new one. But it seems abandoned and we have too many open PRs to leave open abandoned PRs. 🙂

**Comment by sheepo99** [comment]
> I'm going to close this since it was reviewed and then left unfinished for two years. #11134 did some work in this area, going the opposite direction from the Manual of Style in a few areas just to stay internally consistent. I'm not personally opposed to future changes, I just wanted to be consistent even if that means consistently "wrong." stuck_out_tongue
> 
> To be clear, @sheepo99 or others should feel welcome to update and reopen this PR, or a new one. But it seems abandoned and we have too many open PRs to leave open abandoned PRs. slightly_smiling_face

With all due respect @2TallTyler, attempting to contribute towards OpenTTD as a translator/textual reviewer/editor was one of the most unwelcome experiences I've ever had as a software translator, and I do not intend to ever resume in the foreseeable future, nor do I recommend anyone to undertake a similar effort on their own until there is a clear consensus in letting language professionals do their work unimpeded and without interference.

I first approached this project with the intention of translating the game to my language, and found there were too many inconsistencies in the original English text for me to do a proper job. So I took it upon myself to first fix all the English text first and create universal standards along with a manual of style. This process, however, was hardly fought by several senior contributors of the OpenTTD team, who insisted on an inadequate and unreasonable submission and revision process (I was asked to submit textual alterations as logical commits, which makes no sense for text whatsoever), to which I  nevertheless complied. Upon submission of the respective PRs these went either ignored, went unrevised, or were hotly contested and nitpicked by contributors with little understanding on the subject, preventing it from ever moving further ahead. So two years after, it's unreasonable to ask me to reopen or update the PR when this whole process was nothing but hostile.

A tip for the future: take your non-code contributors seriously, and consider welcoming and openly recruiting more skills diversity if you ever want OpenTTD to attain a comparable level of polish and presentation close to anything minimally resembling a professional-looking game. Of all the open source projects I contributed text towards, this was by far my most frustrating experience, which is an absolute shame.

**Pull request closed without merging**
