### PR TITLE
Fix #8922: Crash when selling last member of shared order group while window was open

### LINKED ISSUE #8922: NOT_REACHED() crash when selling shared vehicles
## Version of OpenTTD

1.11.0-RC1

## Expected result

Selling vehicles with shared orders does not crash the game.

## Actual result

crash_reproduction

`NOT_REACHED triggered at line 1719 of ..\src\vehicle_gui.cpp`

## Steps to reproduce

This is a tricky one to reproduce. 

1. In the attached savegame `autosave14` (not the emergency save), open the New Mills Airport station (just north of the starting location in the savegame) and look at the list of trains with that station in its orders.
2. Group the list by shared orders
3. Train 289 is in the list, currently lost and near a depot. Click on it and send it to the depot
4. In the depot, drag the last vehicle (an EMU) off the train onto a new line
5. Click the Sell All button
6. A NOT_REACHED error should trigger

[crash_stuff.zip](https://github.com/OpenTTD/OpenTTD/files/6243812/crash_stuff.zip)

### PR DESCRIPTION
**Pull request by LordAro**
## Motivation / Problem
#8922
Vehicle GUI window (while showing shared orders) could become empty while open (selling all vehicles in group)

## Description
Close the window when shared order window's vehicle list becomes empty
Window was doing updates of internal state in OnPaint rather than OnInvalidateData which struck me as a bit weird, so moved stuff

Played around with it a bit (though not extensively), window still updates when it should, and doesn't crash

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
@btzy You may be interested in taking a look

**Comment by btzy** [comment]
This doesn't seem to work on my Windows computer... with this commit, toggling the "Group By" dropdown (i.e. step 2 of #8922) only changes the number on the left of each row, but doesn't actually group anything.  Without this commit, toggling the "Group By" dropdown works.

(The bug in #8922 can be reproduced on my computer though.)

**Comment by btzy** [comment]
I think this is not the right fix for the bug.  The root cause seems to be due to the fact that the user can now have a "Shared orders of 1 vehicle" window opened.  Previously, it was not possible to have such a situation because the shared orders window closes automatically when the user unshares the shared orders of 2 vehicles.

**Comment by btzy** [comment]
I made PR #8926, that prevents opening a shared order list of just one vehicle.

**Comment by LordAro** [comment]
Closed in favour of #8926

**Pull request closed without merging**
