### PR TITLE
Malaysia Ringgit as Currency

### PR DESCRIPTION
**Pull request by Limyx826**
Cause why not

Added Malaysia Ringgit pegged to British Pound at conversion rate of 5.

*Update the formatting

PS: First time doing actual pull request to a massive project. Need guidance.

### CODE REVIEW

**Comment by James103** [comment]
Can you please do the following?
1. Move your changes to a separate branch, different from `master`.
2. Format your commit message as follows: `Add: Malaysian Ringgit as Currency`

**Comment by Limyx826** [comment]
> Can you please do the following?
> 
> 1. Move your changes to a separate branch, different from `master`.
> 2. Format your commit message as follows: `Add: Malaysian Ringgit as Currency`

alright

**Comment by LordAro** [comment]
No. There have been 2 PRs for this already, please update an existing one. It is not an issue using your own master branch, just limits your own usage. Use rebasing to make changes to commit (or message), rather than making yet another PR

**Comment by Limyx826** [comment]
Ok. That's the first time I use such advanced git command. Guess there's a first time for everything.

**Pull request closed without merging**
