### PR TITLE
Fix: [NewGRF] Negative results from cargo-income callback 39.

### PR DESCRIPTION
**Pull request by frosch123**
## Motivation / Problem

| Callback result | Expected meaning | Actual meaning | Comment |
| --- | --- | --- | --- |
| 0 to 0x3FFF | 0 to 0x3FFF | 0 to 0x3FFF | good |
| 0x4000 to 0x7FFF | -0x4000 to -1 | 0 to 0x3FFF | wrong |

## Description

The sign bit was discarded, now it is used.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by glx22 — APPROVED** [review]

**Comment by PeterN** [comment]
Value is 14 bits, 0-3FFF, so with -8000 it becomes -8000 to -4001?

**Comment by frosch123** [comment]
Result is 15 bit 0-7FFF. 0x4000 (bit 14) is the sign bit.

**Comment by PeterN** [comment]
Result is only 14 bits, from bits 0-13, bit 14 is the signed flag, bit 15 is the callback identifier.
`int result = GB(callback, 0, 14);`

**Comment by frosch123** [comment]
Ah damn, I didn't notice callback != result.

**Pull request closed without merging**
